### ISSUE TITLE
Genserver/Task.Supervisor crash error/stacktrace is too vague in sentry

### ISSUE THREAD

**Issue by sikanhe** [getsentry/sentry-elixir#101]
I had a bug in the code that caused genservers being crashed, and the only print out I got in the sentry app was 

```
Elixir.ArgumentError: argument error
  File "gen_server.erl", line 812, in :gen_server.terminate/7
  File "proc_lib.erl", line 247, in :proc_lib.init_p_do_apply/3
``` 

I had to ssh into to the server to get the full error stack trace and crash report: 

```** (ArgumentError) argument error
    (kernel) gen_tcp.erl:149: :gen_tcp.connect/4
    (hackney) src/hackney_connect.erl:246: :hackney_connect.do_connect/5
    (hackney) src/hackney_connect.erl:37: :hackney_connect.connect/5
    (hackney) src/hackney.erl:328: :hackney.request/5
    (quesly) lib/quesly/utils/file.ex:20: App.Utils.File.download/3
    (quesly) web/models/audio_file.ex:51: App.AudioFile.import_from_url/1
    (quesly) lib/quesly/harbor/series_resync.ex:52: anonymous fn/2 in App.Harbor.Resync.resync/1
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
```

**Comment by mitchellhenke** [comment]
Thank you for creating this issue, this is something I'd like to improve.  Due to the way processes are, sometimes errors reported are less than helpful.

Could you gist a simple reproduction?

**Comment by mitchellhenke** [comment]
I'm not positive, but it appears to partially be related to an error occurring when a GenServer tries to call the [`terminate/2`](http://elixir-lang.org/docs/v1.3/elixir/GenServer.html#c:terminate/2) callback.  Is `terminate/2` defined for the GenServer?

**Comment by sikanhe** [comment]
@mitchellhenke no terminate/2 is not defined, i will try to recreate a gist this weekend

**Comment by walter** [comment]
@mitchellhenke can you talk more about the error with GenServer, please? How does it present itself? We've started experiencing some mysterious timeouts from a package's GenServer that calls `Task.await` not long after switching to Sentry. Shot in the dark that it is related, but I thought I would check.

**Comment by mitchellhenke** [comment]
@walter sorry, my sentence above may have been unclear.  To be more specific, I meant things like context and stacktrace will get lost when communicating over multiple processes.

The library executes the HTTP calls asynchronously, so it shouldn't hold up normal execution.

**Comment by walter** [comment]
Good to know. We ruled out Sentry as the cause in a test as well. Looking more like Perf.
