### ISSUE TITLE
Load dynamic values from system env

### ISSUE THREAD

**Issue by rafaeljesus** [getsentry/sentry-elixir#107]
The current [code](https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/client.ex#L94) does not load dynamic env var using `:system`

```elixir
config :sentry,
  dsn: {:system, "SENTRY_DNS"},
```

This is useful when deploying in production environment using [exrm](https://github.com/bitwalker/exrm).

I would appreciate this feature asap as I am not receiving errors on my Sentry account or if you have any other suggestion please let me now,

Thank guys

**Comment by mitchellhenke** [comment]
I don't have a huge amount of experience with exrm/distillery, so please correct me if I'm off.  My understanding is that for libraries supporting the `{:system, "CONFIG_KEY"}` convention, when the release is built, it will store that tuple normally without fetching from System. Upon the release being run, the library will see that pattern, and read from the config at runtime.

I believe Phoenix only supports it for a couple parts of the configuration (PORT and HOST).  Would adding it for the dsn be sufficient, or would it be necessary for all configuration keys?

**Comment by rafaeljesus** [comment]
@mitchellhenke Thank you for your reply! Yes that's the behavior mate. I also request it on [ex_statsd](https://github.com/CargoSense/ex_statsd/pull/32) I can totally submit a PR you you want, wdyt?

**Comment by mitchellhenke** [comment]
@rafaeljesus cool, sounds good.  I can likely get to it this week.
