### ISSUE TITLE
Documentation not displaying in GH

### ISSUE THREAD

**Issue by Ebtoulson** [getsentry/sentry-elixir#112]
`describe::` is being used throughout documentation but GH is not displaying it. 

refer to the different settings sections: https://github.com/getsentry/sentry-elixir/blob/master/docs/config.rst

**Comment by mitchellhenke** [comment]
The issue stems from different documentation formats.  We maintain separate docs for Sentry's website , which live in the `docs` folder (the docs generated from the file you linked are [here](https://docs.sentry.io/clients/elixir/config)), as well as the ExDoc docs for [hexdocs.pm](hexdocs.pm) and the README for those viewing on GitHub.

The Sentry doc `.rst` files are apparently not displayed super well by GitHub, but I'm not sure if there's much we can do 😕

Absent anything we can do, I'm going to close this issue for now.
