### ISSUE TITLE
Stacktrace Unhelpful 

### ISSUE THREAD

**Issue by maxsalven** [getsentry/sentry-elixir#114]
If I try to render a view that references an attribute that has not been preloaded with Ecto:

Without `use Sentry.Plug`, I know exactly what went wrong and in which file
```
** (exit) an exception was raised:
    ** (KeyError) key :id not found in: #Ecto.Association.NotLoaded<association :user is not loaded>
        (myapp) web/views/user_view.ex:14: MyApp.UserView.render/2
    ...
```

With `use Sentry.Plug`, I have no idea what the source of my error is, which makes Sentry of very limited use for me:
```
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) lib/enum.ex:131: Enumerable.member?/2
        (elixir) lib/enum.ex:1352: Enum.member?/2
        (sentry) lib/sentry.ex:103: Sentry.send_event/1
        (plug) lib/plug/error_handler.ex:96: Plug.ErrorHandler.__catch__/5
        (myapp) lib/myapp/endpoint.ex:1: MyApp.Endpoint.phoenix_pipeline/1
        (myapp) lib/plug/debugger.ex:123: MyApp.Endpoint."call (overridable 3)"/2
        (myapp) lib/myapp/endpoint.ex:1: MyApp.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by mitchellhenke** [comment]
Thanks for opening this.  It looks like the issue is that you don't have any `included_environments` configured, as it's pointing to this line: https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry.ex#L150

Could you try setting `included_environments` in your configuration and see if the issue persists?  If that does turn out to be the issue, we can make the error message more helpful.

**Comment by maxsalven** [comment]
Thanks, yes this fixed it. I only added the `config :sentry ...` data to my `prod.exs` config file, wrongly assuming I could leave the `dev.exs` config untouched.

**Comment by mitchellhenke** [comment]
Yeah, if Sentry is running, it will check the config to see if it should send events.  I've created #118 to find a better experience for users that run into this.

**Comment by mitchellhenke** [comment]
Thanks again for letting me know about this 🙂

**Comment by aptinio** [comment]
For what it's worth, the `deps/sentry` directory of my phoenix app doesn't include a `config` directory, which I notice the repo does. I think this is where the default configs are currently intended to be taken from.

**Comment by aptinio** [comment]
I've created PR #124 to address this. I hope it helps.
