### ISSUE TITLE
protocol String.Chars not implemented for {:error, :einval}

### ISSUE THREAD

**Issue by syamilmj** [getsentry/sentry-elixir#115]
As per doc, we put these inside our Phoenix router:

```
use Plug.ErrorHandler
use Sentry.Plug
```

However, this overrides Phoenix's error handler and effectively making it impossible to trace the actual error, while spitting this error:

```
protocol String.Chars not implemented for {:error, :einval}
```

Any ideas?

**Comment by mitchellhenke** [comment]
Hi, thanks for opening this. Is there a fuller stacktrace available? Sentry should work with Phoenix without issue.

**Comment by syamilmj** [comment]
Found the cause, let me send a PR
