### ISSUE TITLE
Allow assigning user data to payload in `Sentry.Plug`

### ISSUE THREAD

**Issue by hauleth** [getsentry/sentry-elixir#121]

**Comment by mitchellhenke** [comment]
Hi @hauleth, thanks for opening this.  Could you expand on what you mean?

**Comment by hauleth** [comment]
After some search I have found that what I meant is already there in `Sentry.Context` but it is quite hard to find (as it isn't mentioned in Hex only in Sentry docs). I would recommend adding info about setting context in `README`.

**Comment by mitchellhenke** [comment]
Yeah, the `Sentry.Context` docs could definitely be expanded upon.  Thank you for the heads up, I'll create an issue for it 🙂
