### ISSUE TITLE
`Sentry.Context.add_breadcumb` should accept keywords list instead/alongside map

### ISSUE THREAD

**Issue by hauleth** [getsentry/sentry-elixir#125]

**Comment by mitchellhenke** [comment]
Thanks for opening this 🙂 

Could you share some more detail?  A keyword list can't be encoded to JSON, so it would be difficult to pass it to the Sentry API.

**Comment by hauleth** [comment]
There is method `Enum.into(klist, %{})` which would solve the problem. 

--
Łukasz Jan Niemier

Dnia 23 lut 2017 o godz. 21:27 Mitchell Henke <notifications@github.com> napisał(a):

**Comment by mitchellhenke** [comment]
Do you have a use case where passing a map is more difficult, but passing a keyword list isn't?

I think that accepting a keyword list could be a misleading interface if it ultimately has to be a map anyway.

**Comment by hauleth** [comment]
Everywhere ;)

Elixir emulates keyword arguments using keyword list so this

```elixir
Sentry.Context.add_breadcrumb(%{…})
```

become

```elixir
Sentry.Context.add_breadcrumb(…)
````

Also dynamically building breadcrumb is easier with keyword list as you can just:

```elixir
list = []
list = [{:message, "test"} | list]

# Map one

map = %{}
map = Map.put(map, :message, "test")
```

I think it is also nice sugar when you do a lot breadcrumbs and I think that BEAM will optimize it out anyway.

**Comment by hauleth** [comment]
I have opened PR that implements this behavior and provide some other cleanups on `Sentry.Context` module.
