### ISSUE TITLE
Never crash?

### ISSUE THREAD

**Issue by Mazyod** [getsentry/sentry-elixir#126]
Hello,

I have misused sentry by passing a non-encodable object as a `:extra` opts when capturing an exception, and that caused my game sessions supervisor to blow up, losing all active game sessions.

Given that ensuring the passed object is JSON encodable isn't as trivial as adding a `@spec`, and also given that any error handling code should be as robust as possible, would it make sense to simply attempt to encode the `:extra` parameter as JSON, but if it fails, just inspect it with `inspect(x, pretty: true)`?

https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/client.ex#L27

Thanks

**Comment by Mazyod** [comment]
If you think that this is actually by design and it's up to the developer to handle possible errors/exceptions that may rise from their misuse, which is completely understandable, I'd suggest at least moving the risky code, (aka `Posion.encode!`) out of the client, since the client is removed during testing.

So, my code tests the Sentry integration up to generating the `Event` object, but once that object is created, it never gets sent to the `@client`, since that is `nil` during tests, which leads to the risky code to never be exercised during tests.

**Comment by mitchellhenke** [comment]
Hm, yeah, I see what you mean.  I will put something together to handle this better.

As far as `@client` being nil during tests, it should default to `Sentry.Client` unless you explicitly set it to nil.  If you'd like to have Sentry function as far as making HTTP calls during your tests, the tests around `Sentry.Client` should have some decent examples.  You could also write a client that does nothing, or logs, etc.
