### ISSUE TITLE
Consider including logger metadata as tags in reported errors

### ISSUE THREAD

**Issue by myronmarston** [getsentry/sentry-elixir#137]
Elixir's `Logger` supports the concept of `metadata`, which are arbitrary key-value pairs that, if configured, will be included in all logged messages in a standardized format.  In our application we have some standard things that define the context for every process (such as `user`) which we include in `Logger.metadata` -- that way, every logged message includes them in an easy-to-parse, standard format.

Unfortunately, since we don't also include those bits of data in our exception messages, we don't have that context when looking at errors reported to Sentry.  That makes it hard to troubleshoot errors since the context in `Logger.metadata` is so important to understanding the error (we need to know, for example, which user's data triggered the error).

It would be a huge help if `Logger.metadata` was included in errors submitted to sentry.  It seems like it would fit naturally in `tags`.  Is that something you would consider?

**Comment by mitchellhenke** [comment]
Thanks for opening this 🙂 

I'm not super familiar with Logger metadata, but it is stored per process?  If that is the case, you _should_ be able to do something like:
```elixir
Sentry.Context.set_user_context(%{user_id: 34, username: "mitchellhenke"})
```
in the same place you set Logger metadata, and have that information appear in Sentry:
![image](https://cloud.githubusercontent.com/assets/1430443/23956825/b16161ce-096b-11e7-9ec1-29e0db4572f9.png)

Sentry context is also set per-process, so they should work somewhat similarly.  If the above does solve this for you sufficiently, the feature is less compelling.  If not, I can take a deeper look.

**Comment by myronmarston** [comment]
> I'm not super familiar with Logger metadata, but it is stored per process?

Yep:

https://github.com/elixir-lang/elixir/blob/v1.4.2/lib/logger/lib/logger.ex#L307-L309

> If that is the case, you should be able to do something like:

I wasn't aware of `Sentry.Context`, so thanks for that tip!  This would definitely work, but would be pretty sub-optimal for us, for a few reasons:

* We set `Logger.metadata` in _lots_ of places.  (In my project, `ack Logger.metadata`) returns 29 instances).  It would be a bunch of work to update them all (either to call both `Logger.metadata` and `Sentry.Context.set_user_context` or to call a new function that delegates to both).
* In our umbrella app, we have a few packaged deployable apps, and then lots of mini-apps that act as internal services.  Sentry is only directly depended upon from the packaged deployable apps (as it's basically just a strategy for how errors are reported).  I don't really want to add a dependency from all of our sub-apps (currently 44 and counting!) on sentry just to make sure our process context is stored in both the logger and in sentry.
* We have some utilities that we use when spawning new processes (such as tasks) that copy logger metadata form the parent to the child process so that the metadata is available when logging messages from the spawned process.  We'd have to also have it copy `Sentry.Context` data as well, but it seems sub-optimal to have to always copy both.

Since Logger is part of the Elixir standard library, and, in my experience, is the standard way to store process context metadata, it would be ideal if this library could use it automatically (or when a user opts-in via a config setting); that way every sentry-elixir user who uses `Logger.metadata` like we do does not have to make tons of updates to their application just to make their metadata available to Sentry.

I _think_ that implementing this would be as simple as making [`Sentry.Context.get_context`](https://github.com/getsentry/sentry-elixir/blob/9077b52c5b25f257d53f58126d671343471b4142/lib/sentry/context.ex#L56-L58) merge what it's stored in the process dictionary with what `Logger.metadata/0` returns.  It probably makes sense for it to be an opt-in feature, so that users aren't surprised by the logger metadata always being included, and also to guard against cases where `Logger` isn't running.  While it's part of the standard library, it has to be included as an application in releases (e.g. with Exrm or distillery) to be usable at runtime in production, I believe.  (That's why `mix new` includes it in the generated mix.exs).

Thoughts?

**Comment by mitchellhenke** [comment]
Thanks for explaining, it does seem difficult to fit current functionality into that use-case.  If you don't mind, I have a few more questions 🙂 

There are different 'contexts' within Sentry that the metadata key/values could be added to (User, Tags, HTTP, and Extra).  SDK Docs for that are [here](https://docs.sentry.io/clientdev/context/).  Simple case would be merging the Logger metadata into the Extra context.  Would that be sufficient?  You wouldn't need to pick which context it should use or specify which keys from the metadata to take?

**Comment by myronmarston** [comment]
That's a great question.  I'm not familiar with how the sub-contexts are used (e.g. how is the data within them used and surfaced within the Sentry UI?).  Tags I understand (we use them a bit) so it's easy for me to understand how they are use and I was originally thinking `Logger.metadata` would just be merged into that.  It's not clear to me how `extra` context is used--can you explain?

What might be best is providing a useful, simple default (e.g. merging all metadata into `tags` or `extra`, depending on what makes more sense), and then support users optionally configuring a custom `merge` function, which could be used by the user to merge different parts of `Logger.metadata` into different contexts based on their application's needs.

**Comment by myronmarston** [comment]
> Is that something you think could fit for your application, or is that too much flexibility?

I quite like it!  One potential issue: since the `Logger.metadata` is stored in the process dictionary, that function will have to be called from the process from which the event originates.  If it gets called in a spawned task (or whatever), `Logger.metadata` will be empty.

I'm also not sure if the lambda form will ever work for people who deploy their app as releases with a tool like ExRM or distillery.  Such tools compile all mix config down to a `sys.config` file of erlang terms and I'm not sure if it supports anonymous functions in there.  Sounds like you plan to support MFA, which is a nice work around, but you may want to emphasize as the primary case so that users don't try the lambda, have it work in dev, try deploying, and have it fail.

Finally, the name `pre_event_send_function` could be better, IMO.  Maybe something like `before_send_event` ?

**Comment by mitchellhenke** [comment]
We allow for setting tags context on a global basis through config, but otherwise both `Sentry.Context` and `Logger.metadata` are limited to in-process storage without much we can do on the Sentry side as far as I understand.

I 100% agree MFA should be the primary option, and much prefer your naming.

Thank you for taking the time to discuss and help me work this out!  I plan on putting a PR together for it today or early next week.  You're of course not obligated to, but I can mention you on it if you'd like to take a look before it gets merged. 🙂

**Comment by myronmarston** [comment]
> We allow for setting tags context on a global basis through config, but otherwise both Sentry.Context and Logger.metadata are limited to in-process storage without much we can do on the Sentry side as far as I understand.

Right, there's definitely not much you can do in general, but there is something you could do that would make this solution completely unusable for our use case: wait to use this configured function until you are in the [spawned task](https://github.com/getsentry/sentry-elixir/blob/9077b52c5b25f257d53f58126d671343471b4142/lib/sentry/client.ex#L33) that is used to send events to sentry in the background.  If you did that, this config function would never work for our use case.  As long as you avoid that, it should work fine as long as our sentry events originate from processes with `Logger.metadata` set.

That's the only point I was trying to make.

> You're of course not obligated to, but I can mention you on it if you'd like to take a look before it gets merged.

Sure!

**Comment by mitchellhenke** [comment]
>Right, there's definitely not much you can do in general, but there is something you could do that would make this solution completely unusable for our use case: wait to use this configured function until you are in the spawned task that is used to send events to sentry in the background. If you did that, this config function would never work for our use case. As long as you avoid that, it should work fine as long as our sentry events originate from processes with Logger.metadata set.

Yep, sorry, I didn't communicate it well.  That's the plan.
