### ISSUE TITLE
Allow some error type to be excluded from logging

### ISSUE THREAD

**Issue by hdra** [getsentry/sentry-elixir#152]
Similar to how `FunctionClauseError` and `Phoenix.Error.NoRouteError` is ignored from reporting, it would be very useful to allow other types of error such as authentication error to be excluded from reporting as well. 

Frameworks like [Laravel](https://laravel.com/docs/5.4/errors#report-method) have a `$dontReport` attribute in its exception handler that can be used with Sentry to exclude certain kind type of exceptions from logging. Maybe something similar can be achieved with app env and some macros in Elixir?

**Comment by mitchellhenke** [comment]
Does the `Sentry.Filter` behaviour solve this?  https://hexdocs.pm/sentry/Sentry.html#module-filtering-exceptions

**Comment by hdra** [comment]
Actually, I think that would. Sorry, wasn't aware of that option. Thank you.

**Comment by mitchellhenke** [comment]
@hdra no worries, it isn't mentioned in the README.  I should at least add a link to it.
