### ISSUE TITLE
Use stacktraces on exit

### ISSUE THREAD

**Issue by mitchellhenke** [getsentry/sentry-elixir#156]
Creating an issue to track https://github.com/erlang/otp/pull/1448 and use it if it gets merged for Erlang 20

**Comment by jalcine** [comment]
What else is needed here?

**Comment by mitchellhenke** [comment]
I had forgotten about this, thanks for reminding me 🙂 

I think this may be outdated as I saw news before Erlang 20 was released about stacktraces on exits.  It appears it is only related to logger output (OTP-14089): [Erlang 20 release notes](http://erlang.org/download/otp_src_20.0.readme), and so isn't something Sentry could potentially make use of.
