### ISSUE TITLE
Source code scan in build step scans entire disk if project root dir is /

### ISSUE THREAD

**Issue by thurloat** [getsentry/sentry-elixir#168]
May not be a huge bug -- but when building a docker build-step container for my elixir project, the compilation would spin continuously on compiling this line https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/event.ex#L30 because I added my source code to `/` in my docker container (bad practice obviously). 

It would never complete once it hit `/proc` because it recursively followed the `/proc/self/` chain to infinity. Tracked it down following `strace` of the `mix compile` process.

Not sure if there's some sort of safety/sanity checking that could or even should be put in place to stop this from happening. I could see it causing real world grief if someone had a legit link to some other set of system libraries / configs / utils.

Some potential fixes for this might be:

 - ignore symlinks (might be bad if people are using them legitimately)
 - detect recursion (harder to implement probably)
 - ignore /proc (only catches one case of a bad programmer)
 - tell me to shut up (the likely outcome)

Cheers!

**Comment by mitchellhenke** [comment]
Hey, thanks for opening this!  Something like this crossed my mind as possible, but I'm not super sure how to best mitigate a problematic config :/
