### ISSUE TITLE
mix deps.compile fails

### ISSUE THREAD

**Issue by KamilLelonek** [getsentry/sentry-elixir#183]
I cannot compile my code with `sentry`:

```
== Compilation error on file lib/sentry/event.ex ==
** (ArgumentError) application :sentry is not loaded, or the configuration parameter :enable_source_code_context is not set
    (elixir) lib/application.ex:261: Application.fetch_env!/2
    lib/sentry/event.ex:38: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

could not compile dependency :sentry, "mix compile" failed. You can recompile this dependency with "mix deps.compile sentry", update it with "mix deps.update sentry" or clean it with "mix deps.clean sentry"
```

```elixir
  defp deps do
    [
      {:phoenix, "~> 1.3.0-rc"},
      {:phoenix_ecto, "~> 3.2"},
      {:cowboy, "~> 1.1"},
      {:postgrex, "~> 0.13"},
      {:ecto, "~> 2.1"},
      {:gettext, "~> 0.11"},
      {:sentry, "~> 5.0.0"},
      # ...
    ]
  end
```

```elixir
config :sentry,
  dsn:                        "...",
  enable_source_code_context: true,
  use_error_logger:           true,
  root_source_code_path:      File.cwd!,
  tags:                       %{env: "production"},
  environment_name:           Mix.env(),
  included_environments:      [:prod]
```

**Comment by mitchellhenke** [comment]
@KamilLelonek thanks for opening this!  Unfortunately, I'm not able to reproduce the error with that configuration.  Did this configuration work in the past and break when you updated to `5.0.0`?

**Comment by KamilLelonek** [comment]
I started with `5.0.0` and it broke immediately. I haven't tried any other versions.

**Comment by KamilLelonek** [comment]
`4.0.3` fails as well:

```
== Compilation error on file lib/sentry/event.ex ==
** (ArgumentError) application :sentry is not loaded, or the configuration parameter :enable_source_code_context is not set
    (elixir) lib/application.ex:261: Application.fetch_env!/2
    lib/sentry/event.ex:29: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

could not compile dependency :sentry, "mix compile" failed. You can recompile this dependency with "mix deps.compile sentry", update it with "mix deps.update sentry" or clean it with "mix deps.clean sentry"
```

**Comment by KamilLelonek** [comment]
I tried to explicitly list `:sentry` in `applications` or `extra_applications` but nothing changed.

**Comment by mitchellhenke** [comment]
@KamilLelonek hmm, this sounds as though there's a configuration issue somewhere.

A few more questions if you don't mind.  What version of Elixir are you on?  Is the file above the prod configuration in `config/prod.exs`?  What's in your `config/config.exs`?   What command are using to compile?

**Comment by KamilLelonek** [comment]
1. `Elixir 1.4`
2. `config/config.exs`
3. `mix do deps.get, deps.compile`

**Comment by mitchellhenke** [comment]
@KamilLelonek I put the config in a new Phoenix 1.3 project [here](https://github.com/mitchellhenke/sentry_testing), but was unable to reproduce.  If you could look over the config and see how it compares to yours, that would be super helpful in trying to track this down.

**Comment by KamilLelonek** [comment]
Sure, I'll let you know soon.

**Comment by mitchellhenke** [comment]
Played around a bit with https://github.com/mitchellhenke/sentry_testing/pull/1, and I'm admittedly not too familiar with Docker, it looks like it may not have the `config/` folder available when trying to compile.  Adding `COPY config/*.exs ./config/` fixed it for me, though you then run into similar issues as #168 since `root_source_code_path` being set to `File.cwd!` will result in it being set to `/` and scanning everything in that directory.  I'm not sure on what Docker best practices are, but setting up the build to happen in a subdirectory could alleviate the issue.

If my understanding is correct, I'll probably close this issue in the next couple of days.

**Comment by KamilLelonek** [comment]
OK, I'll check if that's the problem, and will confirm here.

**Comment by KamilLelonek** [comment]
So I added:

```dockerfile
COPY config/*.exs ./config/
```

before

```dockerfile
RUN mix do deps.get, deps.compile
```

and it hangs on:

```shell
==> sentry
Compiling 12 files (.ex)
Compiling lib/sentry/event.ex (it's taking more than 10s)
```

**Comment by mitchellhenke** [comment]
right, this is a separate issue.  #168 describes the problem in that since it recursively reads files at compile time in the root project directory when you use `File.cwd!`, it means it's going to read through all of the files in the Docker root directory, which will take some time.

The project should be copied into its own directory to avoid this.

**Comment by KamilLelonek** [comment]
Ah, OK, let me try it then.

**Comment by KamilLelonek** [comment]
It seems that adding:

```dockerfile
WORKDIR /opt/sentry-testing
```

fixes the problem!

**Comment by jeroenbourgois** [comment]
Same problem here, but I am using Elixir 1.5.0. I tried to the test project of @mitchellhenke but still having the same errors. Also using Phoenix 1.3

**Comment by mitchellhenke** [comment]
@jeroenbourgois are you using docker?

**Comment by luisalima** [comment]
I'm having the same problem (not using docker), with Phoenix 1.3 and Elixir 1.5. I tried with Phoenix 1.2 and Elixir 1.3 before, also failed.

Here is the diff, for Phoenix 1.3, Elixir 1.5:

```diff
diff --git a/config/config.exs b/config/config.exs
index 6ab1b29..4ca3994 100644
--- a/config/config.exs
+++ b/config/config.exs
@@ -22,6 +22,12 @@ config :logger, :console,
   format: "$time $metadata[$level] $message\n",
   metadata: [:request_id]

+# configure sentry
+config :sentry,
+  dsn: System.get_env("SENTRY_DSN"),
+  included_environments: [:prod, :dev],
+  environment_name: Mix.env
+
 # configure mix_test_watch
 if Mix.env == :dev do
   config :mix_test_watch,
diff --git a/lib/lists_server_web/router.ex b/lib/lists_server_web/router.ex
index 35babf9..ba212bf 100644
--- a/lib/lists_server_web/router.ex
+++ b/lib/lists_server_web/router.ex
@@ -1,5 +1,7 @@
 defmodule ListsServerWeb.Router do
   use ListsServerWeb, :router
+  use Plug.ErrorHandler # Sentry
+  use Sentry.Plug       # Sentry
   alias ListsServer.Plugs.APIVersion
   alias ListsServer.Plugs.CheckAuthToken

diff --git a/mix.exs b/mix.exs
index 66a523e..6cb9f24 100644
--- a/mix.exs
+++ b/mix.exs
@@ -20,8 +20,10 @@ defmodule ListsServer.Mixfile do
   # Type `mix help compile.app` for more information.
   def application do
     [mod: {ListsServer, []},
-     applications: [:phoenix, :phoenix_pubsub, :cowboy, :logger, :gettext,
-                    :phoenix_ecto, :postgrex, :ex_aws, :hackney, :sweet_xml]]
+     applications: [:sentry, :logger,
+                    :phoenix, :phoenix_pubsub, :cowboy, :logger, :gettext,
+                    :phoenix_ecto, :postgrex, :ex_aws, :hackney, :sweet_xml
+                    ]]
   end

   # Specifies which paths to compile per environment.
@@ -44,7 +46,8 @@ defmodule ListsServer.Mixfile do
      {:mix_test_watch, "~> 0.3", only: :dev, runtime: false},
      {:ex_aws, "~> 1.0"},
      {:sweet_xml, "~> 0.6"},
-     {:hackney, "~> 1.6"}
+     {:hackney, "~> 1.6"},
+     {:sentry, "~> 5.0.1"}
     ]
   end
```

**Comment by jeroenbourgois** [comment]
@mitchellhenke no, no Docker yet, just on my local machine

**Comment by chalmagean** [comment]
Adding `enable_source_code_context: false` seems to fix this issue. That option is a required config option, but admittedly not very obvious.

**Comment by jeroenbourgois** [comment]
@chalmagean indeed that fixed it for us, thank you!

**Comment by neektza** [comment]
I'm having the same problem. Elixir 1.4.4 & Phoenix 1.3 (rc-1), without Docker.

**Comment by mitchellhenke** [comment]
@chalmagean @jeroenbourgois I've released [6.0.0](https://gist.github.com/mitchellhenke/ffe2048e708fd7dd32d8d0a843daddf3) that no longer requires `enable_source_code_context`.  If you have any suggestions on making error messages clearer, I'd be happy to improve them! 🙂

**Comment by jeroenbourgois** [comment]
@mitchellhenke thank you!

**Comment by luisalima** [comment]
@mitchellhenke version 6.0.0 worked for me, thank you! 👍

**Comment by feld** [comment]
> It seems that adding:
> 
> ```dockerfile
> WORKDIR /opt/sentry-testing
> ```
> 
> fixes the problem!

Can we put this in the README for people who deploy their Elixir apps in Docker containers?
