### ISSUE TITLE
Question: Calling Sentry from Long Running Process

### ISSUE THREAD

**Issue by ryan-mahoney** [getsentry/sentry-elixir#188]
I have a function that is called both by a short-lived phoenix process and by a other longer running process that are not invoked via a web request.

This function adds extra context (with unique key values) every time it is called.

My question is... when this is called from a long-running process... is the process dictionary just going to grow and grow since it will never be purged?

Thanks!

**Comment by mitchellhenke** [comment]
@ryan-mahoney From what it sounds like, yep.  The long-running process will continue adding to its process dictionary.  It's difficult to say if it will grow to the point of being problematic though.

**Comment by ryan-mahoney** [comment]
Thanks for your answer -- that is what I saw in the code, but I just wanted to be sure.

What I've decided to do is count the number of messages that I've put into the process table for sentry. When the count get's above a certain threshold, I purge the table.

I expect that this approach will have low overhead and it will prevent the possibility of a slow memory leak from becoming a problem.

**Comment by mitchellhenke** [comment]
Glad to help clarify!

Your solution sounds good to me, but if there's ever something Sentry can do to make it easier going forward, I'd be happy to make it happen.  For now though, I'll close this issue 🙂
