### ISSUE TITLE
only top level params are scrubbed by default

### ISSUE THREAD

**Issue by manukall** [getsentry/sentry-elixir#189]
the default body scrubber only sanitized top level params. i think it's quite common to have even sensitive parameters nested, like
```
%{
  "user" => %{
    "email" => "user@example.com",
    "password" => "hunter2"
  }
}
```
for a login page.

in my opinion, it would be great if the default scrubber would handle those cases. especially because this is quite a sensitive and dangerous issue and people might not be aware.

**Comment by mitchellhenke** [comment]
@manukall Thanks for opening this.  Definitely a common use case and one I did not consider.  I should be able to take care of this soon!

**Comment by manukall** [comment]
thanks!
