### ISSUE TITLE
Remove :use_error_logger configuration

### ISSUE THREAD

**Issue by mitchellhenke** [getsentry/sentry-elixir#190]
Received another report along the same lines as #144, where setting `use_error_logger: true` did not set up the handler properly.  Adding `:error_logger.add_report_handler(Sentry.Logger)` into the user's application start method resolved it, so we'll just have to remove this: https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry.ex#L105-L107

and update documentation.

**Comment by RobinClowers** [comment]
That would be great, I was just bitten by this as well.

**Comment by mitchellhenke** [comment]
@RobinClowers Thank you, it's good to know it's a bigger issue than I initially thought.  This is at the top of my list.
