### ISSUE TITLE
Sentry client should log exception ID

### ISSUE THREAD

**Issue by samphilipd** [getsentry/sentry-elixir#209]
As a developer I would like to quickly and easily grep the application logs for an exception. Currently I have to do this by timestamp which sometimes doesn't match exactly.

I would like to be able to grep the logs for the Sentry event id (e.g. `c112dcfedc2d4b528ab45583608c040b`) so I can easily find the exception logging output.

**Comment by mitchellhenke** [comment]
Thanks for opening this issue!  The best way to do this might be using the [:after_send_event](https://hexdocs.pm/sentry/Sentry.Client.html#module-configuration) hook.  Would that work for your use case?

**Comment by samphilipd** [comment]
@mitchellhenke That's perfect! Thank you. Although I am surprised that Sentry does not log the exception ID by default.

One more question - in the example hook it shows how to add logging for when Sentry fails to send an event. Does this mean that is not logged by default?

**Comment by samphilipd** [comment]
@mitchellhenke I tried to implement the anonymous functions in the config as shown in the documentation you linked. Sadly this is not compatible with distillery. Attempting to release fails with an error.

Reason for this is that you can't have anonymous functions in config - see this issue: https://github.com/bitwalker/distillery/issues/185

Do you have any other suggestions for us?

**Comment by mitchellhenke** [comment]
@samphilipd we do our best to provide good defaults, but differing use cases make this hard.  As an example, some use Logger itself as a source of reporting errors.  It can certainly be worked around, so if there are many users where this is an issue, it can be revisited, but the flexibility to choose Logger level and format on a per event basis feels like the best path for now.

A `{module, function}` tuple of arity 2 should work as well.

**Comment by samphilipd** [comment]
Doh! Missed that part of the documentation. Anyway, thanks for the help, this seems to be working now.

**Comment by mitchellhenke** [comment]
No worries! 🙂 

If you run in to any other issues, feel free to open an issue.
