### ISSUE TITLE
should args act the role in culprit info to aggregate report ?

### ISSUE THREAD

**Issue by redink** [getsentry/sentry-elixir#213]
Hello,

When I using sentry dashboard, I met trouble about aggregating error report. In short, when I capture the exception (or message), different args will not aggregate together, just like:

```
> List.length 1
> List.length 2
> List.length 3
> List.length 4
```

these exception will not aggregate together but just like:

```
transaction List.length(1)
transaction List.length(2)
transaction List.length(3)
transaction List.length(4)
```

After scanned the source code, I noticed that

https://github.com/getsentry/sentry-elixir/blob/9cdfaac2465494aab31195d0705aa59fc7fbc866/lib/sentry/event.ex#L205

Culprit is made up of module, function and args. BUT, I need not to pay attention to the args here, and I will send the stacktrace information to the sentry dashboard.

So, any idea or advice ?

Thanks very much.

**Comment by redink** [comment]
@mitchellhenke ping ?

**Comment by mitchellhenke** [comment]
@redink yep, this is something I'll be working on next.  It's somewhat related to #210 as well.

**Comment by redink** [comment]
Thanks.
