### ISSUE TITLE
Support Confex for Configuration

### ISSUE THREAD

**Issue by jalcine** [getsentry/sentry-elixir#222]
Disclaimer: I'm new to using Elixir for production applications and attempting to follow best industry practice.

I've noticed that on Elixir Forum, people suggest using [Confex][] to handle the act of configuration loading (in tandem with tools like Distillery, exrm et al). I'm aiming to see if this is something y'all like to support implicitly? I'm happy to open a PR for this.

[confex]: https://hexdocs.pm/confex/readme.html

**Comment by jalcine** [comment]
This is blocked by #221 btw.

**Comment by mitchellhenke** [comment]
Sentry does support `{:system, "ENV_KEY"}` to load config from the environment at runtime.  I don't have the fullest understanding of Confex within the context of distillery, though I know it offers more flexibility for configuration beyond `{:system, "ENV_KEY"}`.

I'm somewhat wary of adding a dependency or managing an optional dependency, though I'm not entirely opposed.  I'd prefer to try and solve it within the Sentry library itself first.

Is there a specific part of Confex functionality you're looking to be able to use?

**Comment by jalcine** [comment]
> Is there a specific part of Confex functionality you're looking to be able to use?

Yeah, it allows you to specify the type of the value you're aiming to import. However, looking closer, this is something I can implement in my client application and not have to push this dependency upstream.

**Comment by jalcine** [comment]
Closing this out. For those in the future interested, doing `Confex.resolve_env!(:sentry)` will fix this issue I ran into.

**Comment by indrekj** [comment]
Just stumbled on this as well. Had everything defined like
```
environment_name: {:system, :string, "SENTRY_ENVIRONMENT", "dev"}
```
which failed. Later found out that
```
environment_name: {:string, "SENTRY_ENVIRONMENT"}
```
works just fine.
