### ISSUE TITLE
Add error dump in Mix test task

### ISSUE THREAD

**Issue by jalcine** [getsentry/sentry-elixir#226]
### Environment

* Elixir version (elixir -v): 1.5.2
* Erlang/OTP version (erl): 20
* Sentry version (mix deps): 6.0.3
* Operating system: Alpine Linux

### Description

When running `mix sentry.send_test_event`, it's possible for networking issues to occur. I've run into the case where sending a test event results in a failure. However, as shown [here][1], it isn't handled.

### Expected Behavior
A dump of the exception that was encountered; i.e: raw exception data, printed out to stdout.

### Actual Behavior
```elixir
** (CaseClauseError) no case clause matching: :error
    (sentry) lib/mix/tasks/sentry.send_test_event.ex:53: Mix.Tasks.Sentry.SendTestEvent.maybe_send_event/0
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2
```

### Steps to Reproduce
The easiest way would be to do the following:

- Disconnect from the Internet.
- From a minimal project, run `mix sentry.send_test_event`

[1]: https://github.com/getsentry/sentry-elixir/blob/master/lib/mix/tasks/sentry.send_test_event.ex#L53-L58

**Comment by mitchellhenke** [comment]
Thank you for the excellent bug report.  I will take a look at this!

**Comment by jalcine** [comment]
You're welcome! Your template helped a lot.
