### ISSUE TITLE
Dynamic configuration using environment variables

### ISSUE THREAD

**Issue by doughsay** [getsentry/sentry-elixir#227]
### Environment

* Elixir version (elixir -v): 1.5.2
* Erlang/OTP version (erl): Erlang/OTP 20 [erts-9.1.2]
* Sentry version (mix deps): 6.0.3
* Operating system: macOS / Alpine Linux

### Description

We have multiple dynamic testing and staging environments that don't map to mix envs.  We run these other environments using docker images built with mix env "prod".

Additionally, some of these environments are meant to report to sentry and some are not.  So we'd like to be able to completely control the sentry dsn and sentry env name, as well as wether or not sentry should even boot, using nothing but environment variables.

I can't seem to do this, because:

1.) using `dsn: {:system, "SENTRY_DSN"}` in my prod.exs config and either using empty string as the value or omitting the var altogether results in errors being thrown everytime an exception is caught:

```
     ** (FunctionClauseError) no function clause matching in URI.parse/1
         (elixir) lib/uri.ex:409: URI.parse(nil)
         (sentry) lib/sentry/client.ex:180: Sentry.Client.get_dsn!/0
```

or

```
     ** (FunctionClauseError) no function clause matching in String.split/3
         (elixir) lib/string.ex:366: String.split(nil, ":", [parts: 2])
         (sentry) lib/sentry/client.ex:181: Sentry.Client.get_dsn!/0
```

And:

2.) I can't (easily) dynamically set the `:included_environments` config variable using an environment variable, because it's an array and not a string. (only strings play nicely with the `:system` tuple method.  But because I'm using distillery for releases and use `REPLACE_OS_VARS=true`, I can set something like this, even though it looks a bit ugly: `included_environments: ["${SENTRY_ENV}"]`.

### Expected Behavior

There is a better way to control the behavior of sentry using only environment variables.

### Actual Behavior

Can't prevent sentry from throwing errors if `SENTRY_DSN` is not set or is empty.

### Steps to Reproduce

This is my exact sentry config in prod.exs:

```elixir
config :sentry,
  dsn: {:system, "SENTRY_DSN"},
  environment_name: {:system, "SENTRY_ENV"},
  included_environments: ["${SENTRY_ENV}"]
```

Setting `SENTRY_DSN` and `SENTRY_ENV` to valid values works great; omitting `SENTRY_DSN` causes problems...

**Comment by doughsay** [comment]
I've currently solved this problem using this workaround:

In my `application.ex` during boot, it dynamically sets the sentry config:

```elixir
with dsn when length(dsn) > 0 <- System.get_env("SENTRY_DSN"),
     env when length(env) > 0 <- System.get_env("SENTRY_ENV")
do
  Application.put_env(:sentry, :dsn, dsn)
  Application.put_env(:sentry, :release, release_version())
  Application.put_env(:sentry, :environment_name, env)
  Application.put_env(:sentry, :included_environments, [env])
end
```

**Comment by mitchellhenke** [comment]
Thanks for opening this!  It is an issue for the library to (try to) read an array from system env that will be a string or nil.  It should probably be comma-separated and split into a list or similar.  Would that help solve your issue?

My other question is around how dynamic the environments are.  Is it possible to have a more static set of `included_environments`, with `environment_name` being dynamic?

**Comment by doughsay** [comment]
Being able to set a comma separated string as the config variable would definitely solve my issue.

As for the dynamic nature of our environments, it certainly would be possible to hard-code a list of known environments (we don't create new ones that often), but I guarantee that the next time someone wants to create a new environment they're going to forget (or not know) that a code change needs to be made to include it in sentry reporting...

I think allowing a comma separated string to be a valid value for the `:included_environments` config key is a pretty good idea, but also, my above workaround is also working for me for now too.

Thanks!

**Comment by mitchellhenke** [comment]
@doughsay I've opened #234 to do that, if you would like to take a look.  Otherwise, it will be  available in the next release.
