### ISSUE TITLE
Sentry.capture_exception error

### ISSUE THREAD

**Issue by maxguzenski** [getsentry/sentry-elixir#233]
When I call Sentry.capture_exception inside a gen_stage consumer, I receive a error on logger.

```
[error] Web.NotificationConsumer #PID<0.1870.0> received unexpected message in handle_info/2: {#Reference<0.4095123269.3008888834.9990>,
 {:ok, "e97f44e65d6a43419da377826de87a2e"}}

[error] Web.NotificationConsumer #PID<0.1870.0> received unexpected message in handle_info/2: {:DOWN, #Reference<0.4095123269.3008888834.9990>, :process, #PID<0.1928.0>,
 :normal}
```

```elixir
defmodule Web.NotificationConsumer do
  use GenStage
  require Logger

  def start_link() do
    GenStage.start_link(__MODULE__, :ok)
  end

  def init(:ok) do
    {:consumer, [], subscribe_to: [{Web.NotificationProducer, max_demand: 100}]}
  end

  @doc """
  """
  def handle_events(events, _from, state) do
    Enum.each(events, fn event ->
      try do
        handle_event(event)
      rescue
        ex -> Sentry.capture_exception(ex, [stacktrace: System.stacktrace(), extra: %{}])
      end
    end)

    {:noreply, [], state}
  end

  #
  # ... more code
  #
end 
```

**Comment by mitchellhenke** [comment]
This is likely from the asynchronous request Tasks.  

https://hexdocs.pm/sentry/Sentry.Client.html#send_event/2-options has more information on the different strategies for sending events.

`Sentry.capture_exception(ex, [stacktrace: System.stacktrace(), extra: %{}, result: :none])`
`Sentry.capture_exception(ex, [stacktrace: System.stacktrace(), extra: %{}, result: :sync])`
`Sentry.capture_exception(ex, [stacktrace: System.stacktrace(), extra: %{}, result: :async])`

are the options, with `:async` being the default.

Does that help?

**Comment by mitchellhenke** [comment]
If there's more I can do to help, please let me know, but I'll be closing this for now.
