### ISSUE TITLE
 Unable to encode Sentry error - {:invalid, {nil, "users"}}

### ISSUE THREAD

**Issue by prem-prakash** [getsentry/sentry-elixir#240]
### Environment

* Elixir version (elixir -v): 1.5.3
* Erlang/OTP version (erl): 20.1
* Sentry version (mix deps): 6.0.5
* Operating system:

### Description
Error when sending tuple error

Unable to encode Sentry error - {:invalid, {nil, "users"}}

### Expected Behavior
Encode tuple properly and send error to sentry

### Actual Behavior
Can't encode tuple error so does not send error to sentry

### Steps to Reproduce
Send a tuple as an error

**Comment by mitchellhenke** [comment]
Can you give a short example? A tuple isn't encodable as JSON, but it should be handled in most cases.

**Comment by sheharyarn** [comment]
Encountering the same issue. It looks like Sentry completely relies on the `Jason` library for encoding params, which by default can't encode tuples.

<img width="1384" alt="Screen Shot 2019-04-10 at 4 12 23 PM" src="https://user-images.githubusercontent.com/2355108/55919646-a78bc100-5bab-11e9-888d-8b071cf0aa97.png">


```
Unable to encode Sentry error - %Protocol.UndefinedError{description: "Jason.Encoder protocol must always be explicitly implemented", protocol: Jason.Encoder, value: {:DOWN, #Reference<0.1321247442.30408705.69669>, :process, #PID<0.11679.690>, :normal}}
```

I would've expected Sentry to automatically take care of this, as it turns out a large number of errors were never sent to sentry and we didn't find out.

For now we are just going to implement the `Jason.Encoder` protocol manually for tuples.

**Comment by mitchellhenke** [comment]
@sheharyarn thanks for adding more context to this issue 🙂 

I understand the expectation that these cases should be handled automatically (and that's always the goal), but unfortunately it is more complicated than implementing the `Jason.Encoder` protocol within Sentry for other types.  Different users of Sentry may have their own preferred encoding of tuples, structs, or other types, and implementing them within Sentry may conflict with that, or be cause for surprise within someone else's expectations.

There is potential for improvement as far as notifying when Sentry has failed for whichever reason, but I've held off.  The relative risks around ending up in an infinite loop of the failure repeating being the chief reason, but I also have concerns around noise and generating a helpful event that leads to solving the root problem.

For me, it would be helpful to see how Sentry reaches the point of trying to encode an unencodable value.  Is it happening via [Sentry.Plug](https://hexdocs.pm/sentry/Sentry.Plug.html), [Sentry.LoggerBackend](https://hexdocs.pm/sentry/Sentry.LoggerBackend.html), event metadata, or something else?

**Comment by sheharyarn** [comment]
Hey @mitchellhenke. Thanks for the quick reply. We're using all three but most of the time we pass error tuples and other structs as part of the metadata when manually sending an event via `Sentry.capture_message/2`:

```elixir
with {:ok, result} <- do_something() do
  result
else
  {:error, error} ->
    Sentry.capture_message("[error] Something failed", %{error: error})
    {:error, error}
end
```

**Comment by mitchellhenke** [comment]
In cases like that where it's a term of any type, it's difficult for Sentry to accommodate for the reasons mentioned above.  `error` could be just about anything, e.g. an anonymous function, which can't be encoded.

If the structure of the term isn't important, passing`%{error: inspect(error)}` is an option, as a binary should always be accepted.

**Comment by mitchellhenke** [comment]
@sheharyarn due to the way protocols get dispatched, I don't think including `Jason.Encoder` protocol implementations can fit within Sentry.

I unfortunately am a bit stumped on how else to make this more ergonomic on your end, because ideally these cases are more obvious ahead of time or there's a better way to handle it when it does happen.

**Comment by sheharyarn** [comment]
Hey @mitchellhenke, thanks for the update. For now, we've started calling `inspect` on the passed attributes in our custom logger/sentry wrapper so sentry captures all events, but lost the ability to expand/collapse maps in the sentry dashboard (which is not that big of an issue).

Another solution we're looking at is recursively walking the error metadata map and converting all present tuples to lists and structs to regular maps before passing it to the `capture_message` method.

**Comment by mitchellhenke** [comment]
To wrap this up, I think the best solution is to lean on Jason (or whichever JSON lib), and direct users to implement protocols for values that can't be by default or use `inspect()`.

#372 returns more information in the form of why sending an event failed, including JSON encoding failures, to help diagnose these issues.
