### ISSUE TITLE
Documentation for Source Compiling is Incorrect

### ISSUE THREAD

**Issue by jeremyjh** [getsentry/sentry-elixir#241]
### Environment

* Elixir version (elixir -v): 1.4.5
* Erlang/OTP version (erl): 20.1
* Sentry version (mix deps): 6.0.0
* Operating system: Mac OSX

### Description
In order to include updated source code in Sentry reports, Sentry itself must be recompiled. The documentation says this, but provides incorrect information about how to do so. Rather than run `mix do clean, compile` which only rebuilds the application using Sentry, the sentry dep needs to be recompiled e.g. `mix deps.clean sentry && mix do deps.get compile`

### Expected Behavior
Documentation tells us how to use the feature.

### Actual Behavior
Documentation is wrong.

### Steps to Reproduce
https://docs.sentry.io/clients/elixir/#including-source-code

**Comment by mitchellhenke** [comment]
Thanks for opening this! I've opened #242 to fix this issue 🙂
