### ISSUE TITLE
Exceptions in spawned processes by "spawn" are not logged.

### ISSUE THREAD

**Issue by psagan** [getsentry/sentry-elixir#250]
### Environment

* Elixir version (elixir -v): 1.6.0
* Erlang/OTP version (erl): Erlang/OTP 20 [erts-9.2]
* Sentry version (mix deps): 6.0.5
* Operating system: macOS High Sierra 10.13.3

### Description
In Elixir app:

`spawn(fn -> raise "Test 1" end)` <-- this one is not logged  to sentry
`Task.start(fn -> raise "Test 2" end)` <-- this one is logged properly to sentry

### Steps to Reproduce
example in Phoenix controller action (but in raw elixir app it's the same):
```
def index(conn, _) do
  spawn(fn -> raise "Test 1" end) # :(
  Task.start(fn -> raise "Test 2" end) # :) 
end
```

**Comment by mitchellhenke** [comment]
Hey, thanks for opening this issue! 💖 ❤️ 

I've got it tracked down, and will put together a PR to patch it sometime this week. I'll likely also release a new version.
