### ISSUE TITLE
Is there a way to scrub cookies?

### ISSUE THREAD

**Issue by atomkirk** [getsentry/sentry-elixir#253]
I store the auth token in a cookie, would be nice to scrub those

**Comment by mitchellhenke** [comment]
Hi! There isn't an easy way currently. Would configuration to enable/disable sending cookies be sufficient, or would more fine-grained control over specific cookie keys be most helpful?

**Comment by atomkirk** [comment]
I would say everything helps with debugging so a callback like `default_cookie_scrubber` would be most helpful…
