### ISSUE TITLE
Database Fingerprinting

### ISSUE THREAD

**Issue by novaugust** [getsentry/sentry-elixir#256]
I'd like to collaborate on ideas for making fingerprinting more feasible for applications using the sentry error logger.

We recently upped our stack trace depth to 20 in production to help us dig up exactly where some of our DBConnection errors were coming from. While great for helping us find problem areas in code, it created a new problem: all our DBConnectionErrors are no longer being aggregated by Sentry since their stacktrace differs at the thirteen or whatever lines up. According to Sentry documentation, the solution to this is Fingerprint. In fact, the documentation specifically calls out using fingerprinting with DBErrors.

> A generic error, such as a database connection error, has many different stacktraces and never groups together.

As-is though, the only current way to fingerprint errors in sentry-elixir is to capture the exception yourself and pass the fingerprint there, or set the context for the error before it happens. Obviously the first solution doesn't work with SentryErrorLogger where the user is not the one raising the error, and the second solution doesn't work as it's not possible to fingerprint a db error beforehand, as any number of errors could happen deep in the bowels of ecto before that particular one goes off.

So, I'm curious what we might be able to do to customize fingerprinting after-the-fact. 

### Drawing from ErrorFiltering solution

The customizable error filtering already in this project could stand as inspiration for fingerprinting.
The tricky part would be conveying to users to fallback to the arbitrary `{{default}}` argument.

```elixir
# sentry_event_filter.ex
defmodule MyApp.SentryFingerprinter do
  @behaviour Sentry.Fingerprinter

  def fingerprint(%Ecto.DBConnectionError{}), do: ["db_connection_error"]
  def fingerprint(_exception), do: ["{{ default }}" ]
end

# config.exs
config :sentry, filter: MyApp.SentryFingerprinter,
  included_environments: ~w(production staging),
  environment_name: System.get_env("RELEASE_LEVEL") || "development"
```

### Protocol

Another solution (and, at first glance, perhaps a better one) would be to define a protocol for fingerprinting.

```elixir
defimpl Sentry.Fingerprint, for: Ecto.DBConnectionError do
  def fingerprint(%Ecto.DBConnectionError{}), do: ["ecto", "db_connection", "timeout"]
end
```

That way, the default/fallback implementation of `{{ default }}` could exist within this project, excusing users from having to know that little bit of magic.

Further, via `Code.ensure_loaded?(Ecto)` this repo could even implement useful defaults for a few common community packages if that seemed like a good idea. If not, a standalone repo could offer something similar.

-----------------------------------

Anyhoo. Would love to get feedback on these ideas and potentially get something functional in here!

**Comment by mitchellhenke** [comment]
hey @novaugust, thanks for opening this issue! I really appreciate the comprehensive explanation of the problem and use case.

Is this something that can be solved via the [before_send_event](https://hexdocs.pm/sentry/Sentry.Client.html#module-configuration) configuration? My thought is something along the lines of:

```elixir
      before_send_event: fn e ->
        case e do
          %Sentry.Event{exception: [%{type: DBConnection.ConnectionError}]} ->
            %{e | fingerprint: ["ecto", "db_connection", "timeout]}
          _ ->
            e
        end
```

If that does work, do you think if I implemented it under a module of things users can make use of or reference that it would be sufficient?

example (excuse the naming for now):
```elixir
before_send_event: {Sentry.BeforeSendEvent, DBConnectionErrorFingerprint}
```

I think the Protocol is good, but we've got a (maybe overwhelming) number of configuration options already.

**Comment by novaugust** [comment]
oh-ho, yeah, don't see why `before_send_event` wouldn't work. thanks!

------------------------------------------------

>If that does work, do you think if I implemented it under a module of things users can make use of or reference that it would be sufficient?

Little unclear what you mean, sorry.

>I think the Protocol is good, but we've got a (maybe overwhelming) number of configuration options already.

The protocol would work without adding config options - or maybe you're saying you like protocol more because it doesn't config, in which case, I agree

**Comment by mitchellhenke** [comment]
My initial thought was to have a module like:

```elixir
defmodule Sentry.BeforeSendEvent do
  def db_connection_error_fingerprint(event) do
    case event do
      %Sentry.Event{exception: [%{type: DBConnection.ConnectionError}]} = event ->
        %{event | fingerprint: ["ecto", "db_connection", "timeout"]}
      _ ->
        e
    end
  end

# def some_other_common_before_send_event_use_case(event) do
end
```

and in config users could make use of them as:

```elixir
config :sentry, before_send_event: {Sentry.BeforeSendEvent, :db_connection_error_timeout}
```

I have not done much around fingerprinting in my use of Sentry and I'm not sure which things are commonly fingerprinted, so I'm leaning towards adding the above as an example in the docs. My hunch is that most implementations would also be very similar in that they'd have a different exception type?

Do you think adding something like above in the docs would be sufficiently helpful?

On the protocol, I misunderstood initially, so my comments on it can be disregarded 🙂

**Comment by novaugust** [comment]
Since there are a few places that :sentry can be configured to call into a module, i'm just doing this

```
config :sentry,
  filter: Relay.Sentry,
  before_send_event: {Relay.Sentry, :before_send}

defmodule Relay.Sentry do
  @moduledoc """
  Implements callbacks for customizing our :sentry dep's behaviour.
  """
  @behaviour Sentry.EventFilter

  alias Ecto.Query.CastError, as: QueryCastError

  alias Phoenix.{
    NotAcceptableError,
    Router.NoRouteError,
  }

  @doc """
  Last chance to modify an event before it's sent to Sentry.
  We're fingerprint DB errors so that timeouts don't get their own sentry report
  just because they stack varies at the 15th depth.
  """
  def before_send(%{exception: [%{type: DBConnection.ConnectionError}]} = event) do
    %{event | fingerprint: ["ecto", "db_connection", "timeout"]}
  end
  def before_send(event) do
    event
  end

  @doc """
  Filter errors from being reported to sentry.

  See https://hexdocs.pm/sentry/Sentry.html#module-filtering-exceptions
  """
  def exclude_exception?(%NoRouteError{}, _), do: true
  def exclude_exception?(%NotAcceptableError{}, _), do: true
  def exclude_exception?(%QueryCastError{value: "undefined", type: :id}, _), do: true
  def exclude_exception?(_exception, _source), do: false
end
```

that's not production code re: before_send since i haven't gone and looked up exactly what error i'm trying to fingerprint yet but, you get the idea ;)

**Comment by mitchellhenke** [comment]
That is how I envision more customized uses of Sentry, makes a lot of sense to have a module I think 🙂 

I've created an issue related to discussion above on documentation: #257
