### ISSUE TITLE
[Question] Add Sentry logging to extra applications

### ISSUE THREAD

**Issue by mbaeuerle** [getsentry/sentry-elixir#258]
Is there a way to add Sentry logging to any extra application the main application requires? So if an error in the other application arises Sentry is also logging this error even if it's an external library without access to the source.

**Comment by mitchellhenke** [comment]
Hey @mbaeuerle, thanks for opening an issue!

Via [Sentry.Logger](https://hexdocs.pm/sentry/Sentry.Logger.html), a crashed process should generate an event in Sentry.

Can you expand on the problem with an example?

**Comment by mbaeuerle** [comment]
Sorry I had the misconception that Sentry also logs errors wich were written with `Logger.error`. But It does not, so this question is irrelevant.

**Comment by mitchellhenke** [comment]
If it helps, https://hex.pm/packages/sentry_logger_backend and https://github.com/simonwoolf/sentry-logger-backend aim to do that 🙂

**Comment by mbaeuerle** [comment]
Thanks! That looks very promising!
