### ISSUE TITLE
Doesn't work with the new DSN format

### ISSUE THREAD

**Issue by relip** [getsentry/sentry-elixir#265]
### Environment

* Elixir version (elixir -v): 1.6.4
* Erlang/OTP version (erl): 20
* Sentry version (mix deps): 6.2.0
* Operating system: CentOS 7

### Description
When I set DSN to the one appears in the install instruction, it refuses to send an event. After changing it to the legacy DSN then it works.

### Expected Behavior
Works with the new DSN format

### Actual Behavior
```
[warn] Failed to send Sentry event.
Cannot send event because of invalid DSN
```

### Steps to Reproduce
- Set DSN to the one appears in the install instruction
- Throw an error

**Comment by mitchellhenke** [comment]
Oops, yep, this is my bad. I should have made a release when I updated the README. I will do that today!

**Comment by mitchellhenke** [comment]
I've pushed 6.2.1 to hex, so it should be good now if you update! Sorry again!
