### ISSUE TITLE
Request body not sent to Sentry?

### ISSUE THREAD

**Issue by ndac-todoroki** [getsentry/sentry-elixir#267]
### Environment

* Elixir version (elixir -v): Elixir 1.6.1 (compiled with OTP 20)
* Sentry version (mix deps): * sentry 6.2.0 (https://github.com/getsentry/sentry-elixir) (mix)
* Operating system: Ubuntu 16.04

### Description

When you use this by `use Sentry.Plug`, the `%Event{}` struct includes the request body with the key `request`, but when the error shows up in Sentry the request body is gone.

### Expected Behavior

The request body will show up in the console.

### Actual Behavior

It does not.

### Steps to Reproduce

1. Create a Cowboy application
1. do `use Sentry.Plug`
1. call `super(conn, error)` inside `handle_error`
1. make some crash

---

I went reading the documents a little, and there seems to be no _request_interface_ in the [docs](https://docs.sentry.io/clientdev/interfaces/). Maybe the interface changed?

**Comment by mitchellhenke** [comment]
@ndac-todoroki can you gist the code around using Sentry and sending errors?

I've just tried to duplicate it myself and am getting errors with the request body showing up:
![image](https://user-images.githubusercontent.com/1430443/40667542-0e693d80-6328-11e8-98d2-5ba14ec22f83.png)

**Comment by mitchellhenke** [comment]
Going to close this for now, but would be more than happy to look into it further with some more details around Sentry config and setup for the project that's having issues.
