### ISSUE TITLE
Umbrella project errors reporting to a single Sentry project

### ISSUE THREAD

**Issue by carlodicelico** [getsentry/sentry-elixir#268]
### Environment

* Elixir version (elixir -v): Elixir 1.6.4 (compiled with OTP 19)

* Erlang/OTP version (erl): Erlang/OTP 19 [erts-8.3.5.4] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

* Sentry version (mix deps): 6.2.1

* Operating system: FreeBSD 11.1-RELEASE-p9

### Description

I’m running an Elixir umbrella application made up of two Phoenix applications (web app and API) and a core application (business rules and data access). Each has its own config, since they are self-contained and can be deployed separately.

I have each configured with its own client DSN just the way it is described in the Sentry docs. My thinking was that I would set up one project in Sentry for each app in the umbrella. However, all errors appeared in a single project, the web project. I’m not sure why all errors show up in one project, or why the web project instead of any other one.

### Expected Behavior

Each application in the umbrella should report to its own project in Sentry if that application has its own config.

### Actual Behavior

All of the applications are reporting their errors to a single project, the web application's project, in Sentry.

### Steps to Reproduce

- Create an Elixir Umbrella application in the usual way that contains a Phoenix JSON API, a Phoenix admin web application, and the core application. 

- Configure Sentry as shown in this gist: https://gist.github.com/carlodicelico/32959363621c778c0cf88ead6e461019.

- Set up your projects in Sentry, one for each app, using the Client DSN provided on the project's settings page.

- When you trigger an error in *any* of the apps, you should see the errors all appear in one project in Sentry instead of each one appearing in its proper project.

**Comment by carlodicelico** [comment]
Added a tag to the config for each app to show which app the error is coming from in Sentry:

```elixir
config :sentry, dsn: "https://app_public_key@sentry.io/project_id",
   included_environments: [:prod, :staging],
   environment_name: Mix.env(),
   enable_source_code_context: true,
   tags: %{
     application: "MyApp"
   }
```

When I send a test event with `mix sentry.send_test_event`, the tag for `MyAppWeb` appears in Sentry regardless where the test event was sent from.

**Comment by carlodicelico** [comment]
Okay, I have some stuff to share. Turns out, this is not an issue with the Sentry library at all, but a side effect of how umbrella applications work in relation to Mix configs!

In the umbrella root's `config.exs`, the line `import_config "../apps/*/config/config.exs"` imports all of the config files in `/apps`, and since the web application's directory is *last*, its config overrides any previously imported configs. This explains why the web application's config is the one that is used. It's also not possible to have different logging configurations for Sentry because a) all of the OTP applications run on the same VM, and b) the Sentry library runs as a single application, not as one instance per application in the umbrella. All of this is super clear in hindsight, but wasn't at the time 😆

Thanks to @benwilson512, @DavidAntaramian, and @mitchellhenke for talking through all of that w/me on Slack!

Ultimately, as a workaround, what I ended up doing is using `before_send_event()` to inspect the stack frame, determine the correct Sentry project to send the error to, and set the DSN accordingly. This is probably a terrible idea for some reason I'm not thinking of at the moment, but it works quite well, and I'll share it here in case someone else wants share in my folly and send individual applications' errors to specific Sentry projects from within an umbrella application.

In my umbrella's root `config/config.exs`, I have my Sentry config set up in this way (comments added here to explain):

```elixir
config :sentry,
  dsn: "", # I wanted to fail loudly if this didn't get set
  included_environments: [:prod, :staging],
  environment_name: Mix.env(),
  enable_source_code_context: true,
  in_app_module_whitelist: [MyApp, MyAppApi, MyAppWeb],
  root_source_code_path: File.cwd!() <> "/apps", # We're in the umbrella root here
  source_code_exclude_patterns: [
    ~r"/priv/",
    ~r"/test/",
    ~r"/config/",
    ~r"/assets/"
  ],
  before_send_event: fn event ->
    # Here, I try to grab the module that's causing all the ruckus for tagging
    module =
      # See notes below about why I'm looking at the stacktrace frames
      event.stacktrace.frames
      # MyApp, MyAppApi, and MyAppWeb
      |> Enum.filter(&String.starts_with?(&1.function, "MyApp"))
      # I want the deepest event in the stack I can find
      |> List.last()
      # get the value of the function key (MyApp.MyModule.some_func/2)
      |> Map.fetch!(:function)
      |> String.split(".") 
      # don't need the function name
      |> List.delete_at(-1)
      |> Enum.join(".")

    # The application, so I can send the event to the correct Sentry project
    application =
      module
      |> String.split(".")
      |> List.first()

    # What's the right project DSN for the application?
    application_dsn =
      case application do
        "MyApp" ->
          "https://public_key_1@sentry.io/project_id_1"

        "MyAppApi" ->
          "https://public_key_2@sentry.io/project_id_2"

        "MyAppWeb" ->
          "https://public_key_3@sentry.io/project_id_3"

       # use the "core" app's project DSN by default
        _ ->
          "https://public_key_1@sentry.io/project_id_1"
      end

    # Change the Sentry application's :dsn configuration value, setting the DSN!
    Application.put_env(:sentry, :dsn, application_dsn)

    metadata = Map.new(Logger.metadata())

    tags = %{
      application: application,
      module: module
    }

    %{
      event
      | extra: Map.merge(event.extra, metadata),
        tags: Map.merge(event.tags, tags)
    }
  end
```

Why the stacktrace frames? Because it seems like the most reliable way to determine where exactly in the umbrella the error is coming from. Using culprit won't work because it could be a library (like Ecto), and I wouldn't want to use information in the exception or message because those aren't reliable (I might change them at any time). The stacktrace has the information I need here, so I use that.

Anyway, I'm sure this is not ideal or possibly even a good idea, and it's doing kind of a lot of processing of data on every single error event, which I'm not thrilled about, but but for now, it *does* work exactly as I'd like.

**Comment by mitchellhenke** [comment]
@carlodicelico thanks for the detailed explanation. 😀 The `Application.put_env` may cause some issues since it's global though.

**Comment by carlodicelico** [comment]
That's true, it _is_ global, but it's being set every time an event is sent, so _maybe_ it's okay in this case? 🤔
