### ISSUE TITLE
Mix edeliver build release fails on Sentry. eheap_alloc: Cannot allocate 529782288 bytes of memory (of type "old_heap").

### ISSUE THREAD

**Issue by jakobdamjensen** [getsentry/sentry-elixir#269]
Sorry for bothering you with this. I'm sure it's not really Sentry causing this but since Sentry seems to be the last step `mix edeliver` is able to reach I filed it here. I can't figure out how to debug this. I was able to build the release once but no more.

### Environment

* Elixir version (elixir -v): 1.6.4
* Erlang/OTP version (erl):
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

* Sentry version (mix deps): 6.1.0
* Operating system: Ubuntu 16.04.2

### Description

When doing `mix edeliver build release` it fails when compiling sentry. I've tried updating to the latest version, but it did not solve the problem. I've looked at stats for the server while building but it does not at all reach memory limit of the system.

### Expected Behavior
It should build the release

### Actual Behavior
It fails with the following error
```
==> sentry
Compiling 12 files (.ex)
eheap_alloc: Cannot allocate 529782288 bytes of memory (of type "old_heap").

Crash dump is being written to: erl_crash.dump...done
```

Here is the log:
[erl_crash.dump.zip](https://github.com/getsentry/sentry-elixir/files/2063157/erl_crash.dump.zip)

**Comment by mitchellhenke** [comment]
Thanks for opening this!

Does the same thing happen if you remove Sentry as a dependency?

**Comment by jakobdamjensen** [comment]
> Does the same thing happen if you remove Sentry as a dependency?

Nope. If I remove Sentry it builds just fine.

**Comment by mitchellhenke** [comment]
@jakobdamjensen can you gist your Sentry config?

**Comment by jakobdamjensen** [comment]
@mitchellhenke  sure:

https://gist.github.com/jakobdamjensen/ed9eb84c709fdab7bced0ecf78cbf18c

**Comment by mitchellhenke** [comment]
ah, my initial hunch is it may be an issue similar to https://github.com/getsentry/sentry-elixir/issues/168 with `root_source_code_path` and `source_code_path_pattern` (which default to the `**/*` glob). If you remove `root_source_code_path`, does it finish compilation?

If that is the issue, you'll have to set `root_source_code_path` to be something more specific like `/home/applications/myapp` to avoid the problematic file/directory recursion. This is still a case I don't have a good intuition on solving during compilation.

**Comment by mitchellhenke** [comment]
@jakobdamjensen sorry, my mistake.  Could you try `enable_source_code_context: false`?

**Comment by mitchellhenke** [comment]
@jakobdamjensen have you been able to give the above a try?

**Comment by fschuindt** [comment]
@mitchellhenke Hey, I ran into this same issue. Indeed `enable_source_code_context: false` allowed me to compile. But I'm now getting this warning:

```
One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :parse_trans
```

I don't know if it's related or not.

**Comment by fschuindt** [comment]
**Update:** Apparently adding `parse_trans: :load` to my `rel/config.exs` like so:
```elixir
release :amethyst do
  set version: "0.1.0"
  set applications: [
    :runtime_tools,
    database: :permanent,
    teller: :permanent,
    parse_trans: :load
  ]

  set commands: [
    "migrate": "rel/commands/migrate.sh"
  ]
end
```

Worked for me.

**Comment by mitchellhenke** [comment]
@fschuindt I wouldn't suspect the `:parse_trans` warning would be from Sentry, but I'd be happy to look into a fix if that is the case.

The culprit of `enable_source_code_context` is the reading of files recursively from the file system, and something like the issue mentioned above causing it to loop forever. The fix is to compile in a child directory or have stricter file path reading that avoids `**` globbing so it doesn't do anything recursively.

**Comment by fschuindt** [comment]
@mitchellhenke I see, I can do that. But what setting `enable_source_code_context` to `false` does? Is  any form of linting that setting it to `false` my project will lack?

**Comment by mitchellhenke** [comment]
@fschuindt source code context allows Sentry to display the text of the code when an error is reported.

If it's enabled, you'll see the code itself:
![image](https://user-images.githubusercontent.com/1430443/41731260-920cb388-7543-11e8-8f0a-feaffd431967.png)

If it's disabled, you'll instead only see the file and line number:
![image](https://user-images.githubusercontent.com/1430443/41731295-a2076ca6-7543-11e8-9ea7-d3f9c957c0a1.png)

**Comment by fschuindt** [comment]
@mitchellhenke Oh, ok. Got it. I will compile it in a separated directory with `enable_source_code_context` to `true`. It should work. Thank you so much.

I will keep you posted.
