### ISSUE TITLE
Warnings flood console when there is a connection problem

### ISSUE THREAD

**Issue by sega-yarkin** [getsentry/sentry-elixir#271]
### Environment

* Elixir version (elixir -v):
  `Elixir 1.6.5 (compiled with OTP 20)`
* Erlang/OTP version (erl):
  `Erlang/OTP 20`
* Sentry version (mix deps):
  `sentry 6.2.1`
* Operating system:
  `macOS 10.13.3`

### Description
When there is a problem with connection to Sentry servers, the client prints a lot of warnings in console with request data, even if it will retry in a couple of seconds.

### Expected Behavior
See the warnings after all retries failed with small message (without full HTTP request body). 

### Actual Behavior
Warning message per each failed retry.

### Steps to Reproduce
1) Set DSN with no valid endpoint host (e.g. `127.0.0.1`).
2) Call `Sentry.capture_exception` to send data.

### Other questions
1) As Sentry can do HTTP request in a separate erlang process (default behavior), can data be prepared in this process and do not block caller process?
2) Can data from failed requests be aggregated and sent in one HTTP request?
3) When the last retry failed, `try_request` still is doing sleep before return `:error`, can last sleep be avoided?

Thanks!

**Comment by mitchellhenke** [comment]
Thanks for the detailed issue!

I will look into the logging.

re: questions

1. Which data do you mean?
2. This is a possibility and something I've considered, but runs the risk of not sending events in the event the whole tree comes down before sending the aggregated events. It doesn't look like Sentry supports it via the API, so it would likely end up being individual requests (https://github.com/getsentry/sentry/issues/873)
3. Good catch. I would think so.

**Comment by sega-yarkin** [comment]
1. Every data (parameters) starts from `Sentry.capture_exception` gets exception data, data from current context, and decides to send it to Sentry, to actual sending data via Hackney (e.g. transform maps, encode it as JSON). For example, `Poison.encode()` returns `iodata` by default which is good with I/O functions, but isn't that good to send to another process (compare to binary/string), because there are many of small chunks (small binaries) and erlang will copy them instead of pass by reference.
2. Oh, I see, thanks!

**Comment by sega-yarkin** [comment]
I don't know if seeing a full HTTP request body is useful, I don't have much experience. But if data is sent to Sentry servers at the end, maybe we don't need to see it in a console at all? I think we will have exceptions in console already from error_logger. But is it possible to make an option to disable dumping full request in a console? It will be more useful if developer can choose :-) Thanks!

**Comment by mitchellhenke** [comment]
@sega-yarkin there's unfortunately no guarantee that the data gets sent to Sentry servers at the end, and logging any issues that failed to send immediately is something I think should stay for now. Exceptions received through error_logger would be logged with a default configuration, but exceptions sent through other means would not.

It would be possible to control this via config, but I am wary as the number of configuration options can be quite overwhelming as is, so I'm not sure how to best balance that with control over log noise. It could also be solved by raising your log level to `:error`, though this has implications across other sources of logs in your application.
