### ISSUE TITLE
Documentation for adding Sentry.Logger in multiple applications needs to be updated

### ISSUE THREAD

**Issue by stevedomin** [getsentry/sentry-elixir#276]
### Environment

* Elixir version (elixir -v): 1.6.6
* Erlang/OTP version (erl): 21.0
* Sentry version (mix deps): 6.2.1
* Operating system: macOS

### Description

The [documentation](https://hexdocs.pm/sentry/Sentry.Logger.html ) to add `Sentry.Logger` only once does not work with Erlang 21.0 anymore.

### Expected Behavior

Application should start normally (without crash) and `Sentry.Logger` should be added once to the list of error logger backends.

### Actual Behavior

The application crashes on start, because of this line:

```elixir
iex(1)> Sentry.Logger in :gen_event.which_handlers(:error_logger)
** (exit) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib) gen.erl:228: :gen.do_for_proc/2
    (stdlib) gen_event.erl:239: :gen_event.rpc/2
```

### Steps to Reproduce

Add this code to one of your `application.ex` in an umbrella application:

```elixir
if !(Sentry.Logger in :gen_event.which_handlers(:error_logger)) do
  :ok = :error_logger.add_report_handler(Sentry.Logger)
end
```

**Comment by mitchellhenke** [comment]
@stevedomin thanks for opening this! I will correct the docs 🙂

**Comment by mitchellhenke** [comment]
updated documentation on the 6.x branch in https://github.com/getsentry/sentry-elixir/commit/f482840257af91808b04b2a2b956a7a3cfe20af9
