### ISSUE TITLE
Plug.Phoenix.Endpoint should PROBABLY offer same options for scrubbing

### ISSUE THREAD

**Issue by jeregrine** [getsentry/sentry-elixir#279]
The Plug.Phoenix.Endpoint does not scrub things like the plug does.

**Comment by Ebtoulson** [comment]
The sentry plug also filters out exceptions like `Phoenix.Router.NoRouteError`.
If you have both the plug and endpoint, 404's will still result in a sentry event.

**Comment by mitchellhenke** [comment]
Handled by combining the functionality of `Sentry.Plug` and `Sentry.Phoenix.Endpoint` in #402
