### ISSUE TITLE
Consuming exception

### ISSUE THREAD

**Issue by LucioFranco** [getsentry/sentry-elixir#283]
### Environment

* Elixir version (elixir -v): 1.6.6
* Erlang/OTP version (erl): 21
* Sentry version (mix deps): 3.3
* Operating system: MacOS 10.13.5

### Description
Sentry is consuming the exception when it tries and reports it and instead just produces this exception `** (UndefinedFunctionError) function Plug.Conn.get_peer_data/1 is undefined or private`. It should output the actual exception, I believe this is a bug with 3.3 and the new use of `get_peer_data/1`. Let me know if there is any other info you need.

**Comment by mitchellhenke** [comment]
@LucioFranco what version of Plug are you on?

**Comment by LucioFranco** [comment]
@mitchellhenke `1.4`

**Comment by mitchellhenke** [comment]
@LucioFranco are you overriding the Plug version? Version `6.3.0` has it locked to using Plug `~> 1.6`

https://github.com/getsentry/sentry-elixir/blob/6.3.0/mix.exs#L30

**Comment by LucioFranco** [comment]
@mitchellhenke Right I see that now. We can't upgrade to `Plug 1.6` at the moment so we'll stay with `6.2.1`. Thanks.

**Comment by mitchellhenke** [comment]
@LucioFranco cool, thank you! Let me know if there is anything I can do to make it easier :)
