### ISSUE TITLE
Advice about Task.start errors

### ISSUE THREAD

**Issue by atomkirk** [getsentry/sentry-elixir#284]
Do you have any advice about getting better error messages from `Task.start`? For example:

```
exit: ** (exit) %HTTPoison.Error{id: nil, reason: :timeout}
  File "lib/httpoison.ex", line 66, in HTTPoison.request!/5
  File "lib/task/supervised.ex", line 88, in Task.Supervised.do_apply/2
  File "proc_lib.erl", line 247, in :proc_lib.init_p_do_apply/3
  Module "Elixir.Task", in anonymous fn/0 in Task.start/1
```

Maybe there is context that I can add before calling `Task.start` to give myself a hint as to where `Task.start` is called and thus the function this error happened in? Thanks!

**Comment by mitchellhenke** [comment]
@atomkirk unfortunately when relying upon `Sentry.Logger` to report errors, you're pretty limited in contextual information as it can only use what `error_logger` provides it.

One option would be to wrap it in a try/rescue, and include any contextual information you need by reporting it manually:

```

**Comment by atomkirk** [comment]
What about this?
```
Sentry.Context.set_extra_context(%{})
Task.start(fn ->
  
end)
```

**Comment by atomkirk** [comment]
ok thanks!

**Comment by atomkirk** [comment]
also, we've got somethign like this. Do you see any problems with it?

```
defmodule Utils.Task do

  @doc "Works just like Task.start but runs in-line during tests"
  if Application.get_env(:zipbooks, :env) == :test do
    def start(func), do: func.()
  else
    def start(func) do
      # copies the sentry context into the new process
      context = Process.get(:sentry_context)
      Task.start(fn ->
        if context, do: Process.put(:sentry_context, context)
        func.()
      end)
    end
  end

end
```

**Comment by mitchellhenke** [comment]
@atomkirk from looking at it, I suspect that it won't work.

I don't think the process dictionary state gets passed between the error reporting processes in Erlang, and so despite the Task having that information, I don't think it will propagate it to `error_logger`, which `Sentry.Logger` uses to generate reports.

**Comment by atomkirk** [comment]
don't you read `:sentry_context` thought in the error handler you use to send data to sentry?

**Comment by mitchellhenke** [comment]
It makes a best effort to get as much information from`error_logger`, but it isn't something that can be relied upon unfortunately.

**Comment by mitchellhenke** [comment]
I should add that this could be changing dramatically with the coming OTP/Elixir Logger changes
