### ISSUE TITLE
Ability to disable logging for failed events

### ISSUE THREAD

**Issue by binarylogic** [getsentry/sentry-elixir#304]
When the sentry rate limit is exceeded it [logs an event](https://github.com/getsentry/sentry-elixir/blob/8c216dc6ce20865030977e40a398ab88bc495c36/lib/sentry/client.ex#L334) that looks like:

```
Failed to send Sentry event. {...}
```

These events are incredibly noisy and they swallow the actual error from being logged. Would it be possible to provide a configuration option to disable this or drop the level to `debug`?

Thanks.

**Comment by mitchellhenke** [comment]
@binarylogic thanks for opening an issue!  This is something that's been suggested before (#271).

Would allowing configuration of the log level be sufficient?

**Comment by binarylogic** [comment]
Hey @mitchellhenke, apologies I just saw this. Yes, that would be very helpful, I'd prefer to set it at the `debug` level.
