### ISSUE TITLE
Issues are not catched 

### ISSUE THREAD

**Issue by Nrisimha** [getsentry/sentry-elixir#307]
### Environment

* Elixir version (elixir -v): Elixir 1.6.6 (compiled with OTP 19)
* Erlang/OTP version (erl):
* Sentry version (mix deps): sentry 5.0.1 (Hex package) (mix)
* Operating system: windows 10

### Description
I created account on sentry.io, configured sentry in my elixir project, tried to produce errors (like running a wrong url) and I did not see any issues on on-line platform. 

### Expected Behavior
Events (errors, issues etc.) appear on online platform in project overview.

### Actual Behavior
Project overview is empty, your error robot "is waiting to devour receive your first event".

### Steps to Reproduce
https://docs.sentry.io/clients/elixir/?platform=javascript

**Comment by Nrisimha** [comment]
Codes:
mix.ex
`defp deps do
    [
      {:phoenix, "~> 1.3.0"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_html, "~> 2.10"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:gettext, "~> 0.11"},
      {:cowboy, "~> 1.0"},
      {:xarango, "~> 0.6.1"},
      {:comeonin, "~> 4.0"},
      {:bcrypt_elixir, "~> 1.0"},
      {:guardian, "~> 1.0.0", override: false},
      {:ex_json_schema, "~> 0.5.4"},
      {:wallaby, "~> 0.19.2", [runtime: false, only: :test]},
      {:httpoison, "~> 0.8", override: true},
      {:poison, "~> 1.5.0", override: true},
      {:cors_plug, "~> 1.5"},
      {:sentry, "~> 5.0.0"},
      {:jason, "~> 1.1"},
    ]
  end`
prod.ex
`# sentry configuration
config :sentry,
  dsn: "...",
  environment_name: :prod,
  enable_source_code_context: true,
  root_source_code_path: File.cwd!,
  tags: %{
    env: "production"
  },
  included_environments: [:prod]
`
config.exs
`# sentry configuration
config :sentry,
dsn: "https://2cb2f734157d48bab172b1fb9117ab40@sentry.io/1285004",
enable_source_code_context: true,
use_error_logger:           true,
root_source_code_path:      File.cwd!,
tags:                       %{env: "production"},
environment_name:           Mix.env(),
included_environments:      [:prod]`
router.ex
`defmodule FoodServerWeb.Router do
  use FoodServerWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug
...`

**Comment by mitchellhenke** [comment]
@Nrisimha thanks for opening an issue!

Requesting an undefined endpoint won't generate any errors in Sentry by default.  If you raise an error in an endpoint and request it, an error should show up in Sentry.

Are you running in development mode or is this in production?

One way to test is to run `mix sentry.send_test_event` in the environment you're running Sentry in, and it will say if an event was sent or not.

**Comment by Nrisimha** [comment]
Okay, I solved previous error with running `mix sentry.send_test_event`, problem was in my configurations, I needed to change my `dsn` to deprecated one (on sentry.io go  [Project] » Settings » Client Keys). I also included environment name `:dev`, because it looks like my project runs in dev mode (changed `included_environments` option). Now I have this error:

```
Client configuration:
server: https://sentry.io:443/api/1285004/store/
public_key: 2cb2f734157d48bab172b1fb9117ab40
secret_key: 68844a042571454c9ea1a5c18ecb3678
included_environments: [:prod, :dev]
current environment_name: :dev
hackney_opts: []

Sending test event...
** (UndefinedFunctionError) function :certifi_cacerts.ders/0 is undefined (module :certifi_cacerts is not available)
    :certifi_cacerts.ders()
    (hackney) d:/Dev/Phoenix/food_server/deps/hackney/src/hackney_connect.erl:287: :hackney_connect.ssl_opts/2
    (hackney) d:/Dev/Phoenix/food_server/deps/hackney/src/hackney_connect.erl:242: :hackney_connect.do_connect/5
    (hackney) d:/Dev/Phoenix/food_server/deps/hackney/src/hackney_connect.erl:37: :hackney_connect.connect/5
    (hackney) d:/Dev/Phoenix/food_server/deps/hackney/src/hackney.erl:315: :hackney.request/5
    (sentry) lib/sentry/client.ex:130: Sentry.Client.request/4
    (sentry) lib/sentry/client.ex:114: Sentry.Client.try_request/5
    (sentry) lib/sentry/client.ex:95: Sentry.Client.do_send_event/3
```

**Comment by mitchellhenke** [comment]
Glad you were able to solve it.  I would also consider upgrading to a more recent Sentry 🙂
