### ISSUE TITLE
Support for phoenix 1.4

### ISSUE THREAD

**Issue by vasspilka** [getsentry/sentry-elixir#308]
Upgrading to RC I get

```
Failed to use "phoenix" because
  apps/api/mix.exs requires ~> 1.4.0-rc.0
  sentry (version 7.0.1) requires ~> 1.3 *
```

**Comment by mitchellhenke** [comment]
@vasspilka thanks for opening an issue!  Sentry should support Phoenix 1.4 without any changes, and the `~> 1.3` version requirement will match `1.4` when it is released, but it doesn't match on release candidates.

I think the easiest way to handle it is to override your phoenix dependency, which will direct libraries that depend on Phoenix to ignore their Phoenix version requirements:

```diff
-      {:phoenix, "1.4.0-rc.0"},
+      {:phoenix, "1.4.0-rc.0", override: true},
```

Could you try that and let me know if that fixes your issue?

**Comment by vasspilka** [comment]
It does :) <3

**Comment by mitchellhenke** [comment]
awesome, glad it was solved!
