### ISSUE TITLE
Sentry.Logger.Backend in umbrella application

### ISSUE THREAD

**Issue by stevedomin** [getsentry/sentry-elixir#316]
### Environment

* Elixir version (elixir -v): 1.7.4
* Erlang/OTP version (erl): 21
* Sentry version (mix deps): 7.0.3

### Description

Previously the Sentry.Logger had documentation on how to prevent the backend from being added multiple times when you were running an umbrella application. Is that still an issue with the new Sentry.LoggerBackend?

### Related issues

* #205 
* #276

**Comment by mitchellhenke** [comment]
Thanks for opening this!

It should not be an issue with `Sentry.LoggerBackend`.  [Logger.add_backend/2](https://hexdocs.pm/logger/Logger.html#add_backend/2) shouldn't allow you to add the same backend multiple times (it will return `{:error, :already_present}` or similar).

**Comment by stevedomin** [comment]
Thanks @mitchellhenke, makes sense.

**Comment by mitchellhenke** [comment]
Happy to help!

I haven't done much testing with umbrella apps, so if you run into anything that could be improved, just let me know 🙂
