### ISSUE TITLE
(Question) Why dependency on Phoenix 1.3?

### ISSUE THREAD

**Issue by mstratman** [getsentry/sentry-elixir#317]
I'm trying to update Phoenix to 1.4 and `mix` is giving errors unless overridden. Are there known issues with Phoenix 1.4?

**Comment by mitchellhenke** [comment]
Hi, thanks for opening an issue!

The optional dependency is `{:phoenix, "~> 1.3", optional: true}`, so it should work for both Phoenix `1.3.x` and `1.4.x`.

Which version of Sentry are you on, and could you gist the error message?

**Comment by mitchellhenke** [comment]
If you have more details on the issue, I'd be happy to take a look

Absent that, I'll be closing this issue for now 🙂
