### ISSUE TITLE
issues with cowboy 2

### ISSUE THREAD

**Issue by atomkirk** [getsentry/sentry-elixir#318]
### Environment

* Elixir version (elixir -v): 1.7.3
* Erlang/OTP version (erl): 21.1
* Sentry version (mix deps): 7.0.1
* Operating system: Google Cloud Linux

### Description
Before we upgraded to phoenix 1.4 (with cowboy 2), our errors came through fine, but now we get them all bunched together with the same useless stack trace:

```
  File "lib/phoenix/endpoint/cowboy2_handler.ex", line 43, in Phoenix.Endpoint.Cowboy2Handler.init/2
  File "/srv/zipbooks/phoenix-api/deps/cowboy/src/cowboy_handler.erl", line 41, in :cowboy_handler.execute/2
  File "/srv/zipbooks/phoenix-api/deps/cowboy/src/cowboy_stream_h.erl", line 293, in :cowboy_stream_h.execute/3
  File "/srv/zipbooks/phoenix-api/deps/cowboy/src/cowboy_stream_h.erl", line 271, in :cowboy_stream_h.request_process/3
  File "proc_lib.erl", line 249, in :proc_lib.init_p_do_apply/3
```

And it looks like we aren't getting any errors for router errors that phoenix usually catches.

Any ideas here?

**Comment by mitchellhenke** [comment]
Thanks for opening an issue 🙂 

Are you using `Sentry.Plug`?

**Comment by michaelst** [comment]
We are using Sentry.Plug, we also tried upgrading to 7.0.3

**Comment by mitchellhenke** [comment]
The issue does sound odd with `Sentry.Plug` also being set up.  I created a Phoenix 1.4 project using Cowboy 2 and Sentry 7 to try to reproduce, but I get errors as I would expect.

Could you share some more detail on what kind of router errors?

**Comment by michaelst** [comment]
With the upgrade to 7.0.3 we started to get some other expected errors.

However, we still are getting errors through this, specifically we get a lot of this error, which we didn't use to get as the endpoint just returns 404
`(ErlangError) Erlang error: {{{%Ecto.NoResultsError{message: "expected at least one result but got none in query:`

I have also noticed some mysql deadlock and constraint errors come through that same thing. Everything starts with `(ErlangError) Erlang error`.

We tried adding this to filter them out as they appear to not be real errors, but this doesn't work 
```
def exclude_exception?(%ErlangError{}, _source), do: true

**Comment by atomkirk** [comment]
Some helpful context here is that this is related to the other issue I opened about setting `handle_sasl_reports: true` on logger. I know you said that option might not be around forever, but we've found through experimentation that we miss errors in sentry without it. The errors we don't miss still come through, but they also come through as erlang errors, so we do get some duplicates.

Whats strange here is that since ecto 3/phoenix 1.4/cowboy 2, we are getting `Ecto.NoResultsError` errors which we ignore in our filter:

```
defmodule ZB.SentryEventFilter do
  @behaviour Sentry.EventFilter

  @ignored [
    "Call to refresh token endpoint failed: {:error, %HTTPoison.Error{id: nil, reason: :closed}}"
  ]

  def exclude_exception?(%Phoenix.Router.NoRouteError{}, _source), do: true
  def exclude_exception?(%Plug.BadRequestError{}, _source), do: true
  def exclude_exception?(%Ecto.NoResultsError{}, :plug), do: true
  def exclude_exception?(%Ecto.NoResultsError{}, :endpoint), do: true
  def exclude_exception?(%RuntimeError{message: msg}, _source) when msg in @ignored, do: true
  def exclude_exception?(_exception, _source), do: false
end
```

This problem is probably very unique to us because of our use of `handle_sasl_reports` but any help to know how to filter these errors out would be appreciated.

**Comment by mitchellhenke** [comment]
Thanks for the details.  I've done some investigation into this and it seems as though part of the issues you're experiencing are from using SASL reports.  In enabling them, I was able to reproduce some of what you're seeing.

The combination of SASL and Sentry is producing exceptions like `{{{%Ecto.NoResultsError{message: "expected at least one result but got none in query: [...]` which means the exception Sentry is receiving is wrapped in a few tuples rather than just the exception struct itself.

To exclude them, the filter would have to include something like the following:

```elixir
  def exclude_exception?({{{%Ecto.NoResultsError{}, _, _}, _, }, _}, _source), do: true
```

I don't know the exact tuple structure, but SASL reports appear to be the root issue of the unexpected format, causing the issues with filtering.

I think the best fix would be to have Sentry catching the exceptions it's currently missing for you and move away from SASL.

Do you know which exceptions aren't being reported currently?

**Comment by mitchellhenke** [comment]
I appreciate the issue being opened and the information provided, but I unfortunately do not have enough to take action on.  I'm more than happy to re-open this issue and answer questions related to it, but I'll be closing it for now.
