### ISSUE TITLE
Compilation Error: Plug.Conn.__struct__/0 is undefined

### ISSUE THREAD

**Issue by kenips** [getsentry/sentry-elixir#325]
### Environment

* Elixir version (elixir -v): 1.7.1
* Erlang/OTP version (erl): 21
* Sentry version (mix deps): 7.0.3
* Operating system: macOS 10.14.3

### Description
When upgrading to Sentry 7 I run into compilation error. This is a Phoenix app so pretty weird that it complains about this, as there was a similar error before https://github.com/getsentry/sentry-elixir/issues/88 and the fix is still in place. Wondering what else it could be?

### Actual Behavior
```
Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

==> sentry
Compiling 13 files (.ex)

== Compilation error in file lib/sentry/plug.ex ==
** (CompileError) lib/sentry/plug.ex:150: Plug.Conn.__struct__/0 is undefined, cannot expand struct Plug.Conn
    lib/sentry/plug.ex:150: (module)
could not compile dependency :sentry, "mix compile" failed. You can recompile this dependency with "mix deps.compile sentry", update it with "mix deps.update sentry" or clean it with "mix deps.clean sentry"
```

**Comment by kenips** [comment]
Not sure what caused it. Deleted the deps folder and retried and worked.

**Comment by mitchellhenke** [comment]
@kenips that's what I was going to suggest, but it's still kind of odd 😕

**Comment by kenips** [comment]
@mitchellhenke yeah really odd. Before I deleted the deps folder I did change the first line of `lib/sentry/plug.ex` from `if Code.ensure_loaded?(Plug) do` to `if Code.ensure_loaded?(Plug.Conn) do` and it compiled, but I got another another undefined error so I took the delete route...
