### ISSUE TITLE
Failed to send Sentry event (:unknown_ca)

### ISSUE THREAD

**Issue by LiyangW** [getsentry/sentry-elixir#333]
### Environment

* Elixir version (elixir -v): 1.8.1
* Erlang/OTP version (erl): 21
* Sentry version (mix deps): 7.0.5
* Operating system: Mac OS 

### Description

I followed the instructions on the Sentry documentation to set up my application with sentry plug-in.  After running ` MIX_ENV=dev mix sentry.send_test_event` testing command, I got the following error message.
### Actual Behavior
```
Client configuration:
server: https://...
public_key: ...
secret_key: ..
included_environments: [:dev]
current environment_name: :dev
hackney_opts: []

Sending test event...

15:06:36.547 [info]  ['TLS', 32, 'client', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'certify', 32, 'at ssl_handshake.erl:1370 generated CLIENT ALERT: Fatal - Unknown CA', 10]

15:06:36.550 [warn]  Failed to send Sentry event.
Event ID: 3d3341c4f6a749f0a1f0c0837197a82d - {:error, {:tls_alert, {:unknown_ca, 'received CLIENT ALERT: Fatal - Unknown CA'}}} - {"breadcrumbs":[],"culprit":null,"environment":"dev","event_id":"3d3341c4f6a749f0a1f0c0837197a82d","exception":[{"module":null,"type":"RuntimeError","value":"Testing sending Sentry event"}],"extra":{},"fingerprint":["{{ default }}"],"level":"error","message":"(RuntimeError) Testing sending Sentry event","modules":{"certifi":"2.5.1","cowboy":"","cowlib":"","decimal":"","hackney":"1.15.1","idna":"6.0.0","jason":"","metrics":"1.0.1","mime":"1.3.1","mimerl":"1.2.0","parse_trans":"","phoenix":"1.4.3","phoenix_pubsub":"1.1.2","plug":"1.7.2","plug_cowboy":"","plug_crypto":"1.0.0","ranch":"","ssl_verify_fun":"1.1.4","unicode_util_compat":"0.4.1"},"platform":"elixir","release":null,"request":{},"server_name":"Liyang","tags":{"env":"staging"},"timestamp":"2019-04-15T19:06:36","user":{}}
```

### Steps to Reproduce
1, add `{:sentry, "~>7.0"}` in `mix.exs`
2, add ` {:ok, _} = Logger.add_backend(Sentry.LoggerBackend)` in `application.ex`
3, add `use Sentry.Phoenix.Endpoint` in `endpoint.ex`
4, add ```use Plug.ErrorHandler
              use Sentry.Plug``` 
    in `router.ex`
5, change `dev.exs` to 
```config :sentry,
  dsn: {:system, "SENTRY_DSN_BACKEND"},
  environment_name: :dev,
  enable_source_code_context: true,
  root_source_code_path: File.cwd!(),
  tags: %{
    env: "staging"
  },
  included_environments: [:dev]
```
6. run `MIX_ENV=dev mix sentry.send_test_event`

**Comment by mitchellhenke** [comment]
Hi @LiyangW!  Thanks for opening an issue.

Unfortunately this seems like an issue with SSL and certificates, which can be hard to troubleshoot, and may need to be solved outside of Sentry.

Are other parts of your application able to make HTTP requests?

**Comment by LiyangW** [comment]
Hey @mitchellhenke, thanks for answering!
I am able to make HTTP requests using `HTTPotion` in my application.

One thing I noticed while experimenting with `sentry` is that I deployed my application on two environments, one is verified by `Let's Encrypt CA`, and another is verified by `Digicert CA`.  While the `sentry` testing command is failing on the `Let's Encrypt` environment, it worked on the `Digicert` environment.

Could the problem be related to the `hackney` CA bundle?

**Comment by mitchellhenke** [comment]
I'm not super familiar with certificate bundles and SSL related issues.  hackney uses the Mozilla CA bundle via the https://hex.pm/packages/certifi package.  I'm not sure how HTTPotion handles SSL certificates, or what differences could cause it to succeed while hackney fails.

It may be outside of the scope of Sentry to handle those things, unless you have some suggestions on how Sentry could better accommodate your use case?

**Comment by mitchellhenke** [comment]
@LiyangW were you able to solve this?

**Comment by LiyangW** [comment]
@mitchellhenke  Hey thanks for the following up!  
I decide to not digging in and move on.  I simply passed hackney options `hackney: [insecure: true] `, so the certification step is skipped!

**Comment by mitchellhenke** [comment]
@LiyangW thanks for letting me know the solution! I'm going to close the issue for now, but if there's anything Sentry can do to improve this, feel free to comment back and I can take a closer look.

**Comment by rjhcnf** [comment]
Hi @LiyangW , I am having the same issue now :-( could you tell me where exactly you added hackney: [insecure: true]?
