### ISSUE TITLE
Logger metadata unavailable when using LoggerBackend

### ISSUE THREAD

**Issue by thdxr** [getsentry/sentry-elixir#336]
Currently the recommended way to attach Logger.metadata is via a presend hook that pulls out relevant metadata and attaches it to the event.  This works great under normal situations because the presend hook runs in the same process as where the exception occurred, making Logger.metadata accessible.

However when using the LoggerBackend the message is first sent to a gen event process before being turned into a Sentry exception.  The presend hook loses access to the original Logger.context.

This is fixable and there's a few ways to do but wanted to get it on the radar as I work on the issue

**Comment by thdxr** [comment]
This option is probably too presumptuous but is an option:
https://github.com/ironbay/sentry-elixir/commit/2b7a35e6778823ae1901b07a2213475bcf076e93

**Comment by mitchellhenke** [comment]
@thdxr hey, thanks for opening an issue!

It looks like this became possible with Elixir 1.7/OTP 20 Logger changes, so we should be safe on that end.

I think a solution like the one linked is a good starting point 🙂

**Comment by mitchellhenke** [comment]
I started playing around a bit with this.  I think a solution along the lines of: https://github.com/getsentry/sentry-elixir/compare/logger-metadata?expand=1

is workable?

I think for now I'd rather avoid recursing through nested maps/lists, as it could be a can of worms if there happens to be an extremely nested or lengthy list/map.

**Comment by thdxr** [comment]
That looks perfect, I agree about the recursion because even the default console logger expects you to pass in primitives and not nested objects

**Comment by mitchellhenke** [comment]
Cool!

I've opted to have it disabled by default due to potentially sensitive information being included in events, with it being enabled using `Logger.configure_backend/2` in #338
