### ISSUE TITLE
Different docs between sentry website and readme

### ISSUE THREAD

**Issue by alex88** [getsentry/sentry-elixir#339]
### Description

https://docs.sentry.io/clients/elixir/config/ shows that you have to use `:error_logger.add_report_handler(Sentry.Logger)` to capture non-plug errors while the readme uses `{:ok, _} = Logger.add_backend(Sentry.LoggerBackend)`, is it the same? Which one is the most updated one?

It also says to add a `Sentry.TaskSupervisor` while the readme doesn't, I've found that I could need that since I'm getting errors like
```
** (exit) exited in: GenServer.call(Sentry.TaskSupervisor, {:start_task, [#PID<0.4806.0>, :monitor, {:"web@127.0.0.1", #PID<0.4806.0>}, {:erlang, :apply, [#Function<3.31271745/0 in Sentry.Client.do_send_event/3>, []]}], :temporary, nil}, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
06:19:02.163 [error] :gen_event handler Sentry.LoggerBackend installed in Logger terminating
** (stop) exited in: GenServer.call(Sentry.TaskSupervisor, {:start_task, [#PID<0.282.0>, :monitor, {:"web@127.0.0.1", Logger}, {:erlang, :apply, [#Function<3.31271745/0 in Sentry.Client.do_send_event/3>, []]}], :temporary, nil}, :infinity)
```

**Comment by mitchellhenke** [comment]
Ah, oops! I will fix this 🙂

**Comment by alex88** [comment]
@mitchellhenke so the `Sentry.TaskSupervisor` isn't needed?

**Comment by mitchellhenke** [comment]
@alex88 what version of Sentry are you on?

**Comment by alex88** [comment]
@mitchellhenke 7.0.6 in the main `mix.exs` file of an umbrella app, then I do the `Logger.add_backend` in the web app which is started with `mix phx.server`, I'm not 100% sure if the fact I don't have that in the non web-app matters but I get some error reports, I just get that error in sub-processes

**Comment by mitchellhenke** [comment]
ah, the TaskSupervisor isn't necessary, no, and neither is the :hackney client stuff.  It was intended to be an example of an application Sentry was being added to, but the usage of the Sentry module name in that was unnecessarily confusing.

**Comment by alex88** [comment]
mhhh ok, I'll try to investigate why I get that error then, thanks

**Comment by mitchellhenke** [comment]
Sounds good! Let me know if the issue persists

**Comment by alex88** [comment]
Yeah it does for some reason, anyway that's probably out of topic for this task.

**Comment by mitchellhenke** [comment]
if back and forth discussion would be easier to debug the issue, I'm in #elixir-lang IRC and the Elixir Slack as `mitchellhenke` as well

**Comment by staring-frog** [comment]
> Sounds good! Let me know if the issue persists

I was getting the same error on 7.2.4
```
[error] ** (exit) exited in: GenServer.call(Sentry.TaskSupervisor, {:start_task, [{:nonode@nohost, #PID<0.607.0>, #PID<0.607.0>}, [#PID<0.607.0>], :monitor, {:erlang, :apply, [#Function<2.116676551/0 in Sentry.Client.do_send_event/3>, []]}], :temporary, nil}, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:979: GenServer.call/3
    (elixir) lib/task/supervisor.ex:447: Task.Supervisor.async/6
    lib/sentry/client.ex:112: Sentry.Client.do_send_event/3
    lib/sentry/client.ex:94: Sentry.Client.encode_and_send/3
    (plug) lib/plug/error_handler.ex:98: Plug.ErrorHandler.__catch__/6
```

solved the problem by adding :sentry to `def application`

**Comment by mitchellhenke** [comment]
@staring-frog That step is no longer included because as of Elixir 1.4, anything in `deps` will automatically have its application started as long as `:applications` is empty 🙂

The background information and conversion to `:extra_applications` is described in the release blog post [here](https://elixir-lang.org/blog/2017/01/05/elixir-v1-4-0-released/).

**Comment by staring-frog** [comment]
@mitchellhenke Oh, thanks, I didn't know that, I guess it's a bug in the Mix then. I have both conditions met. Sentry is in the top mix.exs though, I guess this is not handled properly.

**Comment by mitchellhenke** [comment]
@staring-frog Sure thing 🙂

Applications are typically generated with:

```elixir
  def application do
    [
      mod: {MyApp.Application, []},
      extra_applications: [:logger, :runtime_tools]
    ]
  end
```

to make use of the inferred application starts.

**Comment by staring-frog** [comment]
Thanks, that's exactly what I have though :man_shrugging:

**Comment by mitchellhenke** [comment]
Ah, apologies, I misunderstood. This would be a significant bug, could you share your minimal mix.exs and Elixir/Erlang versions so I can reproduce?

**Comment by staring-frog** [comment]
@mitchellhenke np, here it is https://github.com/staring-frog/scratches :
```
$ iex -S mix run
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Application.started_applications
[
  {:app1, 'app1', '0.1.0'},
  {:logger, 'logger', '1.8.2'},
  {:hex, 'hex', '0.20.5'},
  {:inets, 'INETS  CXC 138 49', '7.1'},
  {:ssl, 'Erlang/OTP SSL application', '9.4'},
  {:public_key, 'Public key infrastructure', '1.7'},
  {:asn1, 'The Erlang ASN1 compiler version 5.0.9', '5.0.9'},
  {:crypto, 'CRYPTO', '4.6'},
  {:mix, 'mix', '1.8.2'},
  {:iex, 'iex', '1.8.2'},
  {:elixir, 'elixir', '1.8.2'},
  {:compiler, 'ERTS  CXC 138 10', '7.4.5'},
  {:stdlib, 'ERTS  CXC 138 10', '3.10'},
  {:kernel, 'ERTS  CXC 138 10', '6.5'}
]
# No Sentry started.
iex(2)> Application.start(:sentry)      
{:error, {:not_started, :hackney}}
iex(3)> Application.ensure_started(:sentry)
{:error, {:not_started, :hackney}}
iex(4)> Application.ensure_all_started(:sentry)
{:ok,
 [:unicode_util_compat, :idna, :mimerl, :certifi, :ssl_verify_fun, :metrics,
  :hackney, :sentry]}
iex(5)> Application.started_applications       
[
  {:sentry, 'The Official Elixir client for Sentry', '7.2.4'},
  {:hackney, 'simple HTTP client', '1.15.2'},
  {:metrics, 'A generic interface to different metrics systems in Erlang.',
   '1.0.1'},
  {:ssl_verify_fun, 'SSL verification functions for Erlang\n', '1.1.5'},
  {:certifi, 'CA bundle adapted from Mozilla by https://certifi.io', '2.5.1'},
  {:mimerl, 'Library to handle mimetypes', '1.2.0'},
  {:idna, 'A pure Erlang IDNA implementation', '6.0.0'},
  {:unicode_util_compat, 'unicode_util compatibility library for Erlang < 20',
   '0.4.1'},
  {:app1, 'app1', '0.1.0'},
  {:logger, 'logger', '1.8.2'},
  {:hex, 'hex', '0.20.5'},
  {:inets, 'INETS  CXC 138 49', '7.1'},
  {:ssl, 'Erlang/OTP SSL application', '9.4'},
  {:public_key, 'Public key infrastructure', '1.7'},
  {:asn1, 'The Erlang ASN1 compiler version 5.0.9', '5.0.9'},
  {:crypto, 'CRYPTO', '4.6'},
  {:mix, 'mix', '1.8.2'},
  {:iex, 'iex', '1.8.2'},
  {:elixir, 'elixir', '1.8.2'},
  {:compiler, 'ERTS  CXC 138 10', '7.4.5'},
  {:stdlib, 'ERTS  CXC 138 10', '3.10'},
  {:kernel, 'ERTS  CXC 138 10', '6.5'}
]
# There it is now.
```

**Comment by mitchellhenke** [comment]
Ah, I missed that it was an umbrella application as well. Umbrella applications require runtime dependencies like Sentry to be specified in the child applications' dependencies, and it will start within them properly. The common config can be at the top level though.

I will improve the documentation around this 🙂

**Comment by staring-frog** [comment]
Ok, thanks!
