### ISSUE TITLE
Remove newline from API error logging

### ISSUE THREAD

**Issue by halostatue** [getsentry/sentry-elixir#343]
### Environment

* Elixir version (elixir -v): 1.7.4
* Erlang/OTP version (erl): 21
* Sentry version (mix deps): 7.0.6
* Operating system: MacOS

### Description

The private function `Sentry.Client.log_api_error/1` ([lib/sentry/client.ex:338-345](https://github.com/getsentry/sentry-elixir/blob/ace9faf4f518a0764a81f40ac6ac580f62fe41e6/lib/sentry/client.ex#L338-L345)) currently includes a newline in its log body, which is problematic when capturing Erlang logs to something like an ELK stack, because `Failed to send Sentry event` and the body of the failure are on two different lines.

I would recommend that this change to something like:

```elixir
  defp log_api_error(body) do
    Logger.log(
      Config.log_level(),
      fn ->
        ["Failed to send Sentry event: ", inspect(body)]
      end
    )
  end
```

**Comment by mitchellhenke** [comment]
I think that should be fine to change.

I don't think it would disrupt anyone's logs to do so?

**Comment by halostatue** [comment]
It shouldn’t, although this could be a compile-time configuration option to use the old format vs the new format:

```elixir
  @api_log_error_newline fn body -> fn -> ["Failed to send Sentry event:", ?\n, body] end end
  @api_log_error_oneline fn body -> fn -> ["Failed to send Sentry event: ", inspect(body)] end end

  @api_log_format case Sentry.Config.api_log_format() do
                    fun when is_function(fun, 1) -> fun
                    {module, function} -> &module.function/1
                    :oneline -> @api_log_error_oneline
                    _ -> @api_log_error_newline
                  end

  defp log_api_error(body) do
    Logger.log(Config.log_level(), @api_log_format)
  end
```

The spec would be something like:

`@type api_log_function :oneline | nil | {module, atom} | (String.t() -> (-> iodata))` such that as long as  a module/function accepts a body and returns an iodata, it would all work (this would allow custom error log formats).

It would require `mix deps.compile sentry` whenever this is changed, but that seems to be a small change for big benefit.

**Comment by halostatue** [comment]
@mitchellhenke I can implement this as a PR, if you’d like, but we’re getting alerts on spike protection because of this logging and can’t tell the difference between errors that are spike protection vs errors that are encoding problems that we need to fix because of it (the interleaving of messages in ELK from multiple nodes means that line one and line two can be several messages apart).

**Comment by mitchellhenke** [comment]
@halostatue yes, that would be great! 🙂

**Comment by halostatue** [comment]
Sure. I’ll get it in the next day or so.
