### ISSUE TITLE
No match for {:ok, _} = Logger.add_backend(Sentry.LoggerBackend)

### ISSUE THREAD

**Issue by damboscolo** [getsentry/sentry-elixir#345]
### Environment

* Elixir version (elixir -v): 1.8.1
* Erlang/OTP version (erl): 10.3
* Sentry version (mix deps): 7.0.6
* Operating system: MacOS

### Description

I just integrate with Sentry and this code did not work for me:
```elixir
{:ok, _} = Logger.add_backend(Sentry.LoggerBackend)
```
i'm getting this error at build time:

```elixir
** (Mix) Could not start application apollo: exited in: Apollo.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, :already_present}
            (apollo) lib/apollo/application.ex:9: Apollo.Application.start/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4
```

I removed the pattern matching to build and it logged the event in Sentry, is it really necessary or is there something wrong in my config?

**Comment by mitchellhenke** [comment]
It looks like you may be adding it multiple times.

Is this in an umbrella app?

**Comment by damboscolo** [comment]
I added in all the apps inside the umbrella

**Comment by mitchellhenke** [comment]
`{:error, :already_present}` suggests the Logger backend has already been added.  It's only necessary to make that function call once, so if you're calling it in each umbrella application, you'll get that error.

**Comment by damboscolo** [comment]
got it! thanks!

I need apps to be independent of each other, so I'll create an app to initialize the sentry and add this app as dependencies of the others, thus ensuring that it will only be initialized once.
