### ISSUE TITLE
It would be helpful to add `set_http_context` to docs.

### ISSUE THREAD

**Issue by CrowdHailer** [getsentry/sentry-elixir#350]
Could these [documents](https://docs.sentry.io/clients/elixir/?_ga=2.132887118.1995204738.1560861952-1085467333.1553082584#context-and-breadcrumbs) also reference set_http_context.

I read through the plug source and got to here https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/plug.ex#L139

because in `capture_exception` you can pass a request key to options I spent some time looking for `set_request_context` as a function.

**Comment by mitchellhenke** [comment]
Thanks for letting me know about this! 🙂

I've got an open pull request for those docs [here](https://github.com/getsentry/sentry-docs/pull/957), so I've added a commit that adds an example line for `set_http_context`.
