### ISSUE TITLE
Error compiling Sentry.Plug on Heroku

### ISSUE THREAD

**Issue by swelham** [getsentry/sentry-elixir#356]
### Environment

* Elixir version: 1.8.1
* Erlang/OTP version (erl): 21.2.4
* Sentry version (mix deps): 7.1.0
* Operating system: Heroku Dyno

### Description

When deploying to Heroku using the `hook_pre_compile="mix sentry_recompile"` buildpack config on a fresh dyno or a dyno where the build cache has been purged, it will fail to compile because the `Sentry.Plug` module is not loaded. Removing the config from the buildpack allows the build to succeed.

### Expected Behavior

The application should compile with or without cached build files without having to remove the `hook_pre_compile="mix sentry_recompile"` line from the buildpack config file.

### Actual Behavior

When building without cached build files the application will fail with the following error.
```
remote: == Compilation error in file lib/sentry_plug_error_web/router.ex ==
remote: ** (CompileError) lib/sentry_plug_error_web/router.ex:4: module Sentry.Plug is not loaded and could not be found
remote:     (elixir) expanding macro: Kernel.use/1
remote:     lib/sentry_plug_error_web/router.ex:4: SentryPlugErrorWeb.Router (module)
remote:  !     Push rejected, failed to compile Elixir app.
```

### Steps to Reproduce

I was able to reproduce this issue by creating a new Phoenix application and configuring it to use the Sentry library and then pushing the repo to a new Heroku dyno. I have created a repo containing the application that will fail to compile [here](https://github.com/swelham/elixir-sentry-plug-compile-error).

To reproduce create a new Heroku dyno and under the settings tab set the buildpack config to `https://github.com/HashNuke/heroku-buildpack-elixir.git`. Now clone the repo linked above and run `heroku git:remote -a <heroku app name>` and then `git push heroku master`.

It will eventually display the above error after it has started compiling the application.

**Comment by mitchellhenke** [comment]
@swelham thank you for the very detailed and reproducible report! 🙂

I was able to reproduce the issue.  This is behavior I would not have expected from `mix deps.compile`, as it will strictly compile only that dependency and none of the dependency's dependencies (regardless of the `--force` switch).  The clue being running `mix deps.compile sentry` the first time results in:

```
mix deps.compile sentry
==> sentry
Compiling 14 files (.ex)
warning: function :hackney.body/1 is undefined (module :hackney is not available)
  lib/sentry/client.ex:170

warning: function :hackney.request/5 is undefined (module :hackney is not available)
  lib/sentry/client.ex:169

warning: function :hackney.skip_body/1 is undefined (module :hackney is not available)
  lib/sentry/client.ex:175

warning: function :hackney_pool.child_spec/2 is undefined (module :hackney_pool is not available)
  lib/sentry.ex:99
```

The solution is either to swap the order of the compilation steps:

```elixir
sentry_recompile: ["compile", "deps.compile sentry --force"]
```

or specify that child dependencies should also be compiled:

```elixir
sentry_recompile: ["deps.compile sentry --force --include-children", "compile"]
```

The combination of the `--force` and `--include-children` switches means all of Sentry's dependencies will always be recompiled, which might be kind of a pain if you've already compiled them (on Heroku or elsewhere), so my feeling is to recommend `["compile", "deps.compile sentry --force"]` as the default.  I've done that here: https://github.com/getsentry/sentry-elixir/pull/357

**Comment by swelham** [comment]
@mitchellhenke thank you for the detailed response and solution 👍

**Comment by leandrocp** [comment]
Thanks for the fix. Probably should update the docs? https://docs.sentry.io/clients/elixir/#including-source-code

**Comment by mitchellhenke** [comment]
@leandrocp Thanks, I've submitted a PR to fix it!
