### ISSUE TITLE
Erlang error: :socket_closed_unexpectedly not reported to Sentry

### ISSUE THREAD

**Issue by islamhamdi** [getsentry/sentry-elixir#359]
### Environment

* Elixir version (elixir -v): Elixir 1.8.2
* Erlang/OTP version (erl): Erlang/OTP 22
* Sentry version (mix deps): sentry 7.0
* Operating system: macOS Mojave

### Description

The project, I integrated sentry with, uses a custom elixir package that connects to Rabbitmq with amqp connections. Sporadically we can get errors like:

`Erlang error: :socket_closed_unexpectedly`

But they're not reported to Sentry. We used to use Honeybadger beforehands and they were reported normally, just trying to figure out what can be missing.

### Expected Behavior

Error `Erlang error: :socket_closed_unexpectedly` reported to Sentry

### Actual Behavior

Nothing is reported

### Steps to Reproduce

A lib that connects to rabbitmq with amqp connections, connection management fails.

**Comment by mitchellhenke** [comment]
@islamhamdi thanks for opening an issue!

Sentry should report any crashed process, but without information on which library is being used, it is difficult to troubleshoot.

Can you link me to the library you are using?

**Comment by mitchellhenke** [comment]
Going to close this issue for now, but happy to reopen and investigate further with more information 🙂
