### ISSUE TITLE
Enhancement: Grab release version from env

### ISSUE THREAD

**Issue by jnylen** [getsentry/sentry-elixir#361]
### Environment

* Elixir version (elixir -v): 1.9.1
* Erlang/OTP version (erl): 22.0
* Sentry version (mix deps): 7+
* Operating system: Linux

### Description

This is just an enhancement tip, in 1.9.0+ (the one with mix release) you can grab the application version via: `System.get_env("RELEASE_VSN")`

Would be cool if it default to this when the release is nil/not in the config.

**Comment by mitchellhenke** [comment]
@jnylen thanks for opening an issue!

I can definitely add this soon.

**Comment by paulstatezny** [comment]
@mitchellhenke Was this ever added? I haven't found any documentation on it. Thanks!

**Comment by mitchellhenke** [comment]
This hasn't been added yet. I did prototype it and pulling from `"RELEASE_VSN"` is straightforward enough, but reading from the system environment for every event is something I'd like to avoid.

Do you think an update to the documentation and README for this more common configuration case would be sufficient?

**Comment by jnylen** [comment]
@mitchellhenke one way is just to call it while booting up and then cache it for the lifetime of the current run. I'm not sure if `RELEASE_VSN` is available on build though otherwise that's the best.

**Comment by mitchellhenke** [comment]
Yeah, absolutely. The tricky part is it should fit within the existing configuration process, which has some elements of that already.

**Comment by yordis** [comment]
Could this be resolved by improving the sample code from the Sentry Elixir New Project guide and the readme of this repo or something?

**Comment by whatyouhide** [comment]
This is not really valid anymore, IMO. In v9.0.0 of sentry-elixir, you'll have to set the `SENTRY_RELEASE` env variable. You can always set it to `System.get_env("RELEASE_VSN")`. 🙃  This way, we don't do any additional "magic" behind the scenes.
