### ISSUE TITLE
Beginner Configuration Question for Phoenix

### ISSUE THREAD

**Issue by nbw** [getsentry/sentry-elixir#369]
### Description

I'm using Phoenix and the documentation for sentry-elixir reads:

```
In your Plug.Router or Phoenix.Router, add the following lines:

use Plug.ErrorHandler
use Sentry.Plug
```

To clarify, when you say `Phoenix.Router` do you mean `[My app name]Web.Router.ex`, which would be in `lib/[my app name]web/router.ex`. Because the actual Phoenix.Router module belongs to phoenix in my deps folder. 

I've been trying to actually get errors to pop up on Sentry with no avail, so I'm just trying to figure out where I'm going wrong.

Thanks.

**Comment by mitchellhenke** [comment]
@nbw thanks for opening an issue!

I have made some preliminary changes in the README to hopefully make it clearer how to get Sentry set up quickly.  

To address your present issue, what is your configuration?
