### ISSUE TITLE
Unreachable/misconfigured Sentry hangs the Elixir app

### ISSUE THREAD

**Issue by dkulchenko** [getsentry/sentry-elixir#371]
### Environment

* Elixir version (elixir -v): 1.9.1
* Erlang/OTP version (erl): 22
* Sentry version (mix deps): 7.2.0
* Operating system: macOS 10.13

### Description

If Sentry is misconfigured or otherwise can't reach the API, and is configured to use the Logger backend, any Logger usage in the app will hang indefinitely after a certain number of attempted logged messages.

### Expected Behavior

The app continues to work and logger messages are dropped or otherwise properly handled when Sentry is misconfigured/unreachable.

### Actual Behavior

The app hangs indefinitely on any Logger call after a number of failures.

### Steps to Reproduce

See https://github.com/dkulchenko/sentrytestcase. This is a basic Phoenix app configured with `mix phx.new`, but I've added a task supervisor to the supervision tree, added sentry, and set up the logger backend in application.ex.

From within this app, if you run `mix run test.exs`, the output will be:

```
processing item 1
processing item 2
processing item 3
processing item 4
processing item 5
processing item 6
processing item 7
processing item 8
processing item 9
processing item 10
processing item 11
processing item 12
processing item 13
processing item 14
processing item 15
processing item 16
processing item 17
processing item 18
processing item 19
processing item 20
processing item 21
```

and then hangs indefinitely. If the Sentry logger backend is removed, the test case processes all 1000 items as expected.

Note that I haven't configured Sentry at all in config.exs, but I'm guessing this would happen as well if it was properly configured but the API was unreachable/down.

**Comment by mitchellhenke** [comment]
@dkulchenko thanks for opening an issue! I've identified the cause and am working on a fix.

**Comment by dkulchenko** [comment]
Thanks @mitchellhenke :)

**Comment by mitchellhenke** [comment]
@dkulchenko absolutely, and thank you for discovering the issue!
