### ISSUE TITLE
(Plug.Conn.NotSentError) a response was neither set nor sent from the connection not sent to sentry

### ISSUE THREAD

**Issue by cdvv7788** [getsentry/sentry-elixir#373]
### Environment

* Elixir version (elixir -v): 1.9.4
* Erlang/OTP version (erl): 22
* Sentry version (mix deps): 7.2.0
* Operating system: Ubuntu 18.04

### Description
When getting a `Plug.Conn.NotSentError` an issue in sentry is not being created.

### Expected Behavior
An issue should be created in sentry

### Actual Behavior
Error is in my logs, but not in sentry

### Steps to Reproduce
From any controller, don't return a response. When you try to access it you will get:
```
20:04:46.860 [error] #PID<0.2286.0> running MyApp.Endpoint (connection #PID<0.2285.0>, stream id 1) terminated
Server: myapp.something:80 (http)
Request: GET /
** (exit) an exception was raised:
    ** (Plug.Conn.NotSentError) a response was neither set nor sent from the connection
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:76: Phoenix.Endpoint.Cowboy2Handler.maybe_send/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:43: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy) /myapp/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /myapp/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy) /myapp/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by mitchellhenke** [comment]
@cdvv7788 thanks for opening an issue!

I've attempted to reproduce in a fresh Phoenix repo [here](https://github.com/mitchellhenke/SentryNotSentError), with my attempted minimal changes being: https://github.com/mitchellhenke/SentryNotSentError/compare/e1a39f133032342639eed0784acaefd3574ede01...master

With those changes, I'm unable to reproduce and am receiving Sentry errors when hitting the route that doesn't return. Is there something else I may be missing?

**Comment by cdvv7788** [comment]
@mitchellhenke I checked again and it seems it was an issue with env variables. Sorry for wasting your time, closing. Thanks.

**Comment by mitchellhenke** [comment]
@cdvv7788 no worries, I appreciate you taking the time to create an issue 🙂
