### ISSUE TITLE
Sentry.LogggerBackend crashes when a genserver call times out

### ISSUE THREAD

**Issue by chad-g-adams** [getsentry/sentry-elixir#380]
### Environment

* Elixir version (elixir -v): Elixir 1.9.4 (compiled with Erlang/OTP 21)
* Erlang/OTP version (erl): Erlang/OTP 22 [erts-10.5.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
* Sentry version (mix deps): 7.2.1
* Operating system: Ubuntu

### Description

Sentry.LoggerBackend crashes when a timeout is encountered on a GenServer call()

The following is a snippet from my logs. 

* A request arrives and the server times out handling it. Then Sentry is seen to crash
```
Request: POST /graphql
** (exit) exited in: GenServer.call(Shift.GenServer, {:get_shift_segments, %{:__absinthe_plug__ => %{uploads: %{}}, :pubsub => MyApp.Endpoint, :request_id => "FeGPuzwNBAzjOnIAACAk"}}, 10000)
    ** (EXIT) time out
[error] :gen_event handler Sentry.LoggerBackend installed in Logger terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {GenServer, :call, [Shift.GenServer, {:get_shift_segments, %{:__absinthe_plug__ => %{uploads: %{}}, :pubsub => MyApp.Endpoint, :request_id => "FeGPuzwNBAzjOnIAACAk"}}, 10000]} of type Tuple. This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.PrepareStream, DBConnection.Stream, Timex.Interval, Stream, Range, Date.Range, HashDict, GenEvent.Stream, List, HashSet, File.Stream, IO.Stream, Map, Function, MapSet
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:366: Enum.any?/2
    (sentry) lib/sentry/logger_backend.ex:82: Sentry.LoggerBackend.handle_event/2
    (stdlib) gen_event.erl:577: :gen_event.server_update/4
    (stdlib) gen_event.erl:559: :gen_event.server_notify/4
    (stdlib) gen_event.erl:300: :gen_event.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

I put in an IO inspect in logger_backend.ex at handle_event/2 to see what the "meta" variable holds:

```
"Got meta [crash_reason: {:timeout, {GenServer, :call, [Shift.GenServer, {:get_shift_segments, %{:__absinthe_plug__ => %{uploads: %{}}, :pubsub => MyApp.Endpoint, :request_id => \"FeGPuwNVo-wbA-MAACKh\"}, 10000]}}, pid: #PID<0.1378.0>]"
```

### Expected Behavior

No crashing

### Actual Behavior

logger backend has problems with this case and crashes

### Steps to Reproduce

* A GenServer.call() times out

**Comment by mitchellhenke** [comment]
@chad-g-adams thanks for opening an issue, I'll take a look into this tomorrow!

**Comment by mitchellhenke** [comment]
@chad-g-adams Using your Elixir/Erlang versions, I unfortunately wasn't able to reproduce.

I'm seeing a message in the shape of:

```
  crash_reason: {{:timeout,
    {GenServer, :call, [#PID<0.302.0>, {:sleep, 20}, 1]}},
   [
     {GenServer, :call, 3, [file: 'lib/gen_server.ex', line: 1009]},
     {Task.Supervised, :invoke_mfa, 2,
      [file: 'lib/task/supervised.ex', line: 90]},
     {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}
   ]},
  pid: #PID<0.305.0>
```

I've also written a passing test case here: https://github.com/getsentry/sentry-elixir/pull/new/timeout-test

I'll probably explore making sure the second element in the tuple is a list, but I'm curious on how you're getting that. Do you have anything else going on that could impact this?

**Comment by chad-g-adams** [comment]
Thanks for the quick response! Interesting... My case looks similar to your GenServer call, with the only difference being my pid going into the call() is a module name. (I doubt that would make a difference). 

I am running as part of a larger Phoenix/Absinthe application, so the caller is a process provided by the framework in the context of handling a graphql request. I have confirmed it is definitely the GenServer.call timeout that is throwing an `exit` and I have no `catch` statements in my app so it is being handled out of my code. I suppose it's quite likely Absinthe and/or Phoenix are catching process crashes and perhaps they are also modifying the crash reason somehow, but this is just speculation on my part..

**Comment by mitchellhenke** [comment]
I've opened #381 to at least avoid the crash, but I'm still not sure how best to proceed with the error. It's in the format of an MFA tuple, but it's odd and I can't see how that would happen.

Typically these logs are coming from Erlang and are then translated by Elixir (example: https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger/translator.ex#L405). The docs even state `:crash_reason` should be a two element tuple with the second element being a stacktrace: https://hexdocs.pm/logger/Logger.html#module-metadata.

Do you have any Logger translators installed that could be modifying the metadata?

**Comment by chad-g-adams** [comment]
Hi @mitchellhenke, I have not installed any translators. Looking in my deps, the only reference to "add_translator" is found in `plug_cowboy` (which is a library used by Phoenix but I have not set any custom configuration for it)

**Comment by mitchellhenke** [comment]
Hm, thanks for checking. I'm not sure what else could be causing this.

It seems unlikely, and not being able to reproduce makes it difficult, but it's possible this is a bug in Erlang/Elixir.

Was the Erlang or Elixir version updated recently for the application?

**Comment by chad-g-adams** [comment]
We always tend to run with the latest available version so it's possible there was a recent upgrade to a new minor release.  I just tried rolling all the way back to elixir 1.8 and was still able to reproduce it with the following versions:

```
$ elixir -v
Erlang/OTP 22 [erts-10.6.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.8.2 (compiled with Erlang/OTP 20)
```

**Comment by mitchellhenke** [comment]
Would you be able to pull down my branch [here](https://github.com/getsentry/sentry-elixir/pull/new/timeout-test) and run `mix test` in the same environment?

I've installed the same versions as best as I can tell (Elixir 1.8.2 compiled on OTP 20.3 running on OTP 22.2.1) and the test passes.

```
elixir -v
Erlang/OTP 22 [erts-10.6.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.2 (compiled with Erlang/OTP 20)
```

**Comment by alizain** [comment]
@mitchellhenke I'm experiencing a similar issue, I've created a [minimal Phoenix app](https://github.com/alizain/sentry_genserver_failure) with Sentry that reproduces the error.

PS. The only difference between my repro and what @chad-g-adams experienced is that it's a `MatchError` inside a GenServer call that triggers the initial failure, instead of a timeout.

Check out [this particular commit](https://github.com/alizain/sentry_genserver_failure/commit/46a2cb3e4e81319988c717d49423d3e3615be6d3) to see everything I changed on top of the stock app that Phoenix generates

**Comment by mitchellhenke** [comment]
@alizain thank you so much, this helps me reproduce and I can take a further look into the issue!

**Comment by mitchellhenke** [comment]
Thanks for the patience and information. After taking some time to look into this, it appears to be due to how Cowboy formats these kinds of errors.

The crashed process itself reports a `:crash_reason` of:

```elixir
{%MatchError{term: 1},
 [
   {SentryGenserverFailure.Stack, :handle_call, 3,
    [file: 'lib/sentry_genserver_failure/stack.ex', line: 24]},
   {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]},
   {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]},
   {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}
 ]}
```

which is the expected `{reason,  stacktrace}` format.
The cowboy process also crashes, but the `:crash_reason` is:

```
{{{:badmatch, 1},
  [
    {SentryGenserverFailure.Stack, :handle_call, 3,
     [file: 'lib/sentry_genserver_failure/stack.ex', line: 24]},
    {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]},
    {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]},
    {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}
  ]}, {GenServer, :call, [SentryGenserverFailure.Stack, {:push, 1}, 5000]}}
```

which is `{{error, stacktrace}, {module, function, arguments}` and breaks the expectations.

The reason is mostly the same as the original crash, so I'll likely add the changes in #381 with a special case to handle this format and push a release.

**Comment by alizain** [comment]
Awesome, thanks so much @mitchellhenke!
