### ISSUE TITLE
`Sentry.LoggerBackend` should hook to the Erlang's Logger

### ISSUE THREAD

**Issue by hauleth** [getsentry/sentry-elixir#384]
### Environment

* Elixir version (elixir -v): 1.10
* Erlang/OTP version (erl): 21+
* Sentry version (mix deps): doesn't matter
* Operating system: doesn't matter

### Description

Currently `Sentry.LoggerBackend` hooks to the Elixir's logger which can be defined to ignore the OTP and SASL messages.

### Expected Behavior

Error when configuration is like:

```elixir
config :logger,
  handle_otp_reports: false,
  handle_sasl_reports: false
```

Should be handled by Sentry

### Actual Behavior

Errors will not be handled

### Steps to Reproduce

Just fire error with above options set (it need to be set before `:logger` application will be started.

---

In addition to above, it will be easier to control everything as `:sentry` application can define `:logger` field in application env and then it will be possible to attach it by:

```
:logger.add_handlers(:sentry)
```

**Comment by hauleth** [comment]
Just in case, I will try to handle that in my spare time, I just created it to remember about it.

BTW There are plans to deprecate the "legacy backends" in future, so it is better to do the transition as soon as possible.

**Comment by mitchellhenke** [comment]
I think the transition will be relatively straightforward, assuming the structure of events remains similar. A log event from Erlang's new logger looks relatively similar to the format Sentry uses no:

```elixir
  msg: {:report,
   %{
     label: {:proc_lib, :crash},
     report: [
       [
         initial_call: {:erl_eval, :"-expr/5-fun-3-", []},
         pid: #PID<0.550.0>,
         registered_name: [],
         error_info: {:error, %RuntimeError{message: "raise"},
          [
            {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 678]},
            {Task.Supervised, :invoke_mfa, 2,
             [file: 'lib/task/supervised.ex', line: 90]},
            {Task.Supervised, :reply, 5,
             [file: 'lib/task/supervised.ex', line: 35]},
            {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}
          ]},
         ancestors: [#PID<0.539.0>, #PID<0.81.0>],
         message_queue_len: 0,
         messages: [],
         links: [#PID<0.539.0>],
         dictionary: ["$callers": [#PID<0.539.0>]],
         trap_exit: false,
         status: :running,
         heap_size: 17731,
         stack_size: 27,
         reductions: 12126
       ],
```
Do you know whether Logger translators will still play a role, or will they be deprecated as well?

**Comment by hauleth** [comment]
If the Elixir backends will be deprecated then the translators will play almost no role as well. However the plan is to have formatter defined that will do translation if needed. However I think that structured log is better as Sentry can format it on their own to format that suits Sentry the best.

Additionally it could be useful to translate it to Erlang for example, so Sentry could be used in pure Erlang applications as well.

**Comment by josevalim** [comment]
> BTW There are plans to deprecate the "legacy backends" in future, so it is better to do the transition as soon as possible.

To be clear, it will likely take quite some time for the deprecation to happen. Erlang backends do not support overload protection yet, so we can't deprecate Elixir backends right now. And once Erlang introduces the functionality we need, we need to wait until that Erlang version becomes the minimum required OTP version in Elixir, which usually takes 2 years. So we are at looking at 2 or 3 years from now at best.

**Comment by mitchellhenke** [comment]
Given the timeframe, I'm going to close this issue for now. I definitely think we will do this though 🙂

**Comment by staring-frog** [comment]
@mitchellhenke Could you clarify on what's the situation regarding handling Erlang logs. I see there were `Sentry.Logger` for hooking up to Erlang error_logger. But now it's gone. Can `Sentry.LoggerBackend` handle Erlang events now if setup according to README?

**Comment by josevalim** [comment]
@staring-frog it will capture log messages if you set the capture_log_messages flag as shown here: https://hexdocs.pm/sentry/Sentry.LoggerBackend.html#module-configuration

**Comment by staring-frog** [comment]
Thanks!
