### ISSUE TITLE
Invalid port in HTTPS request urls (Heroku)

### ISSUE THREAD

**Issue by smetana** [getsentry/sentry-elixir#392]
### Environment

* Elixir version (elixir -v): 1.9.4
* Erlang/OTP version (erl): 22.2.1
* Sentry version (mix deps): 7.2.4
* Operating system: Ubuntu (Heroku)

### Description
In Phoenix app configured to serve HTTPS requests on Heroku request url port is invalid in payloads

E.g. Phoenix configured to run on Heroku:
```
  http: [:inet6, port: System.get_env("PORT")],
  url: [ scheme: "https", host: "myapp.com", port: 443 ]
```
### Expected Behavior
to see request urls in payloads as https://myapp.com or https://myapp.com:443

### Actual Behavior
request url is https://myapp.com:80

I have made small PR  #391 to fix the issue

**Comment by mitchellhenke** [comment]
Closed in #391 

Thank you again!
