### ISSUE TITLE
Document how to setup sentry with distillery release

### ISSUE THREAD

**Issue by tychota** [getsentry/sentry-elixir#394]
### Environment

On build env:

* Elixir version (elixir -v): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Erlang/OTP version (erl): Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]
* Sentry version (mix deps): 7.2.4
* Operating system: debian 10.2

On production env:

* Elixir version (elixir -v): part of ERTS
* Erlang/OTP version (erl): part of ERTS
* Sentry version (mix deps): part of ERTS
* Operating system: debian 10.2

### Description

- I deployed a phoenix app with distillery: `MIX_ENV=prod mix do phx.digest, distillery.release --env=prod --no-tar`

```elixir
environment :prod do
  set(include_erts: true)
  set(include_src: false)
  set(cookie: :"<redacted>")
  set(vm_args: "rel/vm.args")

  set(
    config_providers: [
      {Distillery.Releases.Config.Providers.Elixir, ["${RELEASE_ROOT_DIR}/etc/config.exs"]}
    ]
  )

  set(
    overlays: [
      {:copy, "rel/config/runtime_config.exs", "etc/config.exs"}
    ]
  )
end
```
(extract of release conf)

```sentry_dsn =
  System.get_env("CADENCE_SENTRY_DSN") ||
    raise """
    environment variable CADENCE_SENTRY_DSN is missing.
    """

config :sentry,
  dsn: sentry_dsn,
  environment_name: :prod,
  enable_source_code_context: true,
  root_source_code_path: File.cwd!(),
  tags: %{
    env: "production"
  },
  included_environments: [:prod]
```

### Expected Behavior

Proper bug report with source.

Conceptually on another project (python)

![image](https://user-images.githubusercontent.com/13785185/80873664-72707600-8cba-11ea-8b45-b3a504e2d544.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/13785185/80873619-3b9a6000-8cba-11ea-9d93-d12af88d08f4.png)

### Steps to Reproduce

-

**Comment by mitchellhenke** [comment]
Thanks for the detailed issue! I'll take a look into this and try to come up with some docs that address this use case.

**Comment by mitchellhenke** [comment]
I've tried to reproduce this with a distillery release, but I'm able to receive source code within an event

![image](https://user-images.githubusercontent.com/1430443/81329847-c1286200-9064-11ea-8133-ef1893c78da6.png)

https://hexdocs.pm/sentry/Sentry.Sources.html#module-configuration describes some of the potential issues and configurations around this feature.

I published my repro repo here: https://github.com/mitchellhenke/SentryDistilleryTest. If you are able to take a look and see if there's anything that differentiates our setups, it'd be greatly appreciated so I can track down anything that's going wrong.

**Comment by tychota** [comment]
I had an unconfirmed idea that changing this https://github.com/mitchellhenke/SentryDistilleryTest/blob/fccaa5764b02b2564310763e2f73373b718adea6/rel/config.exs#L39
to true might fix it.

I've deploy it to my server but didn't get any new sentry report so far to confirm or infirm this idea.

Which is weird is that you have it set to true.
Can you confirm me that:
1) you did the release in MIX_ENV=prod ?
2) maybe you copy the tar and run it outside of the source (as my production server is different from the build server).

If you reproduce the bug with the prod config or so, I can go ahead an open a PR to improve the documentation.

**Comment by mitchellhenke** [comment]
I don't think Sentry should be affected by changing the `include_src` config as it handles the source on its own.

I ran the release with the options above, `MIX_ENV=prod mix do phx.digest, distillery.release --env=prod --no-tar`. I tried copying it into a separate folder, and was able receive events with source code context.

Could you try force recompiling as described here? https://hexdocs.pm/sentry/Sentry.Sources.html#module-source-code-storage

**Comment by tychota** [comment]
I'm pretty sure I have still the bug

![image](https://user-images.githubusercontent.com/13785185/82097658-9d6bb880-9703-11ea-901b-0c5bff3732b9.png)

I will clean up completely the build server and the previous releases and redeploy to be 100% sure.

If that is still the case I will try to compare your Minimal repro with my codebase.

**Comment by mitchellhenke** [comment]
Yep, it looks like it. Definitely let me know if there’s some config or otherwise I should try, will try to get to the bottom of it.

**Comment by tychota** [comment]
I did found the issue and god, it was dumb. Thanks a lot for your repro.

![image](https://user-images.githubusercontent.com/13785185/82193925-5a256b80-98f6-11ea-8d96-63067363b842.png)

So I got in `_rel/config/config.exs`:

```
config :sentry,
  dsn: sentry_dsn,
  environment_name: :prod,
  enable_source_code_context: true,
  root_source_code_path: File.cwd!(),
  tags: %{
    env: "production"
  },
  included_environments: [:prod],
  release: "0.0.0-development"
```

but this is only executed in runtime, not buildtime.

In `config.exs`, I discover with horror a:

```elixir
config :sentry,
  dsn: "https://redacted@redacted.ingest.sentry.io/redacted",
  included_environments: [:prod],
  environment_name: Mix.env()
```

The fix was:

```diff
config :sentry,
  dsn: "https://redacted@redacted.ingest.sentry.io/redacted",
+  enable_source_code_context: true,
+  root_source_code_path: File.cwd!(),
  included_environments: [:prod],
  environment_name: Mix.env()
```

For the next steps I think we can still work a bit on the doc explaining that both buildtime and runtime config are needed.

**Comment by mitchellhenke** [comment]
Ah, good catch. I would be very glad to have any improvements to the docs to make this clearer.

**Comment by mitchellhenke** [comment]
Note about runtime configuration being necessary was added in https://github.com/getsentry/sentry-elixir/commit/40cfa58bd2eb1d7dcfcce6579671ca16c94b9672
