### ISSUE TITLE
Sentry suppressing exceptions even for excluded environments

### ISSUE THREAD

**Issue by dfalling** [getsentry/sentry-elixir#396]
### Environment

* Elixir version (elixir -v): 1.9.0
* Erlang/OTP version (erl): 22
* Sentry version (mix deps): 7.2.4
* Operating system: macOS 10.15.5
* Is this an umbrella application?: No
* Release type (Distillery, mix release, Mix, etc.): Distillery

### Description

`use Sentry.Phoenix.Endpoint` is suppressing all exceptions from appearing in the console, even in environments not matching `included_environments`.

### Expected Behavior

When the `environment_name` isn't included in `included_environments`, the exception should display in the logs.

### Actual Behavior

The entire exception is missing.  The only indication that there was a failure is a debug log about the 500 response.

### Steps to Reproduce

```elixir
config :sentry,
  dsn: "REDACTED",
  environment_name: Mix.env(),
  included_environments: [:prod, :staging]
```

The weird thing is I have a nearly identical setup in another project and it works fine.  I can't figure out why Sentry's suppressing exceptions for this project.

Any first steps I can take to troubleshoot this?

**Comment by mitchellhenke** [comment]
@dfalling thanks for opening an issue!

Like your other project, I am getting stacktraces and full log output in a new project: https://github.com/mitchellhenke/phoenix_sentry_example

This issue reminds me of OTP/SASL error handler related stuff, but I'm not positive. Also worth noting the 500 response log that's appearing is from within Phoenix itself, while the missing log with the stackstace is in the Ranch/Cowboy domain.

A couple questions if you don't mind:
- What versions of Phoenix, Plug and plug_cowboy are you on?
- Is there any difference in the Logger config or dependencies around logging?

**Comment by dfalling** [comment]
Thanks for the quick response @mitchellhenke!

My other dependencies:
phoenix: 1.4.17
plug: 1.10.1
plug_cowboy: 2.1.3

For local development the logging situation in both of my projects is the same- just using the default logger at :debug level.  My problematic project has a lot more plugs involved though- namely Absinthe.  Just commenting out `use Sentry.Phoenix.Endpoint` lets the exceptions through as expected.

I suspect you're right though that it's a combination of Sentry with something else, since I'm using the same setup and version successfully.

**Comment by mitchellhenke** [comment]
Thanks for the details. I've tried to reproduce with those versions, but it indeed must be something else conflicting with `Sentry.Phoenix.Endpoint`.

If you have any hunches on where I can look further, or a way to reproduce, I will definitely do that. Otherwise, I'm exploring options to report errors within the Endpoint stack without having to `use Sentry.Phoenix.Endpoint`.

**Comment by dfalling** [comment]
I spent the better part of today trying to troubleshoot this further without any luck.  I used `IO.inspect` and `Logger` at various spots inside the `catch`.  I could consistently log near the beginning of the code, but as I got deeper / further along, the logs wouldn't make it through.

```elixir
  def capture_exception(exception, opts \\ []) do
    IO.puts("test")
    IO.inspect(opts)
    IO.puts("test 2")
    filter_module = Config.filter()
```

Only `test` above would print.  It really has me stumped- it feels like there's a limit to how much can be displayed on the console.

**Comment by dfalling** [comment]
So we figured this out, but I sadly don't understand it... Our frontend locally [proxies requests](https://github.com/chimurai/http-proxy-middleware) to our Phoenix backend.  Using this proxy + Sentry's endpoint caused our exceptions to be hidden in Elixir's console.  Switching from proxying requests to simply specifying the API URL explicitly solved the issue.  I'm confused how a separate proxy running on port 3000 would cause this, but we're all good now!

**Comment by mitchellhenke** [comment]
hmm, that is interesting and will keep in mind in the future for similar issues. I'm not sure what would cause that, but appreciate the follow up.
