### ISSUE TITLE
IO.inspect call in logger backend

### ISSUE THREAD

**Issue by hfjallemark** [getsentry/sentry-elixir#405]
### Environment

* Elixir version (elixir -v): 1.10.2
* Erlang/OTP version (erl): 22
* Sentry version (mix deps): 8.0.0-rc.0
* Operating system: macOS
* Is this an umbrella application?: No
### Description

There's an `IO.inspect` call in logger backend on hex.pm but not in the 8.0.0-rc.0 tag/release here on Github. Not sure how it slipped in but it screws up our production logs.

Here's the hex diff: https://diff.hex.pm/diff/sentry/7.2.4..8.0.0-rc.0#4149588--102

**Comment by mitchellhenke** [comment]
Thank you a bunch for letting me know and being willing to test the release candidate. I'm really sorry about the IO.inspect logs in there. I've released `8.0.0-rc.1` that should fix it.

The inspect logs weren't committed, but hex builds are from local files (and I forgot to stash some changes made during testing 🤦🏻‍♂️), so they ended up in the build.

**Comment by hfjallemark** [comment]
That's what I suspected! Thanks for the new release.
