### ISSUE TITLE
Allow configuration to set maximum number of breadcrumbs.

### ISSUE THREAD

**Issue by jfmyers9** [getsentry/sentry-elixir#407]
### Environment

* Sentry version (mix deps): `7.2.0`
* Operating system: macOS, Linux

### Description

Sometimes for long lived processes, too many breadcrumbs are added to a sentry event. When posting the event, the client fails if the body is too large. Similar to this issue: https://forum.sentry.io/t/http-error-413-request-entity-too-large/1942.

Is it possible to get configuration to limit the number of breadcrumbs that sentry will attempt to send? Something akin to `max_breadcrumbs` that is present in the python sentry library?

**Comment by mitchellhenke** [comment]
Yep, makes total sense, can definitely add this. Thanks for opening an issue!

**Comment by jfmyers9** [comment]
@mitchellhenke Is this something that you think could be released on the `7.x.x` line? Or will this only be released when `8.x.x` comes out?

**Comment by mitchellhenke** [comment]
@jfmyers9 I've just released it in `8.0.1`. I can backport it if needed though 🙂

**Comment by jfmyers9** [comment]
If you could backport it, that would be very much appreciated. Thanks for the help.

**Comment by mitchellhenke** [comment]
Sure thing, released in 7.2.5 🙂
