### ISSUE TITLE
Can't use local function scrub_params/1 inside Endpoint

### ISSUE THREAD

**Issue by dmorneau** [getsentry/sentry-elixir#408]
### Environment

* Elixir version (elixir -v): 1.10.4
* Erlang/OTP version (erl): 23
* Sentry version (mix deps): 8.0.0-rc2
* Operating system: macOS
* Is this an umbrella application?: no
* Release type (Distillery, mix release, Mix, etc.): mix release

### Description

This sample code from the 8.0.0-rc2 doc causes a compile error if I try to use it in my app:

```
use Sentry.PlugContext, body_scrubber: &scrub_params/1
```

...even though there is a scrub_params/1 function defined within the module. This used to work fine when using `Sentry.Plug` within the Router, with locally defined functions.

### Expected Behavior

If I define a local function inside the Endpoint module, then pass it to `Sentry.PlugContext`, I would expect it to compile fine.

### Actual Behavior

```
== Compilation error in file lib/myapp_web/endpoint.ex ==
** (CompileError) lib/myapp_web/endpoint.ex:68: undefined function scrub_params/1
    (stdlib 3.13) lists.erl:1354: :lists.mapfoldl/3
    (stdlib 3.13) lists.erl:1355: :lists.mapfoldl/3
    (stdlib 3.13) lists.erl:1354: :lists.mapfoldl/3
    (stdlib 3.13) lists.erl:1355: :lists.mapfoldl/3
    (stdlib 3.13) lists.erl:1354: :lists.mapfoldl/3
    (stdlib 3.13) lists.erl:1355: :lists.mapfoldl/3
    (elixir 1.10.4) expanding macro: Kernel.@/1
    lib/myapp_web/endpoint.ex:66: MyAppWeb.Endpoint (module)
    (plug 1.10.3) expanding macro: Plug.Builder.plug/2
```

### Steps to Reproduce

In a Phoenix app, define this function inside the endpoint module:

```
  def scrub_params(conn) do
    Enum.into(conn.params, %{})
    |> Map.drop(["secret"])
  end
```

Then somewhere else in the endpoint use it in PlugContext:

```
  plug Sentry.PlugContext, body_scrubber: &scrub_params/1
```

It doesn't matter if the function is defined before or after the plug.

### Workaround

Using a tuple works:

```
  plug Sentry.PlugContext, body_scrubber: {__MODULE__, :scrub_params}
```

**Comment by mitchellhenke** [comment]
Thanks for reporting. I've updated and re-published the docs for rc2 and plan on doing a general release next week 🙂
