### ISSUE TITLE
Upgrade guide: mention router changes in 8.x

### ISSUE THREAD

**Issue by dmorneau** [getsentry/sentry-elixir#409]
In a Phoenix app with Sentry 7.x, the router would typically contain this:

```
  use MyAppWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug
```

When upgrading to 8.x, I removed Sentry.Plug, but I didn't realize that Plug.ErrorHandler was tied to it, so I left it in. This caused the app behaviour to change: when an exception like Ecto.InvalidChangesetError is thrown, the app started responding using Plug.ErrorHandler's default handling ("Something went wrong"), rather going through the ErrorView which renders a proper JSON response.

It could be good to mention removing both these lines in the upgrade guide.

**Comment by mitchellhenke** [comment]
Thank you a bunch, I've added detail for this to the guide! 💖
