### ISSUE TITLE
Logger metadata is missing in some calls

### ISSUE THREAD

**Issue by chulkilee** [getsentry/sentry-elixir#411]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4 (compiled with Erlang/OTP 23)
* Erlang/OTP version (erl): 23.0.2
* Sentry version (mix deps): 8.0.0
* Operating system: macOS
* Is this an umbrella application?: no
* Release type (Distillery, mix release, Mix, etc.): mix

### Description

There are several ways sentry events can be triggered in phoenix controller

- Directly 

```elixir
# config

config :logger, Sentry.LoggerBackend, capture_log_messages: true, metadata: [:key1]

# phoenix controller

  def show(conn, _params) do
    Logger.metadata(key1: "foo")

    Sentry.capture_message("from Sentry.capture_message")
    Logger.error("from Logger.error")
    raise "from raise"
  end
```

### Expected Behavior

All reported sentry events have the same metadata in `extra` field

### Actual Behavior

- ✅  Logger.error: has it 
- ❌ raise: does not have it
- ❌ Sentry.capture_message: does not have it

### Steps to Reproduce

See the above code.

**Comment by mitchellhenke** [comment]
Thank you for opening an issue!

This is operating as expected (for now anyway). The metadata configured within `Sentry.LoggerBackend` will only appear for messages received by the `Logger` system.

`Sentry.capture_message` and the `raise` captured by `Sentry.PlugCapture` are outside of `Logger`, so they do not get the metadata. I understand how this is not clear, and there is potential for confusion between `Sentry.Context` and the metadata at hand.

It's possible to expand this functionality outside of `Sentry.LoggerBackend`, but I'm not sure that I want to take that step yet as it would require moving some of that configuration around.

I'll make the documentation clearer, but outside of that, is there something else that could help this issue?

**Comment by chulkilee** [comment]
Thanks a lot for the clarification. Yes, that was my guess as it's configuration for `Sentry.LoggerBackend` logger backend.

---

**For documentation** - I think each section is great, but from github README it's a little bit tricky to see the nested contents (e.g. is it about plug or logger?). Probably better to put most module-level info to ExDoc module docs, while README can refer them. Check out [ecto_sql](https://github.com/elixir-ecto/ecto_sql) or [tesla](https://github.com/teamon/tesla).

---

> It's possible to expand this functionality outside of Sentry.LoggerBackend, but I'm not sure that I want to take that step yet as it would require moving some of that configuration around.

Hm.. I think it would be nice to pick up logger metadata consistently - not for logger. Maybe I'm misusing logger metadata though... so I'm not 100% sure.

If using logger metadata outside Logger backend seems fair... then we may add configuration something like this:

```elixir
config :sentry, Sentry.Context, logger_metadata: [:key1]
```

By doing that, I don't need to call `Sentry.Context.set_extra_context/1` in all places. What do you think? If it sounds good, let's create separate issue for this..

**Comment by mitchellhenke** [comment]
Sentry's integration with Logger has grown as Logger has improved, so I doubt that you are misusing Logger metadata 🙂

I'm wary of adding more config, and I think using `before_send_event` to add context to events from arbitrary sources may be able to serve this for now. As an example:

```elixir
defmodule MyApp.Sentry do
  def before_send(event) do
    metadata = Map.new(Logger.metadata)
    %{event | extra: Map.merge(event.extra, metadata)}
  end
end


# config.exs
config :sentry,
  before_send_event: {MyApp.Sentry, :before_send},
```

Would something like that work?

**Comment by chulkilee** [comment]
@mitchellhenke I like that idea in general, but I'm still not 100% sure whether each library implementing logger should have similar mechanism, or Elixir/Erlang logger should provide a building block to make something like "logging pipeline".

```elixir
config :logger, Sentry.LoggerBackend, pipeline: [MyApp.LoggerMetadataToSentry]
```

**Comment by mitchellhenke** [comment]
My understanding is that Logger metadata isn't necessarily intended to be data subscription where N processes would be notified of a change, so I'm not sure if we will see something like that. Logger backends fit more into that as they'll receive every log message with associated metadata. The metadata is also ultimately stored in the process dictionary, which has its own set of limitations.

I think the flexibility to be able to mutate or fetch Logger metadata is sufficient as it allows non-Logger functionality to hook into it where needed. A fuller solution for Sentry would be its own storage mechanism, perhaps in a kind of registry that works alongside Logger metadata, but I'm not keen on that complexity at the moment.

**Comment by whatyouhide** [comment]
I'm closing this one, as I think using `Logger` metadata in `Sentry.capture_exception/2` and similar calls is "magic" and might lead to unexpected results for folks not relying on it. Also, it's been 3 years 😄 If we still want to discuss this, happy to continue to talk here in this issue! 💟
