### ISSUE TITLE
Feature Request: Allow setting of scrubbed parameter lists et al by configuration

### ISSUE THREAD

**Issue by aselder** [getsentry/sentry-elixir#412]
Right now to add parameters, headers, etc to the list of things to be scrubbed requires implementing a whole module that duplicates a good chunk of the functionality of Sentry.Plug. Being able to specify you complete custom logic is great, but overkill for the 99% use case, which is just adding values to the lists to be scrubbed.

It would be great if instead of a hard coded list, the list of params to be scrubbed could be read from a configuration value and then allowing the option to completely override the logic if really needed.

**Comment by aselder** [comment]
While I've got the library forked, I'll go ahead a whip up a PR for this one as well

**Comment by mitchellhenke** [comment]
Thanks for opening an issue!

My main concern is whether adding a new way to configure is worth the added complexity, and the 99% use case is intended to be covered by the defaults that exist.  If there were edge cases to cover or potential pitfalls that the library would be able to help users with, I'd be more open to it. Right now I'm slightly leaning against this, as the function on the user side would be relatively small, ex:

```elixir
defmodule MyApp.Sentry do
  def scrub_params(conn) do
    Map.drop(conn.params, ["secret"])
  end

  # ...
end
```

**Comment by aselder** [comment]
Mitchell,

That’s what I initially did, but they had to end up copying over all the recursive code to scrub those parameters inside nested structures as well.

That’s what ended up leading me to file this issue.

**Comment by aselder** [comment]
Here's the code I had to write to add three parameters to the list of things to be scrubbed:

```
defmodule ApiV1.Stats.Sentry do
  @moduledoc false

  @params_to_drop ~w(
    currentPassword
    newPassword
    newPasswordConfirmation

  )

  @scrubbed_value "*********"

  def scrub_params(conn) do
    # Makes use of the default body_scrubber to avoid sending password
    # and credit card information in plain text.
    conn
    |> Sentry.Plug.default_body_scrubber()
    |> scrub_map()
  end

  defp scrub_map(map) do
    Enum.into(map, %{}, fn {key, value} ->
      value =
        cond do
          Enum.member?(@params_to_drop, key) ->
            @scrubbed_value

          is_map(value) ->
            scrub_map(value)

          true ->
            value
        end

      {key, value}
    end)
  end
end
```

**Comment by mitchellhenke** [comment]
Oh, that is a bit more than I had remembered. Do you think it would be sufficient for me to refactor that and make it public as something like:

```elixir
  def scrub_map(map, scrubbed_keys, opts \\ []) do
    scrubbed_values_regular_expressions = Keyword.get(opts, :scrubbed_values_regular_expressions, [@credit_card_regex])
    scrubbed_value = Keyword.get(opts, :scrubbed_value, @scrubbed_value)

    Enum.into(map, %{}, fn {key, value} ->
      value =
        cond do
          Enum.member?(scrubbed_keys, key) ->
            scrubbed_value

          is_binary(value) && Enum.any?(scrubbed_values_regular_expressions, &Regex.match?(&1, value) ->
            scrubbed_value

          is_map(value) && Map.has_key?(value, :__struct__) ->
            Map.from_struct(value)
            |> scrub_map(scrubbed_keys, opts)

          is_map(value) ->
            scrub_map(value, scrubbed_keys, opts)

          true ->
            value
        end

      {key, value}
    end)
  end
```

Only intended as an example, didn't test/compile the code. It would allow keeping the configuration structure, but hopefully provide an easier path away from the current defaults.

**Comment by aselder** [comment]
That’s almost exactly the code that I was going to write :)

**Comment by sascha-wolf** [comment]
From where I'm standing the added complexity to make the scrubbing configurable would be negligible.

While the `scrub_map` function currently looks like this:

```elixir
defp scrub_map(map) do
    Enum.into(map, %{}, fn {key, value} ->
      value =
        cond do
          Enum.member?(@default_scrubbed_param_keys, key) ->
            @scrubbed_value

          is_binary(value) && Regex.match?(@credit_card_regex, value) ->
            @scrubbed_value

          is_map(value) && Map.has_key?(value, :__struct__) ->
            Map.from_struct(value)
            |> scrub_map()

          is_map(value) ->
            scrub_map(value)

          true ->
            value
        end

      {key, value}
    end)
  end
```

Making the keys and regular expression configurable might look like this:

```elixir
defp scrub_map(map) do
    scrubbed_keys = Application.get_env(:sentry, :scrubbed_keys, @default_scrubbed_param_keys)
    scrubbed_value_regex = Application.get_env(:sentry, :scrubbed_value_regex, @credit_card_regex)

    Enum.into(map, %{}, fn {key, value} ->
      value =
        cond do
          Enum.member?(scrubbed_keys, key) ->
            @scrubbed_value

          is_binary(value) && Regex.match?(scrubbed_value_regex, value) ->
            @scrubbed_value

          is_map(value) && Map.has_key?(value, :__struct__) ->
            Map.from_struct(value)
            |> scrub_map()

          is_map(value) ->
            scrub_map(value)

          true ->
            value
        end

      {key, value}
    end)
  end
```

With this in place users can go ahead and configure the scrubbing the "usual" configuration way:

```elixir
use Mix.Config

config :sentry,
  scrubbed_keys: ~w(password passwd secret mysupersecret),
  scrubbed_value_regex: ~r/my-weird-regex/
```
```

**Comment by mitchellhenke** [comment]
I do appreciate the simplification on the user implementation side.

The config would also likely be placed on the Plug rather than application.

**Comment by sascha-wolf** [comment]
> I do appreciate the simplification on the user implementation side.
> 
> The config would also likely be placed on the Plug rather than application.

Fair enough, the user can then opt themselves to load the values from the config and pass them to the plug, so not a lot would be lost there.

**Comment by mitchellhenke** [comment]
I’m open to that, but I think I’d rather see how #417 works out for a bit. If it’s too burdensome on the user still, converting the current default keys / regex into that structure would be straightforward.
