### ISSUE TITLE
Sentry getting error reports for non-500 errors from endpoint.ex

### ISSUE THREAD

**Issue by aselder** [getsentry/sentry-elixir#413]
### Environment

* Elixir version (elixir -v): 1.10.3
* Erlang/OTP version (erl): Erlang/OTP 23 [erts-11.0.2]
* Sentry version (mix deps): 7.2.4
* Operating system: Alpine Linux
* Is this an umbrella application?: yes
* Release type (Distillery, mix release, Mix, etc.): mix release

### Description
If an error is raised by a Plug in the endpoint file (outside the router), a report will be generated to Sentry even if that error does not result in a 500 Internal Server Error. For example, is Plug.Parser blows up due to garbage JSON, the response is properly sent back down the wire at 400 Bad Request

### Expected Behavior

No Sentry report will be generated because this is a handled error

### Actual Behavior

A Sentry report is generated

### Steps to Reproduce

1. Set up a Phoenix Endpoint with Sentry and a JSON endpoint.
2. Use curl to make a request with a garbage body.
3. Observe the request comes back with the proper 400 status code.
4. Find the error in Sentry.

**Comment by aselder** [comment]
Probably as simple as adding 

      `Plug.Parsers.RequestTooLarge`,
      `Plug.Parsers.BadEncodingError`,
      `Plug.Parsers.ParseError`,
      `Plug.Parsers.UnsupportedMediaTypeError`

to the default list of excluded params. I'll whip up a PR.

**Comment by mitchellhenke** [comment]
closed in #414
