### ISSUE TITLE
Read compile-time Mix dependencies in the host app, not the `:sentry` app

### ISSUE THREAD

**Issue by wingyplus** [getsentry/sentry-elixir#415]
This issue was previously titled: **Some of dependencies is missing in Packages section**

### Environment

* Elixir version (elixir -v): 1.10.3
* Erlang/OTP version (erl): 23
* Sentry version (mix deps): 8.0.0
* Operating system: macOS
* Is this an umbrella application?: No
* Release type (Distillery, mix release, Mix, etc.): mix release

### Description

When I testing capture exception with my application and self-hosted sentry version 9.1.2. I found that some dependencies is missing in `Packages` section in Sentry ui. This is my dependencies in `mix.exs`:

```elixir
defp deps do
    [
      {:phoenix, "~> 1.4.16"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_ecto, "~> 4.0"},
      {:ecto_sql, "~> 3.1"},
      {:myxql, ">= 0.0.0"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},
      {:httpoison, "~> 1.6"},
      {:absinthe, "~> 1.4"},
      {:absinthe_plug, "~> 1.4"},
      {:cors_plug, "~> 2.0"},
      {:nimble_csv, "~> 0.7"},
      {:tzdata, "~> 1.0.1"},
      {:timex, "~> 3.6"},
      {:logger_json, "~> 4.0"},
      {:cloak, "~> 1.0"},
      {:cloak_ecto, "~> 1.0"},
      {:ecto_enum, "~> 1.4"},
      {:credo, "~> 1.4", only: [:dev, :test], runtime: false},
      {:telemetry, "~> 0.4.1"},
      {:telemetry_poller, "~> 0.5.0"},
      {:telemetry_metrics, "~> 0.5.0"},
      {:telemetry_metrics_prometheus, "~> 0.5.0"},
      {:sentry, "~> 8.0"},
      {:dialyxir, "~> 1.0", only: [:dev], runtime: false}
    ]
end
```

### Expected Behavior
I expected to see all dependencies in `deps` function above. Omit `credo` and `dialyxir` is ok because it happens only `dev` and `test` env.

### Actual Behavior
![Screen Shot 2563-07-16 at 17 35 32](https://user-images.githubusercontent.com/484530/87661739-53e32c80-c78b-11ea-82cb-d39c2a6b6178.png)

Some of dependencies is missing, such as, phoenix, ecto, etc.

### Steps to Reproduce
I create a phoenix controller and raise no case cause matching exception to make it show on sentry ui.

**Comment by wingyplus** [comment]
I try to called `Sentry.Util.mix_deps()` to get dependencies at runtime. It returns:

```
[:absinthe, :cowboy, :ranch, :cors_plug, :plug_cowboy, :connection,
 :phoenix_pubsub, :combine, :ssl_verify_fun, :telemetry_metrics_prometheus_core,
 :db_connection, :myxql, :erlex, :mimerl, :nimble_csv, :dialyxir, :parse_trans,
 :logger_json, :mime, :ecto_sql, :cloak, :nimble_parsec, :timex, :ecto, :idna,
 :telemetry_metrics_prometheus, :hackney, :certifi, :tzdata, :credo, :jason,
 :plug, :sentry, :decimal, :telemetry, :metrics, :phoenix, :ecto_enum,
 :cloak_ecto, :httpoison, :cowlib, :phoenix_ecto, :plug_crypto,
 :telemetry_poller, :unicode_util_compat, :bunt, :absinthe_plug,
 :telemetry_metrics, :gettext]
```

**Comment by wingyplus** [comment]
I try to fix it by get mix deps at runtime (everytime it's call `create_event`). The result is the same as getting directly from `Sentry.Util.mix_deps()`

![screenshot](https://user-images.githubusercontent.com/484530/87664404-60698400-c78f-11ea-9080-d05780815b8d.png)

**Comment by mitchellhenke** [comment]
Thanks for opening an issue!

Unfortunately, it has to be at compile-time as Mix isn't guaranteed to be available at runtime, particularly for deployments that use releases like `mix release` or distillery.

I think the path towards a solution would be further investigation as to why not all of them are returned at compile-time in this case.

**Comment by wingyplus** [comment]
I try some debugging the project. I start by patch this code to lib sentry: 

```diff
$ git diff
diff --git a/lib/sentry/util.ex b/lib/sentry/util.ex
index e7e1507..95fb92b 100644
--- a/lib/sentry/util.ex
+++ b/lib/sentry/util.ex
@@ -27,8 +27,11 @@ defmodule Sentry.Util do

   @spec mix_deps() :: list(atom())
   def mix_deps do
+    Mix.Project.get() |> IO.inspect()
+
     Mix.Project.deps_paths()
     |> Map.keys()
+    |> IO.inspect()
   end
```

Then I change my project to use sentry on local path. And then run `mix clean --all && mix compile`, I get the result during compile sentry: 

```
==> sentry
Compiling 2 files (.ex)
Sentry.Mixfile
[:certifi, :cowboy, :cowlib, :decimal, :hackney, :idna, :jason, :metrics, :mime,
 :mimerl, :parse_trans, :plug, :plug_cowboy, :plug_crypto, :ranch,
 :ssl_verify_fun, :telemetry, :unicode_util_compat]
```

**Comment by wingyplus** [comment]
I think it's because we run Sentry.Util.mix_deps/0 inside :sentry app. So if we run it inside the target project by using macro?

**Comment by wingyplus** [comment]
Gather mix deps when calling `use Sentry.PlugCapture`. It's works as expects:

```diff
diff --git a/lib/sentry/event.ex b/lib/sentry/event.ex
index a1e9104..270024c 100644
--- a/lib/sentry/event.ex
+++ b/lib/sentry/event.ex
@@ -139,6 +139,8 @@ defmodule Sentry.Event do
 
     env = Config.environment_name()
 
+    mix_deps = Keyword.get(opts, :mix_deps, [])
+
     %Event{
       culprit: culprit_from_stacktrace(stacktrace),
       message: message,
@@ -158,7 +160,7 @@ defmodule Sentry.Event do
       breadcrumbs: breadcrumbs,
       request: request,
       fingerprint: fingerprint,
-      modules: Util.mix_deps_versions(@deps),
+      modules: Util.mix_deps_versions(mix_deps),
       event_source: event_source
     }
     |> add_metadata()
diff --git a/lib/sentry/plug_capture.ex b/lib/sentry/plug_capture.ex
index 076adde..79b017b 100644
--- a/lib/sentry/plug_capture.ex
+++ b/lib/sentry/plug_capture.ex
@@ -26,6 +26,11 @@ defmodule Sentry.PlugCapture do
   defmacro __using__(_opts) do
     quote do
       @before_compile Sentry.PlugCapture
+      @mix_deps if(
+                  Sentry.Config.report_deps(),
+                  do: Sentry.Util.mix_deps(),
+                  else: []
+                )
     end
   end
 
@@ -39,11 +44,22 @@ defmodule Sentry.PlugCapture do
         rescue
           e in Plug.Conn.WrapperError ->
             exception = Exception.normalize(:error, e.reason, e.stack)
-            Sentry.capture_exception(exception, stacktrace: e.stack, event_source: :plug)
+
+            Sentry.capture_exception(exception,
+              stacktrace: e.stack,
+              event_source: :plug,
+              mix_deps: @mix_deps
+            )
+
             Plug.Conn.WrapperError.reraise(e)
 
           e ->
-            Sentry.capture_exception(e, stacktrace: __STACKTRACE__, event_source: :plug)
+            Sentry.capture_exception(e,
+              stacktrace: __STACKTRACE__,
+              event_source: :plug,
+              mix_deps: @mix_deps
+            )
+
             :erlang.raise(:error, e, __STACKTRACE__)
         end
       end
diff --git a/lib/sentry/util.ex b/lib/sentry/util.ex
index e7e1507..95fb92b 100644
--- a/lib/sentry/util.ex
+++ b/lib/sentry/util.ex
@@ -27,8 +27,11 @@ defmodule Sentry.Util do
 
   @spec mix_deps() :: list(atom())
   def mix_deps do
+    Mix.Project.get() |> IO.inspect()
+
     Mix.Project.deps_paths()
     |> Map.keys()
+    |> IO.inspect()
   end
 
   @spec mix_deps_versions(list(atom())) :: map()
```

The result from `mix clean --all && mix compile` is: 

```
==> sentry
Compiling 1 file (.ex)
==> secret_project
Compiling 60 files (.ex)
SecretProject.MixProject
[:telemetry, :cors_plug, :cowboy, :telemetry_metrics, :ecto_sql, :httpoison,
 :metrics, :phoenix_pubsub, :connection, :dialyxir, :parse_trans, :credo,
 :ranch, :cloak_ecto, :tzdata, :ecto, :idna, :sentry, :absinthe, :myxql, :plug,
 :unicode_util_compat, :absinthe_plug, :gettext, :cowlib, :ecto_enum, :cloak,
 :mimerl, :bunt, :phoenix_ecto, :timex, :mime, :plug_crypto, :nimble_parsec,
 :certifi, :logger_json, :telemetry_metrics_prometheus_core, :plug_cowboy,
 :ssl_verify_fun, :erlex, :nimble_csv, :decimal, :db_connection, :jason,
 :telemetry_poller, :hackney, :telemetry_metrics_prometheus, :combine, :phoenix]
```

**Comment by wingyplus** [comment]
But the result from calling `mix sentry.send_test_event` will be disappear because I move gather mix deps into plug modules.

**Comment by wingyplus** [comment]
I open the PR for discussing this issue. Feel free to comment. :)

**Comment by wingyplus** [comment]
Hi @mitchellhenke, 

Currently, I have time to fix this issue that we discussed in #425. I need to confirm that I understand correctly. 

The mix deps that we have a problem need to move to user configuration. So we might need to introduced configuration for sentry. For example:

```
config :sentry, deps: Mix.Project.deps_paths()
```

What do you think?

**Comment by mitchellhenke** [comment]
@wingyplus I think the tricky part is making it work for both mix and release runtime environments, which makes me think that it needs to be configured at compilation-time.

I'm not sure if your proposed solution works, but I'm happy to take a look at any pull requests aiming to solve it 🙂

**Comment by thbar** [comment]
I've met that today while debugging a staging server (slightly less often deployed), with package `0.8.6`.

I wonder if an option to "just read the mix.lock" could work?

**Comment by whatyouhide** [comment]
I agree that we can do this at compile-time *in the host app*, not in the `:sentry` application. I renamed this issue to reflect that. 🙃

**Comment by wingyplus** [comment]
I'm willing to help even I can't use the new version of the library because of Sentry server I'm working with is very old. 😢
