### ISSUE TITLE
Sentry.capture_exception should log an error on failure

### ISSUE THREAD

**Issue by dylan-chong** [getsentry/sentry-elixir#419]
### Environment

* Elixir version (elixir -v):
* Erlang/OTP version (erl):
* Sentry version (mix deps): 7.2
* Operating system:
* Is this an umbrella application?: yes
* Release type (Distillery, mix release, Mix, etc.):

### Description

Calls to `Sentry.capture_exception` can fail if say a keyword list is passed into extras, rather than a map. We should not make it clear something is wrong by `Logger.error`ing a message

### Expected Behavior

Log a message

### Actual Behavior

A tuple is returned, but code often does not do anything with the return value so the error is supressed

### Steps to Reproduce

- Call `Sentry.capture_message("aaaaaaa", extra: %{metadata: [boo: "blaa"], module: __MODULE__})`.
- This value is returned:

```
{:error,
 {:invalid_json,
  %Protocol.UndefinedError{
    description: "Jason.Encoder protocol must always be explicitly implemented",
    protocol: Jason.Encoder,
    value: {:boo, "blaa"}
  }}}
```

We should see a Logged message too

**Comment by mitchellhenke** [comment]
Thanks for opening an issue! I’m not sure here, as Logging can be noisy and internal library logs are harder to control as a user.

Sentry does have some of that for cases that are further from the user. Is there a pattern to the use case or would it apply to any time the function is called?

For now, I’d suggest wrapping it and matching on the error and Logging on the user side.

**Comment by dylan-chong** [comment]
> Is there a pattern to the use case or would it apply to any time the function is called?

I would think it would be anytime the function is called and there is an issue

> I’m not sure here, as Logging can be noisy and internal library logs are harder to control as a user.

Hmm, good point. Not sure what to do about that. Maybe a configurable log level? That sounds like a fair amount of work to solve this issue though... Hmmm I don't know what to do here

**Comment by mitchellhenke** [comment]
I'm not sure this is worth another configuration level, and an on/off configuration means users would lose the ability to control granularity of when to log (e.g. only log on bad JSON, or only in certain situations, etc.)

**Comment by dylan-chong** [comment]
Maybe just leave it on? The error case shouldn't really happen... The only thing i can see is possible security issues of error data appearing unwanted in the logs, so as long as we don't actually print that data out it should be fine? Maybe?

**Comment by mitchellhenke** [comment]
So I was mistaken in thinking that there wasn't logging on errors at all. There is actually logging on errors, but just not for Jason decoding errors, which seems like an oversight on my part.

It probably makes sense to log consistently and include those types of errors as being logged.

**Comment by hfjallemark** [comment]
Just ran in to this also (a tuple in a tag) and was very difficult to track down since there is no error log from Sentry at all -- finally figured it out when I saw this issue.

**Comment by mitchellhenke** [comment]
Sorry for the delay, planning to tackle it this week 🙂
