### ISSUE TITLE
Link in Sentry 7 doc leading to Sentry 8 doc

### ISSUE THREAD

**Issue by staring-frog** [getsentry/sentry-elixir#422]
### Description

In https://hexdocs.pm/sentry/7.2.4/readme.html#capture-crashed-process-exceptions
"The backend can also be configured to capture Logger metadata, which is detailed here."
leads to https://hexdocs.pm/sentry/Sentry.LoggerBackend.html which is a 8.x doc.

### Expected Behavior

Should lead to https://hexdocs.pm/sentry/7.2.4/Sentry.LoggerBackend.html

**Comment by mitchellhenke** [comment]
Thanks for reporting this!

Fixed in the 7.2.5 release 🙂
