### ISSUE TITLE
Scrub exception data

### ISSUE THREAD

**Issue by teamon** [getsentry/sentry-elixir#424]
Is there a way to scrub exception data? I know there is a way to scrub conn body params & headers, but I'm looking for a way to handle cases like this:

```ex
{:ok, _} = some_fun()
```

when `some_fun()` returns `{:error, :secret}`. This gets converted into:

```
** (MatchError) no match of right hand side value: {:error, :secret}
```

that is sent to Sentry as is. 

It would be very useful to be able to scrub such exceptions, something like:

```ex
defmodule MyScrubber do
  def conceal(%MatchError{term: {:error, secret}} do
    %MatchError{term: {:error, "<this is secret">}}
  end

  def conceal(ex), do: ex
end
```

What do you think about extending `EventFilter` to allow `conceal/1` alongside `exclude_exception?/1` ?

**Comment by teamon** [comment]
That works, thanks!

**Comment by lud-wj** [comment]
Hello,

I'm trying to implement this solution using the `:before_send` configuration point.

The problem in that in the event passed to the callback, there is no exception anymore. Only the exception message and the stacktrace. For instance:

```
%Sentry.Event{
  event_id: "66902dd5d6cb468da8af8277d8188603",
  timestamp: "2025-01-28T18:33:25.746821",
  breadcrumbs: [],
  contexts: %{
    runtime: %{name: "elixir", version: "1.17.2 (compiled with Erlang/OTP 26)"},
    os: %{name: "linux", version: "6.8.0"}
  },
  dist: nil,
  environment: "dev",
  exception: [
    %Sentry.Interfaces.Exception{
      type: "MatchError",
      value: "no match of right hand side value: %{api_key: \"some super secret\"}",
...
```

You see on that last line, a sensitive value on the match is only present in the `value` which is not the actual exception but rather a message. Very hard to scrub properly then.

Is there another callback that is called with the actual exception? `before_filter` does not seem to exist anymore.
