### ISSUE TITLE
Logger.warn sent as error with capture_log_messages

### ISSUE THREAD

**Issue by jhchen** [getsentry/sentry-elixir#428]
### Environment

* Elixir version (elixir -v): 1.10.4
* Erlang/OTP version (erl): 22
* Sentry version (mix deps): 8.0.0
* Operating system: Ubuntu 16.04
* Is this an umbrella application?: No
* Release type (Distillery, mix release, Mix, etc.): mix release

### Description

With `capture_log_messages` on `Logger.warn` gets sent to Sentry as an error. Sentry does include the level in the extra metadata so not sure if this behavior is intentional.

<img width="687" alt="CleanShot 2020-09-03 at 12 08 44@2x" src="https://user-images.githubusercontent.com/192974/92157103-cca35400-edde-11ea-81ca-2798fae4b759.png">

It seems the cause is [logger_backend.ex:106](https://github.com/getsentry/sentry-elixir/blob/7b4295afb3b52cfaa2e7c7747a661040c3f4fde7/lib/sentry/logger_backend.ex#L106) sets up the `logger_level` into the `extra` metadata and passes through to capture_message, which eventually creates a new Event. Without `level` set, it will [default to error](https://github.com/getsentry/sentry-elixir/blob/7b4295afb3b52cfaa2e7c7747a661040c3f4fde7/lib/sentry/event.ex#L134).

### Expected Behavior

Sentry would sent the message as a warning

### Actual Behavior

Sentry sends as an error

### Steps to Reproduce

1. Turn on `capture_log_messages` and include at least warnings as minimal level to report
2. Call Logger.warn("Test")
3. Observe in sentry.io it gets reported as an error

**Comment by mitchellhenke** [comment]
Thanks for opening an issue, this makes a lot of sense to do

I've opened #430 to resolve this 🙂

**Comment by jhchen** [comment]
Thanks for the quick fix @mitchellhenke! Unfortunately there is a bit of a bug with the solution in that `:warn` is the atom Elixir uses while Sentry only recognizes `:warning`. I believe this is the only level that has a difference between Elixir and Sentry

**Comment by mladenml** [comment]
experiencing same behaviour (as jhchen stated) with client  version `8.0.2`. 
![Screenshot 2020-11-02 at 20 44 35](https://user-images.githubusercontent.com/39903355/97911888-49ee3500-1d4c-11eb-8873-4fd423487174.png)

Is fix for this on roadmap or PRs are welcome?

**Comment by mitchellhenke** [comment]
Yep, it’s on my list!

**Comment by aus70** [comment]
I'm seeing again the same issue: when I send a `Logger.warn` or `Logger.warning`, the `level` is error, the `logger_level` is warn. Regression? Am I missing anything?
