### ISSUE TITLE
Is it suppose to be root_source_code_paths or root_source_code_path ?

### ISSUE THREAD

**Issue by ahsandar** [getsentry/sentry-elixir#444]
### Environment

* Elixir version (elixir -v): `1.11.2`
* Erlang/OTP version (erl): `23.1.3`
* Sentry version (mix deps): `8.0.0`
* Operating system: `debian-buster`
* Is this an umbrella application?: `no`
* Release type (Distillery, mix release, Mix, etc.): `Docker`

### Description
Is it suppose to be `root_source_code_paths` or `root_source_code_path` ?

### Expected Behavior
```
==> sentry
Compiling 15 files (.ex)
Generated sentry app
```
### Actual Behavior
```
== Compilation error in file lib/sentry/event.ex ==
** (ArgumentError) :root_source_code_path must be configured
    lib/sentry/config.ex:86: Sentry.Config.root_source_code_path/0
    lib/sentry/sources.ex:67: Sentry.Sources.load_files/0
    lib/sentry/event.ex:64: (module)
    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
```
### Steps to Reproduce
`Fails`
```
config :sentry,
  dsn: System.get_env("SENTRY_DSN"),
  environment_name: System.get_env("RELEASE_LEVEL") || "development",
  included_environments: ~w(production staging),
  enable_source_code_context: true,
  tags: %{
    env: System.get_env("RELEASE_LEVEL") || "development"
  },
  root_source_code_paths: [File.cwd!()]
```

`compiles`
```
config :sentry,
  dsn: System.get_env("SENTRY_DSN"),
  environment_name: System.get_env("RELEASE_LEVEL") || "development",
  included_environments: ~w(production staging),
  enable_source_code_context: true,
  tags: %{
    env: System.get_env("RELEASE_LEVEL") || "development"
  },
  root_source_code_path: File.cwd!()
```

has the readme got it wrong ?

**Comment by mitchellhenke** [comment]
The README reflects the most recently released version. If you try updating from `8.0.0` to `8.0.4`, does the error persist?

**Comment by ahsandar** [comment]
A different error but still `root_source_code_path` works while `root_source_code_paths` fails 

![Screenshot 2020-12-07 at 4 11 26 PM](https://user-images.githubusercontent.com/2472371/101325574-f0c37500-38a6-11eb-93ab-938e22251dff.png)
`root_source_code_paths`
![Screenshot 2020-12-07 at 4 11 17 PM](https://user-images.githubusercontent.com/2472371/101325564-edc88480-38a6-11eb-9c57-c98cd8b9014e.png)

`root_source_code_path`
![Screenshot 2020-12-07 at 4 20 45 PM](https://user-images.githubusercontent.com/2472371/101326419-316fbe00-38a8-11eb-9f12-de93f27180aa.png)

**Comment by mitchellhenke** [comment]
Thanks for the detail. What configuration do you have in each of those cases?

I can reproduce the first error if I pass a string as the config instead of a list.

**Comment by ahsandar** [comment]
This works on 8.0.4

```
==> sentry
Compiling 15 files (.ex)
Generated sentry app
```
```
config :sentry,
  dsn: System.get_env("SENTRY_DSN"),
  environment_name: System.get_env("RELEASE_LEVEL") || "development",
  included_environments: ~w(production staging),
  enable_source_code_context: true,
  tags: %{
    env: System.get_env("RELEASE_LEVEL") || "development"
  },
  root_source_code_paths: [File.cwd!()]
```

Thanks for the help

**Comment by mitchellhenke** [comment]
Good to hear, thank you!
