### ISSUE TITLE
Unexpected issue grouping

### ISSUE THREAD

**Issue by anthonator** [getsentry/sentry-elixir#445]
### Environment

* Elixir version (elixir -v): 1.11.2
* Erlang/OTP version (erl): 23.1.5
* Sentry version (mix deps): 8.0.4
* Operating system: Alpine 3.12.1
* Is this an umbrella application?: No
* Release type (Distillery, mix release, Mix, etc.): `mix release`

### Description
We're receiving errors in Sentry that have the same error type (e.g. `MatchError`), stacktrace but a different message. These errors are being grouped together. Given the message is different we'd like these errors to be grouped separately.

### Expected Behavior
When receiving an error that has the same error type and stacktrace but a different message these issues should be grouped separately.

### Actual Behavior
Errors with the same error type and stracktrace but a different message are grouped together.

**Comment by anthonator** [comment]
According to the Sentry documentation the fingerprinting should be based on `stackgrace`, `exception` and `message`. So I'm unsure why these are getting grouped together.

https://docs.sentry.io/platforms/elixir/data-management/event-grouping/#grouping-algorithms

> All versions consider the stacktrace, exception and message.

**Comment by mitchellhenke** [comment]
Thanks for opening an issue! This is indeed odd, and I think I can confirm the behavior. Generating a `MatchError` with this:

```elixir
def index(conn, _params) do
  "not a number" = bad_match()
  render(conn, "index.html")
end

defp bad_match() do
  :rand.uniform(100)
end
```

I can get a number of events with messages that have `MatchError no match of right hand side value: 67`, `MatchError no match of right hand side value: 12`, etc. but they all group into one:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/1430443/101710631-7dad3080-3a57-11eb-8442-9dcc75b793a7.png">

It seems to be an issue with the Sentry server's grouping, and I will open an issue but some more info may help me. In my simpler example, the stacktrace is always identical. Is that also true for your case? The `JSON` link on the issue page should have the data being sent by the app if you're able to double check.

**Comment by anthonator** [comment]
Thanks for looking into this!

Yes, the stacktrace and the exception are identical for each error. The only difference is the message.

Let me know what other info I can provide!

**Comment by mitchellhenke** [comment]
It looks like this behavior is intended, at least for the default grouping logic. [This](https://docs.sentry.io/product/sentry-basics/guides/grouping-and-fingerprints/) says that stacktrace, exception and message are used, but not always together:

>A stack trace is used by default if it's available. So if two events have the same stack trace, then they will group into one issue.

This behavior is a bit surprising, and seems like a fingerprint would have to be built manually to avoid this.

**Comment by whatyouhide** [comment]
@mitchellhenke @anthonator I think the proper logic here is to group by exception type *and* stacktrace, but not message?

I would expect two `MatchError`s on the same line about a different value to be grouped together, no? I can see cases when this would be an issue, but maybe `MatchError` is an error that requires a different fingerprinting strategy altogether. Thoughts?

**Comment by whatyouhide** [comment]
According to the docs and to what I've been reading about, this is the expected default behavior in Sentry. You can always customize this with the `:fingerprint` option, which you can potentially also set in a `:before_send_event` callback. Let me know if you folks have any more issues!
