### ISSUE TITLE
Review `in_app_whitelist` 

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-elixir#449]
Our developer guidelines (https://develop.sentry.dev/inclusion/#changing-code) identify terms we'd like to phase out to ensure our code uses inclusive language.

Specifically, for `in_app_whitelist`:
"**whitelist/blacklist**:
Generally should not be used. We try to avoid the word "list" now in general and try to be more descriptive in the UI. For instance, the use of "ip blacklist" has been changed to "ip filters" as part of the filter product. If you need a generic term "allowlist" and "denylist" or "blocklist" are good substitutions."

Can we phase this term out when we next make a breaking change?

**Comment by mitchellhenke** [comment]
Thank you for opening this issue! I've opened #450 to deprecate that language, and it will be removed in the next major release.
