### ISSUE TITLE
Prevent Elixir from compiling when starting Heroku dyno

### ISSUE THREAD

**Issue by tompesman** [getsentry/sentry-elixir#451]
### Environment

* Elixir version (elixir -v): 1.10.x, 1.11.x
* Erlang/OTP version (erl): 23.1.3
* Sentry version (mix deps): 8.0.4
* Operating system: heroku-2018 stack
* Is this an umbrella application?: no
* Release type (Distillery, mix release, Mix, etc.): mix

### Description

When starting a Heroku dyno with this `elixir_buildpack.config`:

```bash
# Erlang version
erlang_version=23.1.3

# Elixir version
elixir_version=1.11.2

# Always rebuild from scratch on every deploy?
always_rebuild=false

# A command to run right before fetching dependencies
hook_pre_fetch_dependencies="pwd"

# A command to run right before compiling the app (after elixir, .etc)
hook_pre_compile="pwd"

# A command to run right after compiling the app
hook_post_compile="mix sentry_recompile"

# Set the path the app is run from
runtime_path=/app
```

and with this mix alias:

```elixir
sentry_recompile: ["compile", "deps.compile sentry --force"]
```

Sentry stack trace linking works the Heroku dyno works also. But when a dyno is started, the application compilation is started and there is a rather large delay in starting the dyno and sometimes the application boot on Heroku is timed out and the dyno fails to start.

### Expected Behavior
No compliation when starting the dyno and Sentry stack trace linking still active.

### Actual Behavior
Compilation when starting dyno resulting in boot time-outs.

### Steps to Reproduce
Use the config in the description.

**Comment by mitchellhenke** [comment]
Thanks for opening an issue! Are there any logs during the start when it fails to boot?

**Comment by tompesman** [comment]
Hi @mitchellhenke 

Thank you for your response! The dyno fails to start because compilation is done after before starting instead of during the build phase on Heroku. This can be slow and the dyno is too late binding to the webserver port.

You can try this yourself on your local machine.

**current behaviour:**
```
➜  project git:(develop) ✗ mix sentry_recompile
➜  project git:(develop) ✗ iex -S mix
Compiling 113 files (.ex)
Generated example app
Interactive Elixir (1.11.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```

**desired behaviour:**
```
➜  project git:(develop) ✗ mix sentry_recompile
➜  project git:(develop) ✗ iex -S mix
Interactive Elixir (1.11.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```
I want to find a solution that the build is cached after the sentry recompile phase.

**Comment by mitchellhenke** [comment]
Thanks for the additional context. This is odd, and I can reproduce those steps. It does make sense on some level that a final recompile may be needed following a forced recompile. If a module depends on a module that was recompiled, it may need recompilation.

If I change the task to `sentry_recompile: ["compile", "deps.compile sentry --force", "compile"]`, I would not expect there to be any compilation before running `iex -S mix`. Strangely, it does still recompile...

Can you try `sentry_recompile: ["compile", "deps.compile sentry --force", "compile"]` to see if you see the same behavior?

**Comment by tompesman** [comment]
Yes! Same behavior! I've tried the exact same thing in my attempts to debug this one. 

- `mix do sentry_recompile, compile` does still need to compile on `iex -S mix`
- `mix sentry_recompile && mix compile` will **not** compile on `iex -S mix`

It looks like the `compile` task is a special case? 🤔

**Comment by tompesman** [comment]
I've did some testing and this config works:

```
hook_post_compile="`mix sentry_recompile && mix compile`"
```

I'm not sure if the "source code context" works correcly right now, `mix sentry.send_test_event` does not include a stacktrace.

**Comment by tompesman** [comment]
This is working for me in multiple production apps. This does not feel like a real solution, but more like a workaround. What do you think @mitchellhenke?

**Comment by mitchellhenke** [comment]
@tompesman yeah, I agree, it's strange behavior. Admittedly, Sentry does some pretty weird things for this kind of compilation, but I opened an Elixir issue to see if this behavior is expected: https://github.com/elixir-lang/elixir/issues/10712

**Comment by mitchellhenke** [comment]
Unfortunately for this use case, it seems like `mix sentry_recompile && mix compile` is probably the best solution with how `mix do` works. I'll update the docs to reflect this.

**Comment by tompesman** [comment]
Okay, thank you!
