### ISSUE TITLE
Trying to mock with Mox causes an exception

### ISSUE THREAD

**Issue by BlueHotDog** [getsentry/sentry-elixir#454]
** (Mix) Could not start application sentry: exited in: Sentry.start(:normal, [])
    ** (EXIT) exited in: GenServer.call(Mox.Server, {:fetch_fun_to_dispatch, [#PID<0.489.0>], {Api.SentryClientMock, :child_spec, 0}}, 30000)
        ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started

**Comment by mitchellhenke** [comment]
Hi @BlueHotDog, thanks for opening an issue!

The issue template has a few fields to help get to the bottom of issues, including the Elixir/Erlang version, Sentry versino and how to reproduce the error. I'm not familiar with Mox, so if you could provide those details, it'd be greatly appreciated 🙂

**Comment by mitchellhenke** [comment]
Closing this for now, but happy to take a look further with more info!
