### ISSUE TITLE
Instructions to use with Mojito

### ISSUE THREAD

**Issue by BlueHotDog** [getsentry/sentry-elixir#455]
Hi, our http-client is Mojito, and wanted to use it, but couldnt figure this out.

**Comment by mitchellhenke** [comment]
Thanks for opening an issue!

The HTTP client is configurable via the `Sentry.HTTPClient` behaviour, I've attempted to improve the discoverability and documentation around this in #456. https://claudio-ortolina.org/posts/using-finch-with-sentry/ also covers using Finch as a replacement, which may be similar to Mojito.
