### ISSUE TITLE
Migrate CI from Travis to GitHub Actions

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry-elixir#458]
Hey, we (Sentry) are in the process of migrating all of our repos away from Travis. This issue will be used by @getsentry/productivity to track overall progress across the organization, but please let us know here if there's anything we should be aware of. Thanks!

**Comment by mitchellhenke** [comment]
@billyvg I think it should be all switched over now, let me know if there's anything else to do related to this! 🙂
