### ISSUE TITLE
Dedupe plugin

### ISSUE THREAD

**Issue by depeiwang** [getsentry/sentry-elixir#459]
I searched everywhere in Google, but found nothing with elixir dedupe plugin...
If there are plugins available, thank you very much :)

**Comment by mitchellhenke** [comment]
Hi @depeiwang, thanks for opening an issue!

Can you describe a little bit more what you mean by a dedupe plugin?
If you could also fill out the issue template, that'd help me get to the bottom of this too.

**Comment by mitchellhenke** [comment]
Closing this for now, but happy to look into it further with some more details 🙂

**Comment by HazAT** [comment]
I am going to re-open this. 
We need this in the SDK and going to implement it.

**Comment by whatyouhide** [comment]
Closed in #650.
