### ISSUE TITLE
Default environment_name is not reflected in the README.

### ISSUE THREAD

**Issue by mhanberg** [getsentry/sentry-elixir#463]
### Expected Result

The default `:environment_name` is :dev, as indicated in the README.

### Actual Result

The default `:environment_name` is :prod. 

I believe this is because `Mix.env()` is used by Sentry to detect the current env, but this will always evaluate to :prod because dependencies are always compiled with MIX_ENV=prod (to my knowledge).

### Solution

Either the README is updated or the code changes to reflect the README.

**Comment by mitchellhenke** [comment]
@mhanberg Thank you for catching this!

**Comment by mhanberg** [comment]
I think the change you made still implies that the default will be whatever the users MIX_ENV currently is, but it will never be anything other than :prod.

**Comment by mitchellhenke** [comment]
@mhanberg Sorry, perhaps I misunderstood the original issue.

When getting environment name in the default configuration, this is what I get:

```elixir
# env MIX_ENV=dev iex -S mix

iex(1)> Sentry.Config.environment_name
:dev

# env MIX_ENV=test iex -S mix

iex(1)> Sentry.Config.environment_name
:test

# env MIX_ENV=prod iex -S mix

iex(1)> Sentry.Config.environment_name
:prod
```

Are you seeing different behavior?

**Comment by mhanberg** [comment]
Are you running that from within the sentry project? If so, those results make sense.

When you use sentry as a dependency in a project, it will be compiled with MIX_ENV=prod, because that is how deps are compiled.

I don't have my work computer right now, but I installed sentry into a new project for demonstration purposes and can confirm that `Sentry.Config.environment_name()` evaluates to `:prod`.

![image](https://user-images.githubusercontent.com/5523984/109424685-9d972500-79b2-11eb-9ed2-827f2bb1cd45.png)

If i locally edit sentry `vim deps/sentry/lib/sentry/config.ex`, and add an `IO.inspect/2` to the line that sets `the default_environment_name`, and recompile, you'll see that it emits `:prod`

![image](https://user-images.githubusercontent.com/5523984/109424734-f23aa000-79b2-11eb-8c99-5250bfe9fd62.png)

![image](https://user-images.githubusercontent.com/5523984/109424736-f6ff5400-79b2-11eb-9e17-47a21b188244.png)

If we move the call to `Mix.env()` to runtime, we can observe that the environment_name uses the consuming projects MIX_ENV

![image](https://user-images.githubusercontent.com/5523984/109424797-49d90b80-79b3-11eb-8ef7-4a543f53a434.png)
![image](https://user-images.githubusercontent.com/5523984/109424801-4f365600-79b3-11eb-886c-f047b4deced7.png)

However, relying on Mix at runtime is obviously not wise considering projects deployed using releases.

---

So, I believe that the documentation should reflect the implementation by stating that the default environment_name is `:prod`, or the the implementation should switch from `Mix.env()` to `:dev` to reflect the documentation.

Thanks!

**Comment by mhanberg** [comment]
As a final sanity check

![image](https://user-images.githubusercontent.com/5523984/109425424-2a8fad80-79b6-11eb-8813-def1cc930f2f.png)

**Comment by mitchellhenke** [comment]
Ahhhhh, right, thank you so much. Greatly appreciate the correction. I will make a correction to the docs and look into this further since it is effectively `:prod` at this point.

**Comment by mhanberg** [comment]
Thanks for taking a look at this!
