### ISSUE TITLE
Plan for Performance Support

### ISSUE THREAD

**Issue by xdays** [getsentry/sentry-elixir#468]
https://docs.sentry.io/product/performance/getting-started/

Do you have any plan to support performance? We are using another product for tracking performance.

**Comment by mitchellhenke** [comment]
Thanks for opening an issue! It's on the roadmap, and I've got some prototypes going, but it's a significant overhaul of the library, so I don't have a timeline yet.

I'm tracking Performance/APM in https://github.com/getsentry/sentry-elixir/issues/426 though, so I'm closing this issue as a duplicate for now 🙂
