### ISSUE TITLE
Exceptions that implement the Plug.Exception protocol are still being reported

### ISSUE THREAD

**Issue by mhanberg** [getsentry/sentry-elixir#471]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
elixir 8.0.4

### Steps to Reproduce

Hit any endpoint that might return a 404 due to not finding something in the database using a bang version of the ecto repo functions, like `Repo.get!(User, random_id_that_wont_be_found)`.

### Expected Result

No sentry error

### Actual Result

Observe that an exception is sent to sentry for `Ecto.NoResultsError`

**Comment by mitchellhenke** [comment]
Thanks for opening an issue! I don't know that Sentry can or should ignore all Exceptions that implement the `Plug.Exception` protocol. The default list Sentry ignores is: https://github.com/getsentry/sentry-elixir/blob/0b7f8e3d786d626dbf945c421a4850ce7dbcde51/lib/sentry/default_event_filter.ex#L7-L11

If you'd like to ignore different errors, implementing a custom [EventFilter](https://hexdocs.pm/sentry/Sentry.EventFilter.html) is the best way.

**Comment by mhanberg** [comment]
I was playing around with the code to see if I could add this in, but in doing so I also realized that it might not be the best solution, as you only want this behavior if you are using Plug.ErrorHandler or using the `render_errors` option of the phoenix endpoint.

Also, after clicking the link to the EventFilter, I see literally what I am trying to do 😅

![image](https://user-images.githubusercontent.com/5523984/114041018-262aa000-9852-11eb-8eaf-0320e3c10aa6.png)

Thanks for the patience.

**Comment by mitchellhenke** [comment]
I had forgotten about that doc, so thank you for sharing that here 🙂
