### ISSUE TITLE
Allow Sentry library to capture Sentry exceptions

### ISSUE THREAD

**Issue by JayAndCatchFire** [getsentry/sentry-elixir#476]
I was experiencing an issue similar to #419 where I was trying to pass an Ecto changeset into the extra context.  It was failing with this error message:
```elixir
{:error,
 {:invalid_json,
  %Protocol.UndefinedError{
    description: "Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @derive Jason.Encoder\n    defstruct ...\n\nFinally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:\n\n    Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])\n    Protocol.derive(Jason.Encoder, NameOfTheStruct)\n",
    protocol: Jason.Encoder,
    value: #Ecto.Changeset<
      action: :insert,
      changes: %{
        # ...snip...
      },
      errors: [
        # ...snip...
      ],
      data: #SNIP<>,
      valid?: false
    >
  }}}
```
I had a difficult time tracking this down.  This wasn't being logged in my logger.  I ended up having to add `:sync` and `IO.inspect` the results of the attempt to call `Sentry.capture_message`.
```elixir
Sentry.capture_message("Error occurred ...snip...",
  extra: %{
    changeset: changeset,
    params: full_params
  },
  sync: true
) |> IO.inspect()
```
All I knew was that there should have been Sentry alerts being captured and there weren't.  The Jason.Encoder error wasn't being logged in my output.  I'd like it if the Sentry lib itself were to send a Sentry alert for these types of issues.  IMHO, that seems like an appropriate option.  When you're trying to send a Sentry and you can't because of the data you're trying to send, that deserves a Sentry.

This could be hidden behind a config flag if people don't want this to happen.  But it seems to me like a sane default to be loud when this happens.  (I'd also be fine with having to opt into this behavior even though I think this should be the default.)

**Comment by JayAndCatchFire** [comment]
Or is this issue on me?  Should I be doing something like this every time I try to capture a Sentry error?
```elixir
:ok = Sentry.capture_message("Oops!")
```

**Comment by JayAndCatchFire** [comment]
After considering this more, I think matching on `{:ok, _}` is more Elixiric™️.  If _that_ fails and you have Sentry set up properly app-wide, it should cause a Sentry.

**Comment by mitchellhenke** [comment]
Thanks for opening an issue! You have it exactly. Implementing the protocol is another option.
