### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by hfjallemark** [getsentry/sentry-elixir#479]
Are there any plans to support attachments like some of the other libraries does?

https://docs.sentry.io/platforms/javascript/enriching-events/attachments/
https://docs.sentry.io/platforms/native/enriching-events/attachments/
https://docs.sentry.io/platforms/java/enriching-events/attachments/

Looks like it's a separate endpoint for uploading attachments: https://develop.sentry.dev/sdk/envelopes/

**Comment by mitchellhenke** [comment]
@hfjallemark thanks for opening an issue! This is related to #426 as it's part of the rewrite to enable the use of the Envelope API
