### ISSUE TITLE
Relax Plug.Cowboy dependency requirements

### ISSUE THREAD

**Issue by arkgil** [getsentry/sentry-elixir#480]
Hi there! 👋

Currently the package specifies the following dependency on the Plug.Cowboy package:

https://github.com/getsentry/sentry-elixir/blob/02a2cc31c7444af88d079f7c32a789b9b1b4e6f1/mix.exs#L44

We have some apps still using Cowboy 1.x, which causes a dependency conflict. For the sake of testing, we've set `override: true` on `:plug_cowboy` in our `mix.exs` files, and the integration with Sentry seems to be working correctly.

Is there a reason why the package depends on Plug.Cowboy 2.x? I've looked at the code and it looks like Plug.Cowboy is only used in tests. If there's not, would it be possible to relax the requirement to allow Plug.Cowboy 1.x too? 

Thanks!

**Comment by mitchellhenke** [comment]
The complicating part is the Logger integration depends on behavior in Plug 2.x to avoid double logging an error through PlugCapture and Logger.

The commit is here: https://github.com/elixir-plug/plug_cowboy/commit/3760ab479b02279d39ddf2b9cf7791f07470277c#diff-87fab128ba958876d471b11a331119757921bd6a6c29c364881497a280b3f1af

**Comment by arkgil** [comment]
Thanks Mitchell! With Cowboy 1.x override, it's more likely that we'd lose the events, or that they'd be reported twice?

**Comment by mitchellhenke** [comment]
They would be reported twice (with slightly different metadata) if you use both `Sentry.LoggerBackend` and `Sentry.PlugCapture`. The bit that enables it is having `:cowboy` in the excluded domains here: https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/logger_backend.ex#L48

**Comment by arkgil** [comment]
Thank you for clarification! I'm gonna close the issue then 👍
