### ISSUE TITLE
Support Finch as a http client

### ISSUE THREAD

**Issue by wingyplus** [getsentry/sentry-elixir#481]
Hi, 

Currently, the library supports only `hackney` as an HTTP client. I would like to purpose `finch` for the alternative client. I could help to work on this issue.

Feedback?

**Comment by mitchellhenke** [comment]
Thanks for opening an issue! The library supports a protocol to implement against for alternative clients if you'd rather not use `hackney` (see https://hexdocs.pm/sentry/Sentry.HTTPClient.html).

Claudio Ortolina was kind enough to publish an implementation of using Finch with Sentry: https://claudio-ortolina.org/posts/using-finch-with-sentry/) and https://github.com/fully-forged/tune/blob/main/lib/sentry/finch_client.ex. I have not tried it myself so I can't speak to that specific implementation, but the `Sentry.HTTPClient` protocol should be able support non-hackney clients 🙂

**Comment by mitchellhenke** [comment]
Closing this issue for now as Sentry does have a way to use `Finch` via the protocol 🙂
