### ISSUE TITLE
Accept all environments by default (in `included_environments`)

### ISSUE THREAD

**Issue by awoimbee** [getsentry/sentry-elixir#483]
## context

I run an elixir app. I can configure the `environment_name` from my deployment config.

## issue

This lib has a weird behavior: it needs me to set `included_environments`, otherwise only stats coming from one of `[:test, :dev, :prod]` will show up in sentry ([doc](https://docs.sentry.io/platforms/elixir/#configure)).
I need a way to include any/every environment, I don't need filtering, especially not as a default setting !

1. It's weird, at first I don't know what's happening, why it isn't working.
2. Now what ? I'm supposed to modify the app every time I deploy in a different env ?

## more context

The ruby lib already moved to including all the environments by default ([source](https://docs.sentry.io/clients/ruby/configuration/options/)):
> As of v0.10.0, events will be sent to Sentry in all environments. If you do not wish to send events in an environment, we suggest you unset the SENTRY_DSN variable in that environment.

## BTW

If `environment_name` is a string but `included_environments` is an array of atoms (or vice-versa), nothing works. There is no warning in the docs nor from the app itself, it will run but never pass errors to sentry !
It is **very** frustrating to spend so much time configuring a thing that should not even exist and that I would like to get rid of !

**Comment by mitchellhenke** [comment]
Thanks for opening an issue on this. I think this makes a lot of sense to do! This would be a breaking change, so will have to be in the next major release.
