### ISSUE TITLE
Crash reports from `gen_statem` processes are ignored

### ISSUE THREAD

**Issue by dmorneau** [getsentry/sentry-elixir#485]
### Environment

Elixir Sentry SDK v8.0.5

### Steps to Reproduce

1. Trigger a crash in a gen_statem process

### Expected Result

Crash gets logged to Sentry, same as gen_server, etc.

### Actual Result

The crash doesn't get logged. See: https://github.com/elixir-lang/elixir/issues/11115

**Comment by mitchellhenke** [comment]
Hi @dmorneau, thanks for opening an issue!

Do you have `Sentry.LoggerBackend` configured? I can confirm that I do receive crashes logged in Sentry:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/1430443/132234212-aa352f70-4ac0-4418-b1c6-144f88fb338a.png">

**Comment by dmorneau** [comment]
I do have the backend and non-statem reports work fine, but I traced around some more and noticed setting `handle_sasl_reports` to true on the logger config seems to fix it. Do you have that enabled in the sample app?

Normally I avoid turning it on because SASL is deprecated (AFAIK), and it adds hundreds of lines of progress reports when running the app. Maybe the short-term fix would be to document that requirement, and eventually something like https://github.com/getsentry/sentry-elixir/issues/384 would solve it for good?

**Comment by mitchellhenke** [comment]
I do not have SASL enabled and am able to receive reports, so I’m curious why your configuration does not. Could you share your logger configuration and Elixir/Erlang version?

Regarding Erlang logger, yes it is an eventuality when Elixir fully supports it, but for now `:capture_log_messages` is the option to receive less structured event messages.

**Comment by dmorneau** [comment]
Odd! This is Elixir 1.12.2 on OTP-24.0.5 with:

```
config :logger,
  level: :info,
  backends: [:console, Sentry.LoggerBackend]

config :logger, :console,
  format: "[$level] $message\n",
  level: :debug
```

`extra_applications` includes `:logger` and `:lager` (used by a dependency) but not `:sasl`.

If these settings look like they should work, I'll try to debug this further, maybe removing lager next...

**Comment by mitchellhenke** [comment]
I would suggest seeing if the behavior persists with `lager` removed, as I think there have been some incompatibilities reported in the past.

**Comment by al2o3cr** [comment]
Related issue: https://github.com/ericentin/gen_state_machine/issues/29

**Comment by whatyouhide** [comment]
In my tests, these crashes get reported if you do

```elixir
config :logger,
  handle_sasl_reports: true
```

It's not ideal, but this is out of our control (in this SDK, that is) because otherwise events just don't end up in logger handlers/backends, so we can't catch them.

Thanks anyways! 💟

**Comment by ryanwinchester** [comment]
Should be fixed in https://github.com/elixir-lang/elixir/pull/13451 🤞

**Comment by dmorneau** [comment]
Thanks!
