### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by aselder** [getsentry/sentry-elixir#502]
It looks like there is an error in the documenation about config values.

The documentation mentions `:root_source_code_paths`, but it looks like the code is expecting `:root_source_code_path`

### Steps to Reproduce

1. Copy the config block from README.md
2. Recompile the app (including Sentry)

### Expected Result

Application compiles

### Actual Result

```
❯ mix deps.compile sentry --force
==> sentry
Compiling 15 files (.ex)

== Compilation error in file lib/sentry/event.ex ==
** (ArgumentError) :root_source_code_path must be configured
    lib/sentry/config.ex:86: Sentry.Config.root_source_code_path/0
    lib/sentry/sources.ex:67: Sentry.Sources.load_files/0
    lib/sentry/event.ex:64: (module)
could not compile dependency :sentry, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile sentry", update it with "mix deps.update sentry" or clean it with "mix deps.clean sentry"
```

**Comment by BlueHatbRit** [comment]
It looks like this is the offending function: https://github.com/getsentry/sentry-elixir/blob/b915794203710fc254ee88b036d2c25b8809fbf5/lib/sentry/config.ex#L81 it is called by the new `root_source_code_paths` function for backwards compatibility but that causes the error to be issued. It looks like you should either ignore the deprecation until it's fixed and use `root_source_code_path` or set both.
