### ISSUE TITLE
Remove implicit read from environment variables.

### ISSUE THREAD

**Issue by yordis** [getsentry/sentry-elixir#503]
### Environment

```elixir
{:sentry, "8.0.6"},
```

## Context

Today, I had to figure out why I kept getting the following issue:

```bash
** (Mix) Could not start application sentry: exited in: Sentry.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) "DEBUG" is not a valid :log_level configuration
            (sentry 8.0.6) lib/sentry.ex:219: Sentry.validate_log_level_config!/0
            (sentry 8.0.6) lib/sentry.ex:105: Sentry.start/2
            (kernel 8.3.1) application_master.erl:293: :application_master.start_it_old/4
```

I searched in my codebase, and I couldn't find who was setting the `"DEBUG"` value, nowhere in my code was set.

Which led me to figure out what could go wrong, because it only happened in CI, at least isolated to the environment. So I came across the following line of code

https://github.com/getsentry/sentry-elixir/blob/27f14cf2f648e409f04326f5fa2f58620902634b/lib/sentry/config.ex#L218-L219

So, I discovered that we, indeed, set up the `SENTRY_LOG_LEVEL=DEBUG` across all our pipelines.

## Request

Remove the implicit lookup in the environment variables

### Why should we?

Elixir we have build-in tools to do a better job managing configuration.

We have:

- `config/config.exs` for build-time configurations injection.
- Or `config/runtime.exs` if we decide we want to inject things at runtime.

The topic related to configuring the application should be left alone to the application developers, in my personal opinion.

A simple misconfiguration could be leading to problems.

While explicitness is a bit more work, such work is quite trivial, and quite small work at the beginning while quite stable after setting up and barely changing it after that.

Not being explicit about it, every incoming Operation person must be careful and have institutional knowledge. Infrastructure configurations change more often related to environment variables and whatnot.
In this particular case, it was set to `"DEBUG"` because of libraries in the NodeJS ecosystem, and made it incompatible with the Elixir ..... really error-prune, and wishes all the Sentry packages would be more explicit honestly.

In the worst case, you can follow what other packages do related to reading from the system env

```elixir
config :ex_aws,
  access_key_id: {:system, "AWS_ACCESS_KEY_ID"}
```

It is explicit, but also outdated, such packages existed before `config/runtime.exs` was added to the language.

So I would like to reconsider the decision made and improve upon such topic.

**Comment by yordis** [comment]
Same with this part, https://github.com/getsentry/sentry-elixir/blob/27f14cf2f648e409f04326f5fa2f58620902634b/lib/sentry/config.ex#L220

I am not sure why this would be the case though.

**Comment by mitchellhenke** [comment]
The code here is longer in the tooth, dating back to before elixir releases with robust configuration had arrived, and there’s a balance between “batteries-included” and too much magic that makes debugging difficult. The code hasn’t quite kept up with those changes, and patterns borrowed from other Sentry integrations don’t apply as well now.

I do think moving some of the config to be more explicit would be good. Inferring from system environment is probably the most egregious now, are there other things you think could be changed?

These are all unfortunately breaking changes as well 🙂

**Comment by yordis** [comment]
> The code here is longer in the tooth, dating back to before elixir releases with robust configuration had arrived

Yeah ... I can tell for sure.

> These are all unfortunately breaking changes as well 🙂

This is where it is quite difficult to make a good judgment without a trade-off. In the worst case, introduce the Config for the Config

```elixir
config :sentry, config_provider: Sentry.LegacyConfig 🤷🏻 
```

So people could opt-in and give them time to remove the deprecation eventually. I am not sure.

> are there other things you think could be changed?

**Documentation**, I ended up following the hosted documentation inside Sentry to set up the package because there was a mismatching and I got lost.

Providing guidelines and proper how-tos. I personally like to follow https://diataxis.fr/ and keep a list of how-tos in the documentation to help all levels of expertise.

Such a thing will help to mitigate the burden of setting things up (just copy-paste) while removing the magical thing that adds little value in the long term.

Then, move to close one ticket at a time if possible.

**Comment by yordis** [comment]
@whatyouhide The original issue is related to reading environment variables instead of using `{:system ....}` configuration https://github.com/getsentry/sentry-elixir/blob/5d3296442e2787b3be002e29c0dfdf9695448515/lib/sentry/config.ex#L217C53-L217C53

Is there any opportunity to remove such a situation since it still causes the same issue? (although at least now I am personally aware of it)

**Comment by whatyouhide** [comment]
@yordis all Sentry SDKs use at least

* `SENTRY_DSN`
* `SENTRY_ENVIRONMENT`
* `SENTRY_RELEASE`

So, we want to keep this behavior in Elixir as well. We could potentially *warn* if you set both one of these env variables *and* the corresponding application configuration key, but there are use cases for that, such as having a default config and then overriding via env variables in deployed environments.

Does that make sense?

**Comment by yordis** [comment]
> @yordis all Sentry SDKs use at least
> SENTRY_DSN
> SENTRY_ENVIRONMENT
> SENTRY_RELEASE

Hard to go against that. Still believe that shouldn't be the default case, but whatever, bikeshedding.

Just would like to avoid the original situation as much as I can, especially with more critical values, a simple "shared" environment could introduce horrible situations.

Being said, I trust your judgment and know what we should do. Good enough for now I guess.

**Comment by whatyouhide** [comment]
> Just would like to avoid the original situation as much as I can

To do this, I removed all other `SENTRY_` env variables 😄 Hopefully that's good enough!
