### ISSUE TITLE
Handle missing EXIT reasons and add them to `Sentry.CrashError`

### ISSUE THREAD

**Issue by yordis** [getsentry/sentry-elixir#510]
### Environment

How do you use Sentry?

Self-hosted/on-premise: `21.8.0 e1ddac6`

Which SDK and version?

```
sentry-elixir 8.0.6
```

### Context

We are getting a lot of `Sentry.CrashError ** (exit) killed` error reports, but we can't really figure out why those crashes are happening.

> Here is the exception section

```
Sentry.CrashError ** (exit) killed
```

```
Sentry.CrashError: ** (exit) killed
  File "gen_server.erl", line 811, in :gen_server.handle_common_reply/8
  File "proc_lib.erl", line 236, in :proc_lib.wake_up/3
```

```
(Sentry.CrashError ** (exit) :hb_timeout)
```

```
(DBConnection.ConnectionError tcp recv (idle): closed)
```

As you can see, not much to work with, in some cases, no stack trace at all so it is quite hard to figure out what the issues are.

I setup

```elixir
config :logger,
  handle_otp_reports: true,
  handle_sasl_reports: true
```

Which was my last line of defense in figuring this out.

Any thoughts?

**Comment by yordis** [comment]
I tried setup some `metadata` to see how it works, but no success so far

```elixir
config :sentry,
  metadata: [:ancestors]
```

**Comment by dvic** [comment]
Commanded user I guess ;)

I think I figured it out, it's because the logger_backend doesn't handle reason `{:killed, []}` properly, it ends up going to https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/logger_backend.ex#L105-L107, which results in a call to `Exception.format_banner(:exit, :killed, [])`, which gives `"** (exit) killed"`.

However, I'm not familiar enough with erlang errors and reasons to apply a proper fix here, I'll need to investigate more.

**Comment by dvic** [comment]
Okay, basically doing this
<img width="608" alt="image" src="https://user-images.githubusercontent.com/1214337/202285384-0a4de159-8734-427d-ae78-4835b632c338.png">

fixes the problem (includes the full message)

But I have no idea if this is a valid fix. Thoughts?

**Comment by yordis** [comment]
Is there any way to improve the pattern matching implementation with `{other, stacktrace}`? it should fallback into that one

**Comment by dvic** [comment]
> Is there any way to improve the pattern matching implementation with `{other, stacktrace}`? it should fallback into that one

Yeah I guess the if check on line 106 in the above screenshot could be moved into the `{other, stacktrace}` fallback.

**Comment by aus70** [comment]
I'm also getting many `Sentry.CrashError ** (exit) time out`. Is there a way to stop them?

**Comment by dvic** [comment]
You can try using an event filter (https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/event_filter.ex) that excludes `Sentry.CrashError`, but then, depending on what the source of you're errors is, you might exclude too much.

**Comment by aus70** [comment]
That could be an option, thanks!

Do you know if the cause of the `Sentry.CrashError ** (exit) time out` will be removed anytime soon?

**Comment by dvic** [comment]
> Do you know if the cause of the Sentry.CrashError ** (exit) time out will be removed anytime soon?

Not sure if my solution is appropriate, maybe someone on the team can have a look and I can cook up a PR.

**Comment by dvic** [comment]
> Okay, basically doing this <img alt="image" width="608" src="https://user-images.githubusercontent.com/1214337/202285384-0a4de159-8734-427d-ae78-4835b632c338.png">
> 
> fixes the problem (includes the full message)
> 
> But I have no idea if this is a valid fix. Thoughts?

@whatyouhide is this a solution to this problem? If so, I can open a PR so we can get rid of this one :)

**Comment by whatyouhide** [comment]
We're reworking some of the internals, but yes, this is something we can improve. Just need to get a few things re-shaped first 🙃
