### ISSUE TITLE
Add a `Sentry.EventFilter.exclude_event?/2` callback

### ISSUE THREAD

**Issue by agutierrezrodriguez** [getsentry/sentry-elixir#512]
We can filter exception messages captured from LoggerBackend if the event has an exception attached although if we raise a Logger.error message without exception, the events can not be filtered.

For example
```elixir
Logger.error("My error message")
```
This line always will be sent because it not has an exception attached in metadata.

**Comment by whatyouhide** [comment]
We can add a callback that takes a `Sentry.Event` struct and returns a boolean. It will be enough to potentially filter out messages, exceptions, based the filter on stacktraces, and more.

@sl0thentr0py you good with this?
