### ISSUE TITLE
Possibly infinite error loop with custom http client.

### ISSUE THREAD

**Issue by ruslandoga** [getsentry/sentry-elixir#514]
👋

The way people use finch for a sentry client [[1,](https://github.com/search?q=Sentry.FinchClient+language%3AElixir&type=Code) [2](https://claudio-ortolina.org/posts/using-finch-with-sentry/)] can cause sentry to enter a possibly infinite exception generating loop.

Once `:sentry` starts sending enough events, `:nimble_pool` which `:finch` uses for managing http1 connections starts [timing out and exiting](https://github.com/dashbitco/nimble_pool/blob/f495e4d279cb5d8bd8c2dc56c33d37cdcdd1e96d/lib/nimble_pool.ex#L368) and finch [relays the exit](https://github.com/sneako/finch/blob/702c52767e5f3dd1fb3560057a85b5e62b2ca357/lib/finch/http1/pool.ex#L57) to the caller which makes [the task sending the request](https://github.com/getsentry/sentry-elixir/blob/76b23dbaff6ec560dc806a4b107b2657a772b55a/lib/sentry/client.ex#L138-L141) terminate and generate another exception thus entering an error loop generating more exceptions.

The exeption looks like this

```plain
12:12:12.866 [error] Task #PID<0.391.0> started from #PID<0.288.0> terminating
** (stop) exited in: NimblePool.checkout(#PID<0.347.0>)
    ** (EXIT) time out
    (finch 0.12.0) lib/finch/http1/pool.ex:57: Finch.HTTP1.Pool.request/5
    (finch 0.12.0) lib/finch.ex:313: anonymous fn/4 in Finch.request/3
    (telemetry 1.1.0) /Users/ruslan/Developer/sentry-finch-issue/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3
    (s 0.1.0) lib/finch_client.ex:18: Sentry.FinchClient.post/3
    (sentry 8.0.6) lib/sentry/client.ex:210: Sentry.Client.request/3
    (sentry 8.0.6) lib/sentry/client.ex:192: Sentry.Client.try_request/5
    (sentry 8.0.6) lib/sentry/client.ex:167: anonymous fn/4 in Sentry.Client.do_send_event/3
    (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
Function: #Function<2.43295134/0 in Sentry.Client.do_send_event/3>
    Args: []
```

Please see [this gist](https://gist.github.com/ruslandoga/9bb8c0a27f8ffd7661d34b8957c9d9ac) for more info, it also contains two possible workarounds (`try/catch` and `protocol: :http2`) but I don't know if they are good enough to suggest to other people.

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

### Steps to Reproduce

```bash
export SENTRY_DSN=https://1a77dc7a687646b28c1b1b6cee1ef4a9@o1012425.ingest.sentry.io/6601933
curl -LO https://gist.githubusercontent.com/ruslandoga/9bb8c0a27f8ffd7661d34b8957c9d9ac/raw/c0eb3a448c0493f08bef38286a92436c56333308/error_loop.exs
elixir error_loop.exs
```

### Expected Result

Sentry doesn't enter that kind of an error loop regardless of what the client does. Or docs make it clear that custom clients shouldn't raise.

### Expected Result (from opening this issue)

Not sure. One one hand, this is more of a problem with the custom client that `:sentry` is not responsible for, on the other hand, I haven't been able to find a client that foresaw this problem which could mean that docs regarding custom clients are not clear enough.

Maybe it would be ok to include a finch client by default or add it in the docs for `Sentry.HTTPClient` as an example?

**Comment by josevalim** [comment]
I think any HTTP client can fail, so it is likely this issue exists elsewhere. My suggestion would be to actually wrap the HTTP client calls in Sentry in a try/catch and, if those fail, log the error.

However, you must also keep in mind that you cannot log the error if it happens if you are inside the Sentry.LoggerBackend. So when you start Sentry.LoggerBackend, you want to store something in the process dictionary and avoid the logging altogether in such cases.

**Comment by josevalim** [comment]
@ukutaht exactly! :+1:

**Comment by ruslandoga** [comment]
I think `event.event_source` could be used to avoid the loop. Right now it only works one way, `:logger -> :sentry`.
