### ISSUE TITLE
Add craft to sentry-elixir

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-elixir#518]
[Craft](https://github.com/getsentry/craft) is Sentry's universal release tool. It would be nice to add it to sentry-elixir so when we do releases, we can push new versions to [Sentry's release registry](https://github.com/getsentry/craft#sentry-release-registry-registry). This allows us to add features to our docs/product to call out new versions of sentry-elixir. Would be great to get something like below on the [Elixir docs](https://docs.sentry.io/platforms/elixir/) for example.

![image](https://user-images.githubusercontent.com/18689448/182883336-d2e45755-3388-499c-bbe8-de32964a85d3.png)

Eventually we'll need to do releases through craft, but we first need to support Hex as a target for this. Opened an issue to track that in the craft repo: https://github.com/getsentry/craft/issues/409

**Comment by sl0thentr0py** [comment]
https://hex.pm/docs/publish#publishing-from-ci
