### ISSUE TITLE
Handle events with metadata that can't be JSON-encoded

### ISSUE THREAD

**Issue by mattnenterprise** [getsentry/sentry-elixir#521]
### Environment

8.0.6

### Steps to Reproduce

* Have a configured logger backend with metadata fields that can't be JSON encoded.

```
config :logger, Sentry.LoggerBackend,
  level: :error,
  metadata: [:mfa],
  capture_log_messages: true
```
* Use Logger to log an error message.

### Expected Result

Some way to know that the event can't be sent to Sentry because it was not JSON encodable. This library could handle encoding the common types, but the user still might add something to the metadata that isn't JSON encodable. Since deadlocks can happen when logging in a logger maybe send an event to Sentry that another event can't be JSON encoded ?

### Actual Result

Logged error is not sent to Sentry and there is no indication to why.

### Notes

This issue is very important to us as we have missed multiple errors in production not knowing they were happening.

I think this is related to #520 since pids are also not JSON encodable by default.

**Comment by isaacsanders** [comment]
I've handled this problem with something like this:

```elixir
  def process_metadata({:file, file}) do
    [file: to_string(file)]
  end

  def process_metadata({:crash_reason, {reason, stacktrace}}) do
    if Exception.exception?(reason) do
      [
        crash_reason: Exception.message(reason),
        stacktrace: Exception.format_stacktrace(stacktrace)
      ]
    else
      [
        crash_reason: Exception.format_exit(reason),
        stacktrace: Exception.format_stacktrace(stacktrace)
      ]
    end
  end

  def process_metadata({key, value})
      when is_pid(value) or is_reference(value) or is_port(value) do
    {module, function} =
      cond do
        is_pid(value) ->
          {:erlang, :pid_to_list}

        is_reference(value) ->
          {:erlang, :ref_to_list}

        is_port(value) ->
          {:erlang, :port_to_list}
      end

    [
      {key,
       module
       |> :erlang.apply(function, [value])
       |> to_string}
    ]
  end

  def process_metadata({key, value}) do
    case Jason.encode(value) do
      {:ok, _encoded} ->
        [{key, value}]

      {:error, _reason} ->
        [{key, inspect(value)}]
    end
  end
```

**Comment by marcandre** [comment]
Quite a bug, very risky, and it's not limited to `Sentry.LoggerBackend`.

If you explicitly call `Sentry.capture_message` with non-encodable extra parameters, it will not generate a sentry error.

You will get a logger entry, but only of level `warn`.

Example: we forgot to destructure `error = {:error, "oops"}`, so `Sentry.capture_message("...", %{extra: %{..., error: error}}` never called Sentry and instead we get:
```
[warning] Failed to send Sentry event. Unable to encode JSON Sentry error - %Protocol.UndefinedError{protocol: Jason.Encoder, value: {:error, "Oops"}, description: "Jason.Encoder protocol must always be explicitly implemented"} 
```
