### ISSUE TITLE
Fix default environment name

### ISSUE THREAD

**Issue by dvic** [getsentry/sentry-elixir#524]
Because `Mix.env()` is [by default `:prod` for dependencies](https://hexdocs.pm/mix/Mix.Tasks.Deps.html#module-dependency-definition-options), locally, the default Sentry environment is `:prod`, which is not intuitive when you run an app locally in `dev` mode.

I think the intended behavior was to use the Mix env of the parent app but that's not what's happening right now (not sure if it's possible to get it).

## Edit from Andrea (maintainer)

We should require `:environment_name` to be set, I agree. Let's do a few things.

```[tasklist]
### Tasks
- [x] Support `SENTRY_ENVIRONMENT_NAME` and fall back to `SENTRY_ENVIRONMENT` as environment variables, to comply with other Sentry SDKs. This is not a breaking change.
- [ ] Require `:environment_name` to be set, and raise if it isn't. This is a breaking change.
```

**Comment by isaacsanders** [comment]
This is also strange, because this library uses `SENTRY_ENVIRONMENT_NAME`, not `SENTRY_ENVIRONMENT` like all other libraries do.

**Comment by yordis** [comment]
Kind of related to https://github.com/getsentry/sentry-elixir/issues/503

The whole configuration managements needs some love
