### ISSUE TITLE
excluded_domains doesn't work in elixir

### ISSUE THREAD

**Issue by sonic182** [getsentry/sentry-elixir#527]
Using elixir and specifying a domain when logging, it doesn't exclude, because elixir uses `:elixir` domain as first key always, and sentry package only checks the first key versus the list specified in config

![image](https://user-images.githubusercontent.com/4070466/207591044-bd4822e5-92e0-4c8c-9030-ed9e80dffbc2.png)

Solution in pr: https://github.com/getsentry/sentry-elixir/pull/526

**Comment by whatyouhide** [comment]
This was closed in #508.
