### ISSUE TITLE
How to handle Phoenix.NotAcceptableError

### ISSUE THREAD

**Issue by grantwest** [getsentry/sentry-elixir#528]
There are bots sending scanning requests to our phoenix server. They are sending json requests to pipelines that only support html. 

### Environment

Elixir 1.13.4
Sentry 8.0.6
Phoenix 1.6.14

### Steps to Reproduce

In the router `plug(:accepts, ["html"])`
Then send a request that accepts json:
```
curl -H 'Accept: application/json' -H 'Accept-Encoding: gzip' http://localhost:4000/the/path/doesnt/matter
```

Phoenix does not log an error when this happens, instead it returns 406 because the `plug_status` is set in the `Phoenix.NotAcceptableError` here: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/exceptions.ex#L15

The Sentry.PlugCapture does send an error to Sentry though. These are not actionable errors and we would prefer to not have them in Sentry. How should this be handled? We can't really stop anyone from sending these requests. Maybe we should be able to configure Sentry.PlugCapture to ignore certain exceptions? Or something else?

**Comment by aselder** [comment]
Do you really want this being logged to Sentry? This happens to every web app countless times per day as bots/scrapers/etc try stuff. As a developer, what action are you going to take in response to this error? Even though an exception is being thrown internally, the request is being handled properly and an appropriate response returned to the client.

**Comment by grantwest** [comment]
It IS being logged to Sentry and no we don't want it to be logged to Sentry.

**Comment by aselder** [comment]
Sorry, I misread... Easiest way to this is to add a `filter` option to your sentry config and pass it a module that defines a `exclude_exception?` function...

Here's what mine looks like:

```
defmodule Monitoring.SentryEventFilter do
  @moduledoc """
  This module implements our Sentry filtering rules.

  Any exception listed in ignore_exceptions will not be sent.
  Any exception that has an associated plug_status less that 500 will also filtered
  """

  @behaviour Sentry.EventFilter

  @ignored_exceptions [
    Phoenix.NotAcceptableError,
    Phoenix.Router.NoRouteError,
    Plug.Parsers.RequestTooLargeError,
    Plug.Parsers.BadEncodingError,
    Plug.Parsers.ParseError,
    Plug.Parsers.UnsupportedMediaTypeError,
    Plug.CSRFProtection.InvalidCSRFTokenError,
    Plug.Static.InvalidPathError,
    TenantWeb.CollectionLive.InvalidPageError
  ]

  def exclude_exception?(%x{}, :plug) when x in @ignored_exceptions do
    true
  end

  # Exclude exceptions that have a 3xx and 4xx codes associated with them
  def exclude_exception?(exception, _) do
    Plug.Exception.status(exception) < 500
  end
end
```

**Comment by whatyouhide** [comment]
Closing this since it can be handled with the `Sentry.EventFilter`, as mentioned in https://github.com/getsentry/sentry-elixir/issues/528#issuecomment-1405802835.

Plus, see #550: if we merge that, then it'll be filtered out by default.
