### ISSUE TITLE
Crashes inside of `GenServer.init/1` callback not being reported

### ISSUE THREAD

**Issue by bmurphy23** [getsentry/sentry-elixir#542]
### Environment

`sentry_elixir 8.0.6`

Relevant section of `config/env/dev.exs`:
```elixir
config :logger,
  level: :debug,
  backends: [:console, Sentry.LoggerBackend]

config :logger, Sentry.LoggerBackend, capture_log_messages: true, level: :error
```

This is not a Phoenix project. Nothing is hooked up to Phoenix or Plug, or any similar configuration.

### Steps to Reproduce

1. Configure Sentry to report errors. Whether or not `Sentry.LoggerBackend` is configured with `:capture_log_messages` seems to have no impact on the actual result.
2. Have a module that implements the `GenServer.init` callback fail. Even something as simple as `1 = 2` in `init` will suffice.
3. You can attempt to capture the results: `{:ok, pid} = MyModule.start_link()`, or simply call `MyModule.start_link()`. Additionally, the difference between `start` and `start_link` seems to have no effect.

### Expected Result

I expect that the GenServer will crash, and that the result will be reported to Sentry according to the configuration. 

### Actual Result

The GenServer does indeed crash, but no error is reported to Sentry. However, if `GenServer.init` results in a `handle_continue` call, and the `handle_continue` call crashes, the error **does** get reported. I went ahead and did some rudimentary print debugging, and it seems like `Sentry.LoggerBackend.handle_event` is not getting called specifically for `init` crashes. I feel like this may have a similar root cause as #485, but am not well-versed enough in the depths of Elixir/OTP to accurately comment on that.

It seems like when `init` fails, the error is wrapped in a tuple, which is then passed back as the return value for `start_link`. When matching on the return value with `{:ok, pid}`, and `start_link` returns `{:error, error_info}`, a `MatchError` is raised, as expected. However, not even this error is getting reported, and I feel like it should be regardless of what's going on in `init`.

**Comment by whatyouhide** [comment]
Enabling SASL reports (as described in #485) fixes this in my tests. Sadly, this is out of our control, because the issue is that we're doing this via logger handlers/backends, so only what gets to those is something we can report to Sentry.

Thanks anyways! 💟
