### ISSUE TITLE
Possibility of closer integration with Logger

### ISSUE THREAD

**Issue by ruslandoga** [getsentry/sentry-elixir#559]
Right now `Sentry.LoggerBackend` looks like a second citizen, with `Sentry.PlugCapture` and `Sentry.PlugContext` getting all of the attention. I wonder if there is any interest in seeing it being reversed:

- `Sentry.LoggerBackend` could become the default way to use this Sentry client
- `Sentry.PlugCapture` and co. could be replaced with custom plugs using helpers to populate the logger metadata

This would potentially make Sentry easier to use in non-Plug projects (like LiveView), allow users to modify what is logged in HTTP failures (instead of changing `Sentry.PlugCapture`), and catch more error-level information (thanks to integrating with Logger from the start).

**Comment by ruslandoga** [comment]
I imagine something like this:

```elixir
config = [
  metadata: :all,
  level: :warning,
  dsn: System.fetch_env!("SENTRY_DSN")
]

:ok = :logger.add_handler(:sentry, Sentry, Map.new(config))

defmodule AppWeb.Endpoint do
  use Phoenix.Endpoint
  
  # ...
  plug :sentry_context
  # ...
  
  def sentry_context(conn) do
    # ip, path, etc.
    Sentry.Context.from_plug_conn(conn)
    # custom part, this could be made nicer with helpers
    %{sentry: sentry} = metadata =  :logger.metadata()
    user_context = %{id: conn.assigns.current_user.id}
    sentry = Map.update(sentry, :user, user_context , fn prev -> Map.merge(prev, user_context) end)
    sentry = # ... param scraping
    :logger.metadata(%{metadata | sentry: sentry})
  end
end
```

**Comment by whatyouhide** [comment]
So, `Sentry.LoggerBackend` is not a second-class citizen IMO. Both the Logger backend and the Plug-specific stuff rely on `Sentry.capture_exception/2` and/or `Sentry.capture_message/2`, so I don't think there's anything to do here 😉 

Thank you anyways! 💟
