### ISSUE TITLE
Conflict with assert_error_sent/2?

### ISSUE THREAD

**Issue by JoshSmith** [getsentry/sentry-elixir#58]
In my application's `Router`, if I `use Sentry.Plug`, then any test that uses `assert_error_sent/2` fails to pass.

Does the Sentry plug's error handling conflict with this in some known way?

**Comment by JoshSmith** [comment]
It looks as though your `handle_errors` which calls out to `Sentry.capture_exception` is not continuing to raise the exception.

You can see some discussion about this in relation to Rollbax here: https://github.com/elixir-lang/plug/issues/444

**Comment by mitchellhenke** [comment]
Thanks for the report.  ❤️

Could you set up an example project showing this?  I tried to replicate with a Phoenix application, and was able to use `assert_error_sent` successfully.  My understanding of [Plug.ErrorHandler](https://hexdocs.pm/plug/Plug.ErrorHandler.html) is that by default it will re-raise once the `handle_errors` callback has executed, and so it shouldn't cause any conflict with a test case using `assert_error_sent`.

**Comment by JoshSmith** [comment]
@mitchellhenke yes, I know it's not just a minimal setup but you can find the branch for this PR https://github.com/code-corps/code-corps-api/pull/223 and pull it down. If you use Docker should be relatively trivial to get it up and running for testing purposes.

Let me know if I can help more there. Don't want to make the bug verification too burdensome.

**Comment by mitchellhenke** [comment]
After some research, I am not sure if this is an issue with how we are using `Plug.ErrorHandler` within a Phoenix application, or if this is a Phoenix issue.  I am going to continue investigating to find a fix, because it's definitely not behaving as I would expect.

**Comment by JoshSmith** [comment]
@mitchellhenke okay, happy to help if you'd like/need.

**Comment by mitchellhenke** [comment]
@JoshSmith it looks to be a bug in Phoenix.  I opened an issue [here](https://github.com/phoenixframework/phoenix/issues/1928), and it should be fixed on master now.  I suspect experiencing the above bug means that there are some content-type inconsistencies in the application, but I'm not positive.

If you could try Phoenix master with: `{:phoenix, "1.3.0-dev", github: "phoenixframework/phoenix", override: true},` and let me know if everything is good, that would be great.

**Comment by JoshSmith** [comment]
@mitchellhenke yes, I'll try a little later today and report back. Thanks!

**Comment by JoshSmith** [comment]
@mitchellhenke now I get a new failure (hitting the new code) on my failures:

```
     expected error to be sent as 404 status, but got an error with no response from:

     ** (FunctionClauseError) no function clause matching in Phoenix.Template.HTML.encode_to_iodata!/1
```

Is there something else I'm doing wrong?

**Comment by mitchellhenke** [comment]
@JoshSmith is that with or without Sentry set up?

**Comment by JoshSmith** [comment]
@mitchellhenke it's with that branch on the referenced PR, so with Sentry set up. You should be able to pull down, since it's Dockerized, and verify in ~5 minutes there.

**Comment by JoshSmith** [comment]
Also happy to screenshare or something if it's helpful.

**Comment by mitchellhenke** [comment]
@JoshSmith it looks like the tests also fail on develop without Sentry

**Comment by JoshSmith** [comment]
@mitchellhenke that's bizarre. They shouldn't be, or else my CI is borked somehow. Let me investigate and figure out what's happening.

**Comment by JoshSmith** [comment]
I'm guessing that change in Phoenix changed something else that now makes them break where they were passing before.

**Comment by mitchellhenke** [comment]
@JoshSmith that's my hunch as well.  I'm not sure if it's due to a dependency, or something else, but it does not appear to be related to Sentry.

**Comment by JoshSmith** [comment]
@mitchellhenke thanks, I went through some dependency resolution fun the other day. Will test this again today.

**Comment by mitchellhenke** [comment]
@JoshSmith cool, let me know if there's any way I can help.

**Comment by JoshSmith** [comment]
Updated in the Phoenix issue: https://github.com/phoenixframework/phoenix/issues/1928

If you concur and could reopen that would be helpful!

**Comment by JoshSmith** [comment]
The actual issue here was not in this package but in how I was handling `json-api` error view rendering.

Described in this issue https://github.com/AgilionApps/ja_serializer/issues/176 and closed by https://github.com/AgilionApps/ja_serializer/pull/177
