### ISSUE TITLE
Make `Sentry.HTTPClient.child_spec/1` callback be optional

### ISSUE THREAD

**Issue by wingyplus** [getsentry/sentry-elixir#587]
My use-case is I want to use Tesla as an HTTP Client and use pre-configure Finch that is already defined in the application tree. But the `HTTPClient` requires the implementor to implement `child_spec`. 

My proposal is to make `child_spec` optional and attach it to the supervisor if it's available. I can help working on this if you're ok with this proposal. :)

Thanks

**Comment by whatyouhide** [comment]
@wingyplus yes, I think this is a good idea. PRs are welcome, absolutely! 🙏
