### ISSUE TITLE
Backward compatible with old Sentry

### ISSUE THREAD

**Issue by wingyplus** [getsentry/sentry-elixir#588]
My service are using Sentry 9, self-hosted and it looks very old. After I upgrade it to 8.1, the library breaks because the library changing to use Envelope API but on the previous version, it use Store API. 

I'm not sure if there's any way to make it compatible with this?

**Comment by whatyouhide** [comment]
I’m not following. You're using Sentry 9, and sentry elixir 8.1?

Also, we'll release sentry-elixir 9.0.0 in a bit, which should fix incompatibilities.

**Comment by whatyouhide** [comment]
That's weird because 403 is `Forbidden`. Anyways, sure, it could be the envelope. Sorry! I would advise to stay on sentry-elixir 8.0.6 or upgrade Sentry itself, maybe?

**Comment by whatyouhide** [comment]
Closing this for now to clean up the tracker 🙃
