### ISSUE TITLE
Are use_error_logger and Sentry.Plug mutual exclusive?

### ISSUE THREAD

**Issue by alex88** [getsentry/sentry-elixir#59]
I don't understand by the docs if the

```
config :sentry,
  use_error_logger: true
```

is enough to catch all the errors, or I need to also also with

```
use Plug.ErrorHandler
use Sentry.Plug
```

just in case the plug doesn't intercept all the errors?

I mean, it `use_error_logger` something that works only for what `Sentry.Plug` doesn't catch? Or using it alone is enough to work both outside of Plug and inside?

**Comment by mitchellhenke** [comment]
They aren't mutually exclusive.

[Plug.ErrorHandler](https://hexdocs.pm/plug/Plug.ErrorHandler.html) is used to catch errors that happen during a Plug response.

`use_error_logger` sets up a [Logger backend](http://elixir-lang.org/docs/stable/logger/Logger.html#module-backends) that receives error events from any system that reports one (could be something like a Redis worker process, or other GenServer process crashing).

**Comment by alex88** [comment]
Gotcha, thank you

**Comment by mitchellhenke** [comment]
@alex88 you bet :)
