### ISSUE TITLE
Issues with large codebase and source code context

### ISSUE THREAD

**Issue by Miradorn** [getsentry/sentry-elixir#615]
Hi there and thanks for the great work on this amazing library ❤️ 

This is not strictly a feature request, but more of me screaming "help" regarding the use of source-code context

If I'm understanding the code correctly, what this library is doing, it basically adding the content of all files into a map of strings, right?
The problem: We have a pretty big codebase (smth around 6k modules i think as of now), and we had to disable the feature since it started failing our builds due to memory/cpu consumption.

With that context: is there a "better" way we could enable this feature (e.g. copying the sources somewhere into the release, or leveraging the gitlab integration on sentry?
If you have any ideas I might also be able to put some time in to try to implement something here.

Thanks again!

**Comment by whatyouhide** [comment]
Hey @Miradorn! Since #632, this should be better. Now, you can package your source code into a binary file in your release (inside `:sentry`'s `priv` directory). Can you try to run `mix sentry.package_source_code --debug` in your big app and report the results? 🙃
