### ISSUE TITLE
Sentry.PlugContext does not follow Plug.RequestId recommendations

### ISSUE THREAD

**Issue by halostatue** [getsentry/sentry-elixir#623]
### Environment

8.1, but the affected code exists in trunk

This isn't a *bug* as such, but it appears that Sentry.PlugContext is not following Plug.RequestId recommendations for accessing the found or created `request_id`.

Specifically, [sentry/plug_context.ex:145](https://github.com/getsentry/sentry-elixir/blob/a4c4a6bb4e4ebea83d176259c722ea02bc51ccc7/lib/sentry/plug_context.ex#L145) calls `get_resp_header/2`

```elixir
        "REQUEST_ID" => Plug.Conn.get_resp_header(conn, request_id) |> List.first()
```

The [documented recommendation](https://hexdocs.pm/plug/Plug.RequestId.html) for `Plug.RequestId` is:

> You can also access the request_id programmatically by calling Logger.metadata[:request_id]. Do not access it via the request header, as the request header value has not been validated and it may not always be present.

Switching to obtaining the data from `Logger.metadata()[:request_id]` would make the need for the `request_id_header` plug parameter obsolete. Once elixir-plug/plug#1172 is released, then the `request_id` would be available in `conn.assigns`, but you would still need to get the assigned key.

**Comment by halostatue** [comment]
Would it be worth considering `Logger.metadata()[:request_id] || (Plug.Conn.get_resp_header(conn, request_header) |> List.first())`?

**Comment by whatyouhide** [comment]
That would be a breaking change in behaviour because we'd be ignoring the `:request_id_header` option for the plug (that is, if the `:request_id` Logger meta is present we wouldn't read the specified header).
