### ISSUE TITLE
Update docs to make it easier to start Sentry for the first time

### ISSUE THREAD

**Issue by whatyouhide** [getsentry/sentry-elixir#628]
Adding the sentry config to `prod.exs` config as mentioned in the docs is not enough, the `dev` environment will crash (complaining that `environment_name` config is missing) if I do not add a general config in `config.exs`. So I added the following in `config.exs`:
```elixir
config :sentry,
  included_environments: [:prod],
  environment_name: :prod
```

This is not explained in the docs.

_Originally posted by @thojanssens in https://github.com/getsentry/sentry-elixir/issues/627#issuecomment-1778564193_

**Comment by thojanssens** [comment]
I think this can be closed at the docs in the main readme mention to add the config in `config.exs`

**Comment by whatyouhide** [comment]
Correct!
