### ISSUE TITLE
Do not capture certain exceptions

### ISSUE THREAD

**Issue by matt-g-adams** [getsentry/sentry-elixir#63]
Currently, sentry is capturing Elixir.Phoenix.Router.NoRouteError, which is not what we'd prefer. Is it reasonable for there to be a config key like `excluded_exceptions`?

**Comment by mitchellhenke** [comment]
Capturing from `Plug.ErrorHandler`?

**Comment by myronmarston** [comment]
This is happening for us, too, and I'd love a way to exclude it.

> Capturing from Plug.ErrorHandler?

Yep.

**Comment by mitchellhenke** [comment]
@myronmarston would it apply only to Plug errors, or also to `Sentry.capture_exception/2` and  `Sentry.Logger`?

**Comment by myronmarston** [comment]
> @myronmarston would it apply only to Plug errors, or also to Sentry.capture_exception/2 and Sentry.Logger?

We are currently only using the plug handler, but I expect we'll use the others in the future.

Could you support a filtering function that would allow users to flexibly define filtering logic? If so, you could pass a `source` argument, which would allow people to do things like:

``` elixir
# in config.exs
config :sentry, :filter_module, MyApp.SentryFilter

# in sentry_filter.ex
defmodule MyApp.SentryFilter do
  @behaviour Sentry.Filter

  def exclude_exception?(:plug, %Elixir.Phoenix.Router.NoRouteError{}), do: true
  def exclude_exception?(_, _), do: false
end
```

By passing both the exception and the source (e.g. `:plug`, `:logger` or `:capture_exception`) it allows the user to filter exceptions however they want.

**Comment by jeregrine** [comment]
@myronmarston that sounds good to me.
