### ISSUE TITLE
Avoid global config (or allow to override it)

### ISSUE THREAD

**Issue by thojanssens** [getsentry/sentry-elixir#639]
Following https://github.com/getsentry/sentry-elixir/pull/636

It is recommended to avoid global config where multiple parts or dependencies or apps want to use the library in different ways: https://hexdocs.pm/elixir/1.15.7/library-guidelines.html#avoid-application-configuration

With the current global config, the library forces the user to have a single http client across the applications and dependencies.

A good example is how we can configure the time zone library in Elixir.
Through the config:
```elixir
config :elixir, :time_zone_database, MyTimeZoneDatabase
```
or through the Calendar:
```elixir
Calendar.put_time_zone_database(MyTimeZoneDatabase)
```
or pass the database to the DateTime functions:
```elixir
DateTime.now("America/Sao_Paulo", MyTimeZoneDatabase)
```

In a similar way, with maybe a little creativity, we could figure out a way for the user to pass the http client as an argument/option in the code.

Example scenario: multiple apps independently deployed, having http clients with different settings. Note however that this issue is not limited to Umbrella apps.

**Comment by whatyouhide** [comment]
The only thing we can do here without major breaking is to support options, as the `DateTime.now/2` example shows. I will work on this, however my recommendation is still to absolutely do something like I documented in https://github.com/getsentry/sentry-elixir/commit/0133fdc57de246ff42e41e1d534d73277c522788. That's gonna lead to a more modular design of your system overall, IMO.

**Comment by whatyouhide** [comment]
Also, @thojanssens yes, I’m in the Elixir team and have participated in writing those guides, so I’m aware of the issue of global config. However, this library has been out for a while so we also need to be mindful of what we change to try and keep the experience of updating and maintaining smoother for users.

**Comment by thojanssens** [comment]
Referring to https://github.com/getsentry/sentry-elixir/commit/0133fdc57de246ff42e41e1d534d73277c522788, it didn't really address my specific issue, which I wrote in more details here: https://github.com/sneako/finch/issues/247#issuecomment-1793327245

In short, Finch needs to be started. The sentry library forces me to start Finch in another umbrella, and as I wrote in that issue:
> => I'm annoyed because it seems I introduce an unnecessary complexity: a new supervision tree, a start-able dependency, and I do not even need it for release/production but only to satisfy the problem in development (i.e. running all apps and testing all apps simultaneously).

I went for this solution:
```elixir
defmodule Shared.Finch do
  def child_spec(opts) do
    name = Keyword.fetch!(opts, :name)

    case Process.whereis(name) do
      nil ->
        Finch.child_spec(opts)

      _pid ->
        # the :id needs to be unique per supervisor. It’s fine if it’s opts[:name].
        %{
          id: name,
          start: {Task, :start_link, [fn -> :ok end]},
          restart: :temporary
        }
    end
  end
end
```
to avoid having to introduce a new supervision tree in my app.

The documentation you added is not wrong though, maybe a little obvious, but if you want you can leave it as is.

Do you have anything to add or we close this? Thank you very much for all the work done<3

**Comment by thojanssens** [comment]
I'm a little tired, I suggested to close this but I forgot that the point still remains: ideally we eliminate global config such as the http client:D

**Comment by whatyouhide** [comment]
> I went for this solution

I’m confused. If you have an application in the umbrella whose job is only to wrap Sentry and start the HTTP client, you shouldn't need that. The app will start only once and hence start the HTTP client only once?

**Comment by thojanssens** [comment]
> and start the HTTP client

That's what I dislike. Because of Sentry's global config (and so many other libraries following the same way: global configuration), I need to introduce a new supervisor in a shared app (as Finch needs to be started).

I'll demonstrate with an example. Independently-deployable apps put in an umbrella for the conveniences:
```
- umbrella root
  - foo_app
  - bar_app
  - baz_app
  - shared
```

1. Sentry's global config forces me to use a single Finch instance, so now I need to add a supervisor in `shared` (it contains just some simple shared modules, but now I need to add an `application` to start Finch for sentry).
And I would need to do this just to make it work in development, to run commands at the root of the umbrella such as:
* mix run --no-halt
* mix test
It is not necessary in production because the apps are independently deployed, so in prod having `{Finch, name: Shared.Finch}` will not lead to the `:already_started` error and the release will happen without an error. However my CI for example fails with `:already_started` as a `mix test` is executed at the root and starting all the apps in development with `mix run --no-halt` will fail too.

2. The solution I am using above (custom `child_spec`) allows me to start a Finch instance with the same name from multiple apps in their supervision trees `{Shared.Finch, name: Shared.Finch}`. If `Shared.Finch` was already started, I will just ignore and so prevent the `:already_started` error.
This allows me to avoid creating a new application/supervision tree in the shared dependencies just to satisfy development (again, in prod the apps are independently deployed so I would have the `already_started` error only in development and test).

As to why it bothers me that much to start Finch from the dependency and create an application/supervision tree:

> => I'm annoyed because it seems I introduce an unnecessary complexity: a new supervision tree, a start-able dependency, and I do not even need it for release/production but only to satisfy the problem in development (i.e. running all apps and testing all apps simultaneously).

**Comment by thojanssens** [comment]
(btw when I wrote dependency above, I refer to the shared app in the umbrella that the other apps depend on)

**Comment by whatyouhide** [comment]
IMO, you are looking at Erlang/OTP applications wrong. Dependencies that start a supervision tree vs ones that don't are not really different. In fact, I would argue that if a dependency starts to use a supervision tree, I wouldn't consider it a breaking change. Take [Postgrex](https://github.com/elixir-ecto/postgrex) as an example: would you think it has a supervision tree? If so, for what, considering it's just a database library and that you have to start connections manually (`Postgrex.start_link/1`)? But as a matter of fact, it [does have one](https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/app.ex) that it uses to start caches, GenServers, and whatnot.

> I need to introduce a new supervisor in a shared app

The thing is that I don't think this is an issue. Or at least, I can't see why this would be an issue in your setup either. Let `shared` start its sup tree and let it start the Finch pool. What issues does that cause?
