### ISSUE TITLE
Flaky RuntimeError with tests

### ISSUE THREAD

**Issue by beerlington** [getsentry/sentry-elixir#641]
### Environment

Elixir 1.15
OTP 25
Sentry 9.10

mix.exs contains: 

```ex
{:sentry, "~> 9.1"},
```

### Steps to Reproduce

I'm upgrading from Sentry 8.1.0 to 9.1.0 and I'm getting runtime errors when our test suite runs. I can reproduce it locally by running our entire test suite with `mix test`, but when I rerun it with `mix test --failed`, the same tests do not fail a second time.

When I first updated the package I got this error when running `mix test`:

```
** (Mix) Could not start application sentry: exited in: Sentry.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) :environment_name must be set in the application config or the SENTRY_ENVIRONMENT env var
            (sentry 9.1.0) lib/sentry/config.ex:126: Sentry.Config.environment_name/0
            (sentry 9.1.0) lib/sentry/config.ex:28: Sentry.Config.validate_environment_name!/0
            (sentry 9.1.0) lib/sentry/application.ex:43: Sentry.Application.start/2
            (kernel 8.5.4) application_master.erl:293: :application_master.start_it_old/4
```

We didn't have any configuration for the test environment, so I added this to our runtime.exs file:

```ex
if config_env() not in [:prod, :staging] do
  config :sentry,
    dsn: "fake-dsn",
    environment_name: config_env(),
    root_source_code_path: File.cwd!(),
    included_environments: []
end
```

I've also tried adding this to my test.exs config:

```ex
config :sentry,
  dsn: "fake-dsn",
  environment_name: config_env(),
  root_source_code_path: File.cwd!(),
  included_environments: []
```

Now I can run `mix test`, but I get seemingly random test failures.

I checked the 9.0 upgrade guide, but I didn't see anything specifically about test environments.

### Expected Result

No runtime errors.

### Actual Result

I'm getting a runtime error:

```
(RuntimeError) :environment_name must be set in the application config or the SENTRY_ENVIRONMENT env var
```

With this stacktrace:

```
(sentry 9.1.0) lib/sentry/config.ex:126: Sentry.Config.environment_name/0
(sentry 9.1.0) lib/sentry/event.ex:267: Sentry.Event.create_event/1
(sentry 9.1.0) lib/sentry.ex:374: Sentry.capture_exception/2
(app 0.1.0) lib/app/event_routing/event_routing.ex:87: App.EventRouting.get_redirect_url/3
(app 0.1.0) lib/app/event_routing/event_routing.ex:41: App.EventRouting.redirect_data/3
test/app/event_routing/event_routing_test.exs:1459: (test)
```

This is one particular example, but it changes every time I run `mix test`.

**Comment by whatyouhide** [comment]
Do you have a minimal application to reproduce this? I don't quite understand why Sentry is not picking up `:environment_name` from the config. By the way, I believe https://github.com/getsentry/sentry-elixir/issues/524 was a mistake, so I opened #642 to avoid requiring `environment_name`.

**Comment by beerlington** [comment]
I haven't tried reproducing it in a smaller app, but I suspect it would be hard to do. Our app has thousands of tests and it's only happening on a handful. The only pattern I've seen is that it usually (but not always) fails on tests that are expecting an error. 

So code like this:

```ex
assert_raise MatchError, fn ->
  # Code that should raise a MatchError
end
```

We have a few dozen of those and sometimes it's only one or two that fail with the `RuntimeError` from Sentry instead. That could be a red herring though and could just be a coincidence.

**Comment by whatyouhide** [comment]
We re-hauled the config recently, and we'll release 10.0.0 soon. This should be fixed now. In the meantime, if you want, please do give `master` a try 🙃 

In any case, I'll close this one out for now, but feel free to reopen once we release in case this is still ongoing. Thanks @beerlington! 💟

**Comment by beerlington** [comment]
@whatyouhide I just upgraded to 10+ and everything is working great. Just wanted to send a belated thanks!
