### ISSUE TITLE
Not Capturing GenServer errors

### ISSUE THREAD

**Issue by Harrisonl** [getsentry/sentry-elixir#65]
For some reason I can't get this to capture elixir based errors. For example, a GenServer termination error.

```elixir
config :sentry,
  dsn: "mydsn",
  environment_name: 'dev',
  use_error_logger: true
```

**Comment by mitchellhenke** [comment]
what environments are set in `included_environments`?  If `environment_name` doesn't match anything in `included_environments`, no exceptions will be sent.  It defaults to `[:prod]`, so `"dev"` wouldn't match.

**Comment by jeregrine** [comment]
also @Harrisonl `'dev'` is a character list. Not sure if thats a typo.

**Comment by mitchellhenke** [comment]
Happy to take a look into this with more information, but going to close for now.
