### ISSUE TITLE
Add option to capture only unhandled exceptions

### ISSUE THREAD

**Issue by sdzhong** [getsentry/sentry-elixir#665]
Currently, the Elixir SDK captures both handled and unhandled exceptions. 

Add an option to change this behavior to capture only unhandled exceptions.

**Comment by whatyouhide** [comment]
So, there are only two mechanisms through which this SDK currently captures exceptions:

1. `Sentry.LoggerHandler`
2. `Sentry.PlugCapture`

### Logger handler

In this case, we can't really know what it means for the user to have "handled" an exception. For example, if a process crashes, we report the exit reason. We can't really know if the user was monitoring that process or if they're handling the crash in any way.

### Plug

In this case, if the exception makes it to the Plug then it's always unhandled. If the user were to handle it, it wouldn't make it to the Plug in the first place.

So, I’m not sure this makes sense for the Elixir SDK?

**Comment by whatyouhide** [comment]
Btw, my comment above applies exactly the same to #666 too.

**Comment by sl0thentr0py** [comment]
@whatyouhide the semantics for handled/unhandled are very bad on our side, but what we mean is this.

* if an SDK captures and sends an exception in some integration and we re-raise the exception, that is 'unhandled' for the user
* if a user captures an exception manually in *their* user code with `Sentry.capture_exception`, that is 'handled'

this requires a `mechanism` field to be set on the exception like this
https://github.com/getsentry/sentry-python/blob/fe079c8c5a9f913f4051599b94739e859bee1339/sentry_sdk/integrations/wsgi.py#L194
https://develop.sentry.dev/sdk/event-payloads/exception/#exception-mechanism

**Comment by whatyouhide** [comment]
Aaaah, gotcha. This is about whether *Sentry* reported an issue "behind the scenes", or the user actively reported it. Awesome, on it!

**Comment by whatyouhide** [comment]
@sl0thentr0py it's unclear to me why we'd want to only want to capture **unhandled** exceptions. I'd expect the desired behavior to be an option to only capture **handled** exceptions. The idea there is that you can always just remove (or gate) calls to `capture_exception` and friends *in user code*. Instead, if we add an option to only capture handled exceptions that makes it easy to essentially "silence" unhandled exceptions that are captured by the SDK?

I also don't see a similar option in the Python or Node SDKs, FWIW.

**Comment by sl0thentr0py** [comment]
if the mechanism option is supported now, you can ignore and close this issue.
