### ISSUE TITLE
Issue event context to include exception status code

### ISSUE THREAD

**Issue by sdzhong** [getsentry/sentry-elixir#667]
Currently, issue events do not show status codes.

Add this information as context/tags to the issue event.

**Comment by whatyouhide** [comment]
@sdzhong can you elaborate on this? What do you mean by "issue event"? Do you mean that exceptions that happen within the boundaries of web requests should have the status code that the server will send to the user attached to them?

**Comment by sl0thentr0py** [comment]
we can add the response code to `contexts` like
https://github.com/getsentry/sentry-python/blob/0eb346533da224f2d6d99c87e06be5e26eaa5cf1/sentry_sdk/tracing.py#L771

**Comment by whatyouhide** [comment]
Are you folks talking about the HTTP status set in **spans**? Because the Python SDK seems to only do it for transactions and spans, not for exception or message events. cc @sl0thentr0py

**Comment by sl0thentr0py** [comment]
i'll ping @sdzhong  internally, not sure what he wants

**Comment by whatyouhide** [comment]
@sl0thentr0py have you had a chance to ping @sdzhong? I'm really not sure what we're supposed to do with this issue 🙃

**Comment by sl0thentr0py** [comment]
closing, he can reopen later if necessary
