### ISSUE TITLE
PlugContext: protocol not implemented for struct

### ISSUE THREAD

**Issue by jschaeff** [getsentry/sentry-elixir#674]
### Environment

* Elixir version (elixir -v): 1.15.7
* Erlang/OTP version (erl):  26
* Sentry version (mix deps): 10.1.0
* Operating system: Linux
* Is this an umbrella application?: no
* Release type (Distillery, mix release, Mix, etc.): mix release

### Description

In my application, I parse POST requests and build a struct with its content, which gets into the Plug context.

Sentry.PlugContext does not like this at all, it crashes with a  `Protocol.UndefinedError`.

This is a link to the code producing the behaviour. https://gricad-gitlab.univ-grenoble-alpes.fr/OSUG/RESIF/wsdataselect/-/blob/8c9a20cfcf26cbd5de238ac0633c55abb1e857d5/lib/wsdataselect/router.ex#L20
### Expected Behavior

Should'nt structs be managed by PlugContext, for instance by calling `Map.from_struct/1` ?

If not, how can I make Sentry get the context correctly ? 

### Actual Behavior

The full error is:

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for %Wsdataselect.DataRequest{quality: "B", nodata: "204", user: "anonymous", streams: [%Wsdataselect.Stream{net_id: 0, net: "FR", sta: "CIEL", loc: "01", cha: "HNZ", start: "2023-01-01T00:00:00", end: "2023-01-01T01:00:00"}], files: []} of type Wsdataselect.DataRequest (a struct). T
```

**Comment by jschaeff** [comment]
I think I managed to overcome the problem with a custom body scrubber that makes a map from structure before the actual scrubbing.

```elixir
defmodule MySentryScrubber do
  def scrub_params(conn) do
    %{conn | params:  Map.from_struct(conn.params) }
    |> Sentry.PlugContext.default_body_scrubber()
  end
```

**Comment by whatyouhide** [comment]
@jschaeff yeah, we expect params to be a map or `Plug.Conn.Unfetched.t/0`, as per the `Plug.Conn` docs. So, if you're changing the params to be a struct, you'll have to do something like you showed above for things to work. Thanks for bringing this up anyways! 🙏
