### ISSUE TITLE
Events missing request body when using Pheonix integration

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-elixir#683]
### Environment
Sentry elixir SDK v10.1.0
Phoenix	v1.7.10

### Steps to Reproduce
Setup the application with [Elixir SDK](https://docs.sentry.io/platforms/elixir/) and [Phoenix integration](https://hexdocs.pm/sentry/setup-with-plug-and-phoenix.html#for-phoenix-applications)
Have a post request result in an error/exception captured by the SDK

### Expected Result
The request body is available in the event for troubleshooting.

What you thought would happen.

### Actual Result
The body in the event is an empty JSON `{}`, the same request has a body which was successfully read by Phoenix.

Issue originally reported [here](https://sentry.zendesk.com/agent/tickets/111486)

**Comment by oliver-kriska** [comment]
I reported this issue. We don't see post requests in regular Controller and also Absinth GQL. But second one can be due to some config conflicts but regular Controller doesn't have anything special. Phoenix integration is configured exactly like is written in docs.

**Comment by whatyouhide** [comment]
Hi @oliver-kriska, thank you for reporting this!

  1. I set up a brand new Phoenix application and added `:sentry` version 10.1.0.
  2. I added a `POST` route to the router
  3. The controller action to handle the newly-added `POST` route raises an error (just a `raise "some error"`)

If I hit the new endpoint to trigger the error, the body is in the error in Sentry as expected:

```
curl -X POST -H 'Content-Type: application/json' 'http://localhost:4000/api/test' -d '{"foo": false}'
```

![CleanShot 2024-01-18 at 12 48 43@2x](https://github.com/getsentry/sentry-elixir/assets/3890250/f4283f56-8000-49df-b5b6-e2998816b7c9)

### Troubleshooting

Could you help me troubleshoot this by telling me

1. What your router looks like
2. What your Phoenix endpoint looks like
3. What your controller action looks like
4. What the request you're issuing is

Thank you!

**Comment by oliver-kriska** [comment]
while I was writing you our code examples I figured out that issue is that we have json parser for API requests in router and not in endpoint. Thanks to that Sentry doesn't have parsed request's body. Sorry for taking your time.
