### ISSUE TITLE
[elixir] Support for "Metrics"

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-elixir#692]
### Description
Metrics! Sentry will support Metrics finally! First we need all of our SDKs to support Metrics, including the Elixir SDK

#### Requirements:

- [ ] API for sending Metrics
- [ ] Metrics Summary
- [ ] Code location
- [ ] Tag normalization

#### Document(s)
[Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/)
[SDK Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/sending-metrics-sdk/)
[Product Specs](https://develop.sentry.dev/sdk/metrics/)

**Comment by whatyouhide** [comment]
For now, we're not actively working on this in this SDK, waiting for a few cycles here.

**Comment by whatyouhide** [comment]
Ah yes sure my bad 👍

**Comment by grantwest** [comment]
Any idea on when this work might happen?

**Comment by whatyouhide** [comment]
Deferring to @sl0thentr0py and @stephanie-anderson for this 🤓

**Comment by HazAT** [comment]
We going to revisit this plan, currently the idea is that Metrics are just attributes on a Span. So, as described in the initial comment, it for sure is not gonna happen like this.
