### ISSUE TITLE
Support for "Cron Monitors"

### ISSUE THREAD

**Issue by hkrutzer** [getsentry/sentry-elixir#694]
Some SDKs have support for the new Cron Monitoring feature, e.g. https://docs.sentry.io/platforms/javascript/guides/nextjs/crons/. Could this SDK support it as well? I think libraries like Quantum are quite popular. Perhaps it could work with `:telemetry.span`?

**Comment by whatyouhide** [comment]
I will take a look at this 👁️

**Comment by whatyouhide** [comment]
This has been closed in #697, #698, #699.
