### ISSUE TITLE
Flaky test suite after migration from 9.1.0 to 10.2.0

### ISSUE THREAD

**Issue by ulissesalmeida** [getsentry/sentry-elixir#703]
### Environment

Elixir: v1.15.7
otp: 26.1.2
Sentry 10.2.0

### Steps to Reproduce

When migrating from 9.1.0 and put this config on my `config/test.exs` file :

```elixir
config :sentry, test_mode: true, dsn: nil
```

### Expected Result

The suite would pass as normally.

### Actual Result

Flaky errors like this one

```
     ** (ArgumentError) errors were found at the given arguments:
     
       * 1st argument: the table identifier does not refer to an existing ETS table
     
     code: assert {{code}}
     stacktrace:
       (stdlib 5.0.2) :ets.update_element(Sentry.Dedupe, 14786931, {2, 1710859335364})
       (sentry 10.2.0) lib/sentry/dedupe.ex:23: Sentry.Dedupe.insert/1
       (sentry 10.2.0) lib/sentry/client.ex:158: Sentry.Client.maybe_dedupe/1
       (sentry 10.2.0) lib/sentry/client.ex:123: Sentry.Client.send_event/2
```

Then I tried this config:

```
config :sentry, test_mode: true, dsn: nil, dedup_events: false, send_result: :none
```

And everything seems to be more stable. No flaky errors. 

Is this how is supposes to be?

**Comment by whatyouhide** [comment]
@ulissesalmeida hey Ulisses, long time no chat! 🙃 

Are you starting the `:sentry` app in the `test` Mix env?

> Is this how is supposes to be?

Nope 😬

**Comment by ulissesalmeida** [comment]
@whatyouhide Long time ❤️  I have been hiding below my desk for a while 🤣 

> Are you starting the :sentry app in the test Mix env?

Thank you for asking that. I thought not. But, after investigating the code, I noticed that we're stopping and starting the sentry app for changing the configuration to test with Bypass. 😅  I'll fix that, it is supposed to use the `Config.change` function right? After that, I'll come back  here to tell if this weird behaviour is still happening.

**Comment by whatyouhide** [comment]
@ulissesalmeida yes you should use [`Sentry.Config.put_config/2`](https://hexdocs.pm/sentry/10.2.0/Sentry.html#put_config/2) now. However, there's a whole new `Sentry.Test` module in 10.2.0 you might want to look at 😉

**Comment by ulissesalmeida** [comment]
@whatyouhide Using the put config function made our test suite be stable(we're no stopping or starting the app anymore).

We'll soon move the current tests to use the new test module, the new module looks gorgeus.

Thank you for your quick reply and help.

❤️ 💛 💜 💚
