### ISSUE TITLE
Output of `mix sentry.send_test_event` has no environment name

### ISSUE THREAD

**Issue by krns** [getsentry/sentry-elixir#707]
### Environment

What version are you running? Etc.

- OTP 26.2.3
- Elixir 1.16.2
- sentry-elixir 10.2.1

### Steps to Reproduce

- Configure sentry (set DSN and `environment_name` to `staging`)
- Sending a test event via `mix sentry.send_test_event`

### Expected Result

Display current `environment_name` (`staging`) in the output of the mix command.

### Actual Result

```
root:/opt/app# mix sentry.send_test_event
Client configuration:
server: <url>
public_key: <public_key>
secret_key:
current environment_name: ""
hackney_opts: [pool: :sentry_pool]
```

Although the current environment is set to `staging` the output shows `""`. In the iex I get the correct value for `environment_name`:

```
iex(5)> Sentry.Config.environment_name()
"staging"
```

**Comment by whatyouhide** [comment]
Hi @krns thanks for the issue.

Are you running `iex` in the same Mix env as `mix sentry.send_test_event`? Where are you configuring the environment?

I cannot reproduce this within this repo, for example:

```
→ mix sentry.send_test_event
Client configuration:
current environment_name: "dev"
hackney_opts: [pool: :sentry_pool]

Event not sent because the :dsn option is not set (or set to nil)
```

**Comment by krns** [comment]
We are setting the `dsn` and `environment_name` in the runtime config to distinguish between `staging` and `production` environment.

**Comment by whatyouhide** [comment]
Can you try a patch in another branch I just pushed up by doing

```elixir
{:sentry, github: "getsentry/sentry-elixir", branch: "al/loadconfig"}
```

in your deps instead of getting `:sentry` from Hex?

**Comment by krns** [comment]
Just tried you branch, but the output is the same:

```
root:/opt/app# mix sentry.send_test_event
Client configuration:
current environment_name: ""
hackney_opts: [pool: :sentry_pool]

Event not sent because the :dsn option is not set (or set to nil)
```

**Comment by whatyouhide** [comment]
@krns do you have a way to reproduce this with a minimal app, so I can give it a try?

**Comment by krns** [comment]
I will try to isolate the problem and get back to you.

**Comment by krns** [comment]
Here is the minimal app for reproduction: https://github.com/krns/sentry_test

To reproduce you have to setup the project, `mix deps.get` and set sentry env via `export SENTRY_ENV='staging'`. When you execute the mix task via `mix sentry.send_test_event` the `environment_name` should be `""`.

```
⋊> ~/c/sentry_test on main ◦ export SENTRY_ENV='staging'                                                                                                                                             13:29:28
⋊> ~/c/sentry_test on main ◦ mix sentry.send_test_event                                                                                                                                              13:29:29
Client configuration:
current environment_name: ""
hackney_opts: [pool: :sentry_pool]

Event not sent because the :dsn option is not set (or set to nil)

⋊> ~/c/sentry_test on main ◦ iex -S mix                                                                                                                                                              13:29:32
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Interactive Elixir (1.16.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Sentry.Config.environment_name()
"staging"
```

**Comment by whatyouhide** [comment]
@krns I was able to reproduce it, thanks. #708 fixes it, can you give that a try?

**Comment by whatyouhide** [comment]
Great. We'll get a release going in the next few days.
