### ISSUE TITLE
No fallback to MIX_ENV

### ISSUE THREAD

**Issue by omin** [getsentry/sentry-elixir#71]
Should fallback to MIX_ENV=dev by default.

```
** (Mix) Could not start application sentry: exited in: Sentry.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) environment_name not configured
            (sentry) lib/sentry.ex:84: Sentry.check_required_env!/0
            (sentry) lib/sentry.ex:37: Sentry.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

**Comment by jeregrine** [comment]
If you check outhttps://github.com/getsentry/sentry-elixir/blob/master/lib/sentry.ex#L78 you need MIX_ENV or environment_name set.

**Comment by alexgaribay** [comment]
I think using `System.get_env("MIX_ENV")` at https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry.ex#L82 is the wrong way to grab the mix environment. The standard way to do so with Mix is with `Mix.env`. I find it very annoying to have to pass in `MIX_ENV=test mix test` just to do testing with `mix test` automatically sets the Mix environment to `:test`.

**Comment by jeregrine** [comment]
Using Mix.env in your application code is an anti-practice. I will make a
new issue to fix this.

**Comment by jeregrine** [comment]
@alexgaribay @omin You could also juset set environment_name in your test.exs
