### ISSUE TITLE
Cron Monitor integration for Oban

### ISSUE THREAD

**Issue by milmazz** [getsentry/sentry-elixir#720]
For a particular client, I'm in the process of upgrading their `sentry` client from `8.x` to `10.x`, while I was doing that I noticed the addition of two **great integrations** for Oban. So, I wanted to try those and after doing that, I wanted to share a couple of observations.

The Sentry documentation about the configuration options doesn't specify a minimum required Oban or Oban Pro version.  I think the docs should mention that the cron integration will only work if you have Oban Pro [v0.14 ](https://oban.pro/docs/pro/1.4.3/changelog.html#enhancements-1), or Oban [v.2.17.6](https://github.com/sorentwo/oban/releases/tag/v2.17.6).

![Screenshot 2024-04-16 at 1 40 44 PM](https://github.com/getsentry/sentry-elixir/assets/34700/c9779ad5-52a5-4942-afbb-ddddae1a4b29)

Another issue that I found is the current `monitor_slug`. While I see the telemetry handler implementation working and sending the check-ins, it seems that the `monitor_slug` is the raw `job.worker` (e.g., `MyApp.MyDummyWorker`), while the **Sentry UI** doesn't allow you to define such slug, even if the Monitor Cron title is `MyApp.MyDummyWorker`, Sentry lowercase that input and removes the dots, So, there is a mismatch in the config and the monitor doesn't catch the check-ins. I haven't tried creating the Cron Monitor programmatically to see if Sentry allows setting the monitor slug as is sent by the cron integration.

For now, at least in my case, is more important the upgrade from the sentry client from `8.x` to `10.x`. So, I will revisit the cron integration later, but I wanted to start a discussion here.

**Comment by whatyouhide** [comment]
@milmazz any chance you can give this branch a try? 🙃 https://github.com/getsentry/sentry-elixir/pull/721
