### ISSUE TITLE
Error with nested LiveViews

### ISSUE THREAD

**Issue by tomtaylor** [getsentry/sentry-elixir#733]
### Environment

LiveView 0.20.12, Sentry 10.6.0.

### Steps to Reproduce

1. Render a page which contains a nested LiveView

### Expected Result

It renders.

### Actual Result

```
[error] Sentry.LiveView.on_mount hook errored out: ** (RuntimeError) attempted to read connect_info from a nested child LiveView PoplarWeb.Admin.TaskManagerLive.

Only the root LiveView has access to connect_info.
```

Then the page rerenders.

**Comment by sl0thentr0py** [comment]
thx for the report
we'll have to make sure that we call `get_connect_info` only if the socket is not a child by checking `parent_pid` here
https://github.com/phoenixframework/phoenix_live_view/blob/8683020484a12fe6c552e27820469e49c87157c9/lib/phoenix_live_view/socket.ex#L65

**Comment by tomtaylor** [comment]
Thanks!
