### ISSUE TITLE
Sentry ignores remote IP address with nginx proxy

### ISSUE THREAD

**Issue by omin** [getsentry/sentry-elixir#74]
I'm not sure if it's related to the following issue but I only get 127.0.0.1 as the ip address.
![image](https://cloud.githubusercontent.com/assets/3143154/19413052/2a307c62-92d8-11e6-9438-a2b71ff6d0c1.png)
![image](https://cloud.githubusercontent.com/assets/3143154/19413055/30a3cf04-92d8-11e6-8ec6-42f9910742d7.png)
getsentry/sentry#1254

**Comment by h4cc** [comment]
We use nginx as reverse proxy as well, which is configured to add the common "X-Forwarded-For" header to forwarded request.

Having a configuration value to define a strategy where User IP Address should be taken from would be cool imho.

**Comment by omin** [comment]
I realized that this is a problem with phoenix. We need to use a package to overwrite remote ip with x-forwarded-for header.

**Comment by ijunaid8989** [comment]
@charleshan how you solved this ? which library did you use?
