### ISSUE TITLE
Periodically purge check-ins ETS table

### ISSUE THREAD

**Issue by whatyouhide** [getsentry/sentry-elixir#762]
> @nsweeting yep, you're right! I'll add some sweep functionality that clears the tables. 
> 
> @whatyouhide, is the best approach to clear the table -> remove any check-in ids that have a 'stop' or 'exception' event? or something like `memsup` to check the available RAM and then clear based on the oldest entries?
> 
> I'm going to reopen this to address what @nsweeting mentions. 

 _Originally posted by @savhappy in [#749](https://github.com/getsentry/sentry-elixir/issues/749#issuecomment-2264149450)_

Let's go with the GenServer that owns the table periodically sweeping it. Every ~30 seconds, it can send a message to itself, go through the all table and use `ets:select_delete` or something like that to remove all check-ins that are older than, say, 10 minutes. If needed we can add a timestamp to the check ins, I don't recall if we do that already.

**Comment by savhappy** [comment]
@whatyouhide question: what if a job runs longer than 10 minutes in Quantum? The start id would be something like "quantum-123" and stored in `ets` as an associated UUID value but when a stop event for the same "quantum-123" key happens the UUID would be different because the key would be reinserted.

**Comment by whatyouhide** [comment]
We shouldn't re-insert keys at `:stop` events, I had commented on the PR but maybe it got lost. We can make the sweep interval configurable so that users that have long-running jobs can keep data in memory for longer.
