### ISSUE TITLE
Validate all params passed to sentry even in dev/test

### ISSUE THREAD

**Issue by PragTob** [getsentry/sentry-elixir#766]
👋 
Me again, and thanks again!

It'd be great if even in dev/test mode Sentry validated all parameters/options passed. It does validate some but not all:

```
tobi@qiqi:~$ iex -S mix
iex(1)> Sentry.capture_message("hu", client: [oha: :nonsense])
:ignored
tobi@qiqi:~$ MIX_ENV=prod iex -S mix
iex(1)> Sentry.capture_message("hu", client: [oha: :nonsense])
** (NimbleOptions.ValidationError) invalid value for :client option: expected atom, got: [oha: :nonsense]
    (nimble_options 1.1.1) lib/nimble_options.ex:359: NimbleOptions.validate!/2
    (sentry 10.6.2) lib/sentry/client.ex:106: Sentry.Client.send_event/2
    iex:1: (file)
iex(1)> 

```

I suspect this behavior is because Sentry is deactivated, but it allows some bad options to slip through dev and test to production. I.e. I had somehow (don't ask me how) falsely assumed that I could pass an environment name to the client in `capture_message`'s optins: `client: [environment_name: System.get_env("ENV)]` - which made it all the way to production 😅 

So still checking that even if dsn isn't configured would be nice I think.

**Comment by savhappy** [comment]
@whatyouhide yep yep, on it!

**Comment by PragTob** [comment]
One more thought here that's probably a different topic:

While I love params validations for an error reporting library emitting a warning and ignoring them instead _may_ be better, as well not getting any error report can be a bit annoying (but probably a different topic).

Thanks for takcling this!
