### ISSUE TITLE
exception.values.0.stacktrace.frames: Missing value for required attribute

### ISSUE THREAD

**Issue by Dalepalmer** [getsentry/sentry-elixir#770]
### Environment

Version:  10.4.0
Erlang: 24.3.3
Elixir: 1.14.5

### Steps to Reproduce

1. Navigate to a missing URL in our prod env
2. Sentry receives an error without all information

### Expected Result

Route message to Sentry with the stacktrace.frames without error

### Actual Result

Sentry receives an error with 
`"errors":[{"type":"invalid_data","name":"threads.values.0.stacktrace.frames","reason":"expected a non-empty value"}]`

Errors hit sentry like so:
```
Process #PID terminating
** (exit) {{{%Phoenix.Router.NoRouteError{plug_status: 404, message: "no route found for GET /blog (BikeWeb.Router)", conn: %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...},
```

![Image](https://github.com/user-attachments/assets/51b7addd-affa-4651-93fd-d7358889adc6)

### Notes

I wanted to bring this issue up here because I found it in a handful of similar issues in other Sentry projects.

https://github.com/nuxt-community/sentry-module/issues/163
https://github.com/getsentry/sentry-android/issues/233
https://github.com/getsentry/sentry-react-native/issues/2429

My team is currently seeing this issue after upgrading from version 8.0.6

It only seems to happen in production so far, so I apologize for the poor reproduction steps. The is still a little bit of a mystery to myself and I'm looking for help to understand if it's something with sentry-elixir, or our application.

**Comment by whatyouhide** [comment]
Thanks for the report @Dalepalmer 💟 @savhappy wanna take a look?

**Comment by savhappy** [comment]
Thanks @Dalepalmer for raising the issue and linking the associated issues from others - it's very helpful 🧡 

`The Sentry protocol does not allow empty frames, an empty list, it should be null instead.. ` mentioned this in [getsentry/sentry-android #233](https://github.com/getsentry/sentry-android/issues/233) and the resounding fix in all of these is to ignore setting the frames if it doesn't exist.

@whatyouhide should we add this functionality into the Elixir SDK as well?

**Comment by whatyouhide** [comment]
@savhappy yes fantastic catch! Sounds good, if the list is empty then we set the whole thing to `null`.
