### ISSUE TITLE
`Sentry.Transport.Sender` can use a lot of memory

### ISSUE THREAD

**Issue by hkrutzer** [getsentry/sentry-elixir#773]
### Environment

v10.6.2

### Steps to Reproduce

This is memory usage with our base config:

![Image](https://github.com/user-attachments/assets/874904c5-56ec-4839-bfa1-01458275803c)

In absolute terms it is not that much memory, but it can go up to around 20MB and often appears in our top 20 of processes using the most memory. Manually triggering a garbage collection on the process reduces it by a lot.

I enabled source maps, which took it up to this:

![Image](https://github.com/user-attachments/assets/02d6323d-b4e8-4ed5-9c9a-f9dfe128d5eb)

and eventually caused our application to be OOM-killed.

The source map file is not that big:
```
Wrote 1412 files in 1.54 Mb to: _build/dev/lib/sentry/priv/sentry.map
```

Loading it manually with `:erlang.binary_to_term`:
```
iex(11)> byte_size(sourcemap)
1307912
```

I realise there are not many details in this issue but I'm not sure what to add. Please let me know what additional info you need.

**Comment by whatyouhide** [comment]
Mh this is definitely an issue but yeah it could take a while to debug, I'll try to look into it.

**Comment by whatyouhide** [comment]
@hkrutzer what's your error throughput that you are reporting to Sentry here? The issue with source maps will be fixed in `master` soon, but 20MB can be quite high unless your throughput is high.

**Comment by hkrutzer** [comment]
Not that high:

![Image](https://github.com/user-attachments/assets/c0ac9557-cead-4d8d-ac55-f6d4b1f0f27b)

(I'm assuming errors includes warnings, if not it might be 2 to 3 times as much, which is still not that high I would say).

**Comment by hkrutzer** [comment]
Don't see this issue anymore, memory for the Sender processes has gone down to around 2MB at max 🙂

**Comment by whatyouhide** [comment]
Fantastic, thanks for updating @hkrutzer! 💟
