### ISSUE TITLE
Oban undefined protocol

### ISSUE THREAD

**Issue by maennchen** [getsentry/sentry-elixir#779]
### Environment

* Sentry Lib: `10.7.0`
* Oban: `2.18.2`
* Oban Pro: `1.5.0-rc.1`
* Elixir: `1.17.2`
* Erlang: `27.0.1`

### Steps to Reproduce

* Setup Oban Integration
* Have an error in any oban job

### Expected Result

Error is reported.

### Actual Result

```
Failed to send Sentry event. Unable to encode JSON Sentry error - %Protocol.UndefinedError{protocol: Jason.Encoder, value: %Oban.Job{... (truncated)
```

**Comment by savhappy** [comment]
Looking into this! Thanks for the report @maennchen

**Comment by savhappy** [comment]
I was able to recreate this from a local repo. This is being logged as a warning and not an error - which is why it's not being reported. Setting up a test to pinpoint where this is happening. Stay tuned

**Comment by whatyouhide** [comment]
This should be solved with https://github.com/getsentry/sentry-elixir/commit/116140d6f9d2051635597919d7610a1471385cff. I think it was coming from the `integrations_meta` field, which is not being sent anymore. @savhappy can you confirm?

**Comment by savhappy** [comment]
Can confirm Oban errors are now reported! Thx @whatyouhide for adding that in 👍 @maennchen let us know if the issue persists after using the latest.

![Image](https://github.com/user-attachments/assets/12f7c87b-4abd-4587-9572-3e8c9cc209b3)

**Comment by whatyouhide** [comment]
(the latest is not released yet, to be clear)

**Comment by BobbyMcWho** [comment]
This was very surprising to us, just happened to notice this 2 weeks after upgrading to 10.7.0 :sadness: thanks for the fix
