### ISSUE TITLE
Error integrating with Phoenix

### ISSUE THREAD

**Issue by Rauulll** [getsentry/sentry-elixir#781]
### Environment

Versions:
- erlang 27.0
- elixir 1.17.2-otp-27

### Steps to Reproduce

Tried to implement on Phoenix. 

### Actual Result

Got the error below,  in MyApp.ErrorHTML.ex file
`undefined function sigil_E/2 (expected ChequeitWeb.ErrorHTML to define such a function or for it to be imported, but none are available)Elixir`

**Comment by whatyouhide** [comment]
Hi @Rauulll, thanks for the report. Anything pointing to Sentry here? This doesn't look like a Sentry issue. Maybe you could include the contents of the culprit file, and/or the stacktrace of the error?

**Comment by Rauulll** [comment]
the .ex file
`defmodule ChequeitWeb.PlaidHTML do
  use ChequeitWeb, :html

  def index(assigns) do
    ~H"""
    <section class="flex-center size-full max-sm:px-6">
      <section class="auth-form">
        <header class="flex flex-col gap-5 md:gap-8">
          <.link navigate={~p"/"} class="mb-12 cursor-pointer flex items-center gap-2">
            <img src={~p"/images/logo.svg"} alt="logo" class="size-[24px] max-xl:size-14" />
            <h1 class="text-30 font-ibm-plex-serif font-bold text-black-1">ChequeIt</h1>
          </.link>
          <div class="flex flex-col gap-1 md:gap-3">
            <h1 class="text-24 lg:text-36 font-semibold text-gray-900">
              Sign Up
            </h1>
            <p class="text-16 font-normal text-gray-600">
              Link your bank
            </p>
          </div>
        </header>
        <button phx-click="pushEvent('navigate', '/')" method="post" class="plaidlink-primary">Connect Bank</button>
      </section>
    </section>
    """
  end
end
`

**Comment by whatyouhide** [comment]
I'll close this out as there is nothing pointing to Sentry. @Rauulll if you will get any way of reproducing this please feel free to reopen the issue or comment down here. Thanks! 💟
