### ISSUE TITLE
Fallback to ancestor's context if available?

### ISSUE THREAD

**Issue by mtwilliams** [getsentry/sentry-elixir#79]
The `:proc_lib` module (and by extension `Task` module) record ancestors by shoving them into the process dictionary under `$ancestors`. Although a nasty hack, looking up context in from an ancestor would drastically help when trying to reproduce a bug.

Thoughts?

**Comment by mitchellhenke** [comment]
Thanks for the report.  Is this for `Sentry.Logger`?  I don't think this is something I'd feel comfortable adding without at least understanding the use case a little bit more.

My initial thought would be to have the children send a report on `terminate`?  Or have the supervisor handle the child crashes and report from there?

**Comment by mtwilliams** [comment]
Specifically [`Sentry.Context.get_context/0`](https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/context.ex#L50).

Something like,

```elixir
defp get_context, do: get_context(self())
defp get_context(process) do
  [dictionary: dict] = :erlang.process_info(process, [:dictionary])
  ancestor = Map.get(dict, :"$ancestors", []) |> Enum.first
  get_ancestor_context = fn -> if ancestor, do: get_context(ancestor) end
  Map.get_lazy(dict, @process_dictionary_key, get_ancestor_context)
end
```

**Comment by mtwilliams** [comment]
This means code that makes use of Tasks, like below, will show what request caused the crash in `App.Analysis.Connections.between/2`.

```elixir
get "/people/:id" do
  person = Task.async(fn -> App.Repository.get!(Person, :id) end)
  connections = Task.async(fn -> App.Analysis.Connections.between(id, viewer.id))
  contextualized = Map.merge(Task.await(person), %{connections: Task.await(connections)})
  PersonSerializer.json(contextualized, pretty: true)
end
```

**Comment by mitchellhenke** [comment]
Does that route use`Sentry.Plug`?

**Comment by mtwilliams** [comment]
It's in the chain, yes.

**Comment by mitchellhenke** [comment]
I see what you mean.  Something along the lines of:

```elixir
  def index(conn, _params) do
    Sentry.Context.set_user_context(%{id: 1})
    Task.async(fn -> 1 / 0 end)
    |> Task.await()
    render conn, "index.html"
  end
```

will crash but not include the user context that was set.

Adding the above code does not seem to work well within the current tests we have.  I am interested in finding a solution, but there doesn't seem to be a standard way to go up the tree either.

Absent a solution along those lines in the near term, I would probably avoid linking async tasks, and use Task Supervisors and `async_nolink` to avoid having the task bring down the request.  Then the task can exit on its own, and using [yield](http://elixir-lang.org/docs/stable/elixir/Task.html#yield/2) or `yield_many`, the request process will maintain its context, and would crash on a bad match from the result, or continue as normal.

**Comment by mtwilliams** [comment]
> Adding the above code does not seem to work well within the current tests we have.

Please elaborate.

> I am interested in finding a solution, but there doesn't seem to be a standard way to go up the tree either.

Undefined, but unchanging too.

**Comment by mitchellhenke** [comment]
Apologies for being unclear.  The code above causes tests to fail, and I'm not sure this feature is something we want to add if it depends on behavior that is not currently well-defined.

I would gladly review a PR for this as I think it would better illustrate how the feature could fit into the library.

**Comment by mtwilliams** [comment]
Why do the test fail?

The code I gave was illustrative – wrote it off the top of my head.

**Comment by mitchellhenke** [comment]
I don't recall, as I only tried briefly.

I am going to close this issue, as without more specifics around the implementation, it is difficult to discuss.  If you would like to submit a PR for the feature with tests, I would be happy to review and provide feedback. 🙂

**Comment by axelson** [comment]
Note: the elixir 1.8.0 release adds automatic `caller` tracking which would be very useful in this scenario.

https://elixir-lang.org/blog/2019/01/14/elixir-v1-8-0-released/

**Comment by mitchellhenke** [comment]
@axelson this is something definitely I plan to look into 🙂

**Comment by tfwright** [comment]
Hey! We are currently running into this exact issue using v8. Any updates on recommended ways to bring request context into errors reported inside async code blocks?
