### ISSUE TITLE
maybe_log_send_result/2 MatchError: no match of right hand side value: :too_many_retries

### ISSUE THREAD

**Issue by danielspofford** [getsentry/sentry-elixir#792]
### Environment

What version are you running? 10.7.1

### Steps to Reproduce

Ephemeral error in practice. This pattern https://github.com/getsentry/sentry-elixir/blob/10.7.1/lib/sentry/transport/sender.ex#L77 does not always match. It is possible for the right hand side to be `:too_many_retries`, perhaps from https://github.com/getsentry/sentry-elixir/blob/10.7.1/lib/sentry/transport.ex#L45.

### Expected Result

The general approach in `maybe_log_send_result/2` is to gracefully log and return, so my expectation for this error case would be the same rather than raising an exception.

### Actual Result

![Image](https://github.com/user-attachments/assets/af0f6622-c09c-4c48-9b71-359ebb485e33)

**Comment by savhappy** [comment]
@danielspofford Absolutely, we have an error message that should have been logged here. Working on a PR for this. Thanks for the report!

**Comment by danielspofford** [comment]
Awesome @savhappy, thank you!
