### ISSUE TITLE
Log errors as warnings in `Sentry.Transport.encode_and_post_envelope`

### ISSUE THREAD

**Issue by whatyouhide** [getsentry/sentry-elixir#796]
Internal refactoring.

**Comment by savhappy** [comment]
@whatyouhide is this the ticket for refactoring `maybe_log_send_result` fn to the newly created `encode_and_post_envelope` fn?

**Comment by whatyouhide** [comment]
@savhappy yes exactly

**Comment by whatyouhide** [comment]
Closed in #799.
