### ISSUE TITLE
Please include `request_id` in data submitted by `Sentry.Plug`

### ISSUE THREAD

**Issue by myronmarston** [getsentry/sentry-elixir#80]
Plug provides [`Plug.RequestId`](https://hexdocs.pm/plug/Plug.RequestId.html#content), which assigns a unique request id to every request.  If you're using Phoenix, it [automatically wires this up](https://github.com/phoenixframework/phoenix/blob/996a83a27d8ccdc7e0e3bdda9c21d537b19b2002/installer/templates/new/lib/app_name/endpoint.ex#L22) for you.

Given `request_id` goes in `Logger.metadata` and we have configured logger to include it in every message, it would be suuuuper useful in `Sentry.Plug` sent the request id to sentry when reporting errors.  Then when investigating the cause of an error, I can grep through our logs looking for that request id to find every single log message related to the request.

Would you consider sending `request_id` to sentry from `Sentry.Plug`?

**Comment by jeregrine** [comment]
@myronmarston good call, we should be able to do this without using logger or metadata, we'll just use the conn.

**Comment by mitchellhenke** [comment]
Release 1.1.1 should include this :)
