### ISSUE TITLE
Oban ErrorReporter can crash and detach future telemetry events

### ISSUE THREAD

**Issue by GregMefford** [getsentry/sentry-elixir#805]
### Environment

What version are you running? Etc.

* Sentry version: `10.7.1`
* Oban version: `2.18.3`

### Steps to Reproduce

Looking through server logs for disconnected telemetry handlers, I found the log below, which appears to be due to a `:timeout` error.

### Expected Result

I think [this code](https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/integrations/oban/error_reporter.ex#L40) should probably account for non-Exceptions somehow.

### Actual Result

In this example, the `exception` is `:timeout` rather than being an `Exception` struct.

```
Handler Sentry.Integrations.Oban.ErrorReporter has failed and has been detached. Class=:error
Reason=:undef
Stacktrace=[
  {:timeout, :__struct__, [], []},
  {Sentry.Integrations.Oban.ErrorReporter, :handle_event, 4,
   [file: ~c"lib/sentry/integrations/oban/error_reporter.ex", line: 40]},
  {:telemetry, :"-execute/3-fun-0-", 4,
   [file: ~c"/tmp/project/deps/telemetry/src/telemetry.erl", line: 167]},
  {:lists, :foreach_1, 2, [file: ~c"lists.erl", line: 1442]},
  {Oban.Queue.Executor, :emit_event, 1,
   [file: ~c"lib/oban/queue/executor.ex", line: 284]},
  {Oban.Backoff, :with_retry, 3, [file: ~c"lib/oban/backoff.ex", line: 108]},
  {Task.Supervised, :invoke_mfa, 2,
   [file: ~c"lib/task/supervised.ex", line: 101]},
  {Task.Supervised, :reply, 4, [file: ~c"lib/task/supervised.ex", line: 36]}
]
```

**Comment by whatyouhide** [comment]
@savhappy any chance you could look into this?

**Comment by savhappy** [comment]
@whatyouhide yep yep!

**Comment by savhappy** [comment]
Okay, I had a look and we'll forward anything not matching an exception to `capture_message` instead. Will have a PR out shortly! Thanks @GregMefford for the report 💟

**Comment by savhappy** [comment]
PR #807 out for review

**Comment by GregMefford** [comment]
Hey, I was just curious what release cadence I should expect. I've been checking the releases on GitHub once in a while to see when we can get this fix deployed in our app, but it looks like the [latest release was September 5](https://github.com/getsentry/sentry-elixir/releases/tag/10.7.1). Thanks! ❤

**Comment by savhappy** [comment]
@GregMefford release [10.8.0](https://github.com/getsentry/sentry-elixir/releases/tag/10.8.0) is out as of this morning!
