### ISSUE TITLE
Incomplete doc note

### ISSUE THREAD

**Issue by kacorvus** [getsentry/sentry-elixir#806]
under capture_exception, there is a note about opts

```
The opts argument is passed as the second argument to [send_event/2](https://hexdocs.pm/sentry/Sentry.html#send_event/2).
```

It doesn't discuss the the opts split off and sent to create_event here ` {send_opts, create_event_opts} = Options.split_send_event_options(options)`

**Comment by whatyouhide** [comment]
This has been fixed in `master`.
