### ISSUE TITLE
Tags context - question

### ISSUE THREAD

**Issue by lkananowicz** [getsentry/sentry-elixir#813]
Hi, I am using:

```
Sentry.Context.set_tags_context(%{
  token: "value",
  client: client.name
})
```

and I am not sure where I should look for this info on Sentry web portal, should this be associated with a specific issue. So far I could not find that information on Sentry web portal and I know this was deployed long time ago. Any suggestions on how to debug this problem?

Best regards,
Leon

**Comment by whatyouhide** [comment]
Hi Leon are you reporting any errors? Also, the context is per process, are you reporting errors in the same process where you're calling `set_tag_context/1`?

**Comment by lkananowicz** [comment]
Thanks, yeah, I see it is usually in another process or controller action did not invoke `Sentry.Context.set_tags_context` before the error was triggered 😛. I am going to close this now as I see it just a problem in the app and it is more of coverage problem.
