### ISSUE TITLE
Unlock poison dep

### ISSUE THREAD

**Issue by QuentinFchx** [getsentry/sentry-elixir#82]
Poison lib is now 3.x (https://github.com/devinus/poison).
Is it possible to unlock the dep ?
currently `{:poison, "~> 1.5 or ~> 2.0"}`

**Comment by mitchellhenke** [comment]
Yep, absolutely.

**Comment by mitchellhenke** [comment]
Release 1.1.1 should now allow Poison 3.0 :)
