### ISSUE TITLE
How to poreply caputre errors from plug parser/hadle_error?

### ISSUE THREAD

**Issue by marknefedov** [getsentry/sentry-elixir#821]
I was able to configure Sentry to log direct `raise` and `Logger.error`, but I can't capture exceptions from `handle_error`/`plug Parsers.`

```
21:23:13.538 [error] ** (Plug.Conn.WrapperError) ** (Plug.Parsers.ParseError) malformed request, a Jason.DecodeError exception was raised with message "unexpected byte at position 16: 0x73 (\"s\")"
    (plug 1.16.1) lib/plug/parsers/json.ex:95: Plug.Parsers.JSON.decode/3
    (plug 1.16.1) lib/plug/parsers.ex:340: Plug.Parsers.reduce/8
```

Here is repoduction proejct, specify DSN in the config.
[plug_example.zip](https://github.com/user-attachments/files/17692573/plug_example.zip)

to run query in question,
```sh
curl -X POST -H "Content-Type: application/json" -d '{borkedjson}' http://localhost:4000/test1/test2
```

**Comment by whatyouhide** [comment]
`Plug.Parsers.ParseError` is ignored by default in [`Sentry.DefaultEventFilter`](https://hexdocs.pm/sentry/10.8.0/Sentry.DefaultEventFilter.html) because it's an easy attack vector: just spam a server with badly-encoded JSON (or other formats) and you'll burn through its Sentry quota. You can customize the event filter with `:before_send`.

Let us know if you still have issues! 💟

**Comment by marknefedov** [comment]
Hi, thanks for the response, is it because of it is not possible to prevent this plug error from bubbling up? 
I’ve believe it was your post to make it possible to change it in Plug, but it was dismissed as it would change Plug semantics? I’m currently trying to suppress this error and was using as a general test to check if I configured Sentry correctly. So if other error will raise in some other plug it will be captured?

**Comment by whatyouhide** [comment]
Hi @marknefedov I have some trouble understanding what you're asking. In general Plug errors are captured unless they are excluded by an event filter, yes, if that's what you're asking.
