### ISSUE TITLE
LiveView has reached 1.0.0

### ISSUE THREAD

**Issue by greg-freewave** [getsentry/sentry-elixir#825]
LiveView has reached 1.0.0 🎉 

This project requires ~> 0.20 which is incompatible. Upgrade the LiveView dep?

**Comment by phinnaeus** [comment]
Is this worthy of a new release of `sentry` on Hex? I've updated my project to point to `{:sentry, github: "getsentry/sentry-elixir", ref: "ce8654b0b6afd158cee9fe9f7891a79aef6e6e0d"}` now but not ideal

**Comment by whatyouhide** [comment]
Yes, @solnic can you get a patch release up?

**Comment by solnic** [comment]
> Yes, [@solnic](https://github.com/solnic) can you get a patch release up?

Sure, will do
