### ISSUE TITLE
Is this supposed to provide a backend for Elixir Logger?

### ISSUE THREAD

**Issue by ctrlShiftBryan** [getsentry/sentry-elixir#83]
Should I expect calls to Logger.error to get sent? It appears not.

I would say that it provides an "erlang report handler" in the documentation instead of an "Elixir back end".

Is adding an actual Elixir back end logger a feature you would want to add?

**Comment by Mazyod** [comment]
I'm very interested in this one as well, since it's the main reason I am looking for an error reporting tool besides just relying on papertrail logging.

**Comment by jeregrine** [comment]
So the original code base was a Logger Backend before we moved to this style. 

https://github.com/getsentry/sentry-elixir/commit/8448f3699c70d60899009536d6dd9ff3d6df59e5

The issue with Logger backend's is that we lose all fidelity and context of what exception _actually_ occurred. Logger will format and render the exception and stack trace as text before handing it off to you. So the previous version of this library would attempt to parse and extract the information form the text. 

If you'd like to do further analysis of logs you could very easily create a logger backend that feeds into sentry. The behaviour is pretty small https://github.com/getsentry/sentry-elixir/commit/8448f3699c70d60899009536d6dd9ff3d6df59e5#diff-e2b84f49dbbced2d1aec1d27a367d0d8

**Comment by mitchellhenke** [comment]
Yeah, you are correct that `Logger.error` messages will not be handled or sent.  I'm not sure it's something we want to add, as we found it hard to work with.

As Jason said, adding your own Logger backend is probably the best way for now, and then have it send Sentry events.  If there is a good solution you find that generalizes well, and you think would be helpful to include in the library, I would be very happy to take a look.

**Comment by SimonWoolf** [comment]
In case it's helpful to anyone else coming across this issue: I made a drop-in Sentry logger backend - [github](https://github.com/simonwoolf/sentry-logger-backend), [hex package](https://hex.pm/packages/sentry_logger_backend).

(sentry-elixir devs: I'd be very happy if you want to include it the main package -- just say the word and I'll do a PR. Equally, if you'd rather it be kept a separate package, that's fine too)

**Comment by mitchellhenke** [comment]
@SimonWoolf For now, my feeling is that the current Logger backend is a more important focus for us.  Your package clearly fills a need, but for now I think they can co-exist separately.  I will link to it in the README though.

Thanks! 🙂
