### ISSUE TITLE
Make PRs in CHANGELOG.md linkable

### ISSUE THREAD

**Issue by ruslandoga** [getsentry/sentry-elixir#838]
Right now the PR tags in CHANGELOG.md are plain text. Would be easier if they were links :)

**Comment by whatyouhide** [comment]
They're autogenerated (in another tool—see https://github.com/getsentry/publish and https://github.com/getsentry/craft) so it's a bit annoying to do that for this particular repo. Feel free to open issues there! Thank you. cc @sl0thentr0py @stephanie-anderson
