### ISSUE TITLE
protocol Enumerable not implemented for nil

### ISSUE THREAD

**Issue by rawkode** [getsentry/sentry-elixir#84]
Adding the following code to my `router.ex` in my Phoenix application results in an exception during exceptions ...

```elixir
use Plug.ErrorHandler
use Sentry.Plug
```

```
Protocol.UndefinedError at GET /health-check222
protocol Enumerable not implemented for nil
```

![sentry](https://cloud.githubusercontent.com/assets/145816/20278976/a5100456-aa9e-11e6-81af-bc840a3fbc30.png)

**Comment by jeregrine** [comment]
@rawkode I see the error, to fix for now please set the included_environments variable in your config and I will see if we can cut a new release today

**Comment by rawkode** [comment]
My config actually includes that:

```
# Sentry
config :sentry, dsn: "https://" <> System.get_env("SENTRY_USERNAME") <> ":" <> System.get_env("SENTRY_PASSWORD") <> "@app.getsentry.com/" <> System.get_env("SENTRY_APPLICATION"),
  included_environments: ~w(dev prod),
  environment_name: Mix.env()
```

**Comment by jeregrine** [comment]
@rawkode well one issue is that included environments needs to be a list of atoms, you can add an a to the end of it like so `~w(dev prod)a`.

I'm looking into it now .

**Comment by rawkode** [comment]
D'oh! That fixed it for me. Thanks for your help, @jeregrine

**Comment by jerel** [comment]
For whatever it's worth I'm still seeing this issue using the latest version if `included_environments` is not used. To replicate: install sentry in the router using `use Sentry.Plug` and don't add any config except in config/prod.exs. Any errors in development will throw `Enumerable not implemented for nil`

**Comment by alex88** [comment]
Same here too, maybe there should be some defaults in every environments or a fallback in the code where it loads the `included_environments`

**Comment by alex88** [comment]
Oh seems https://github.com/getsentry/sentry-elixir/pull/124 and #118  should fix this
