### ISSUE TITLE
Error: Event dropped due to filter

### ISSUE THREAD

**Issue by Mazyod** [getsentry/sentry-elixir#89]
Hello again,

Now that I've been running Sentry on my elixir instance for a while, I'm seeing random errors logged in the elixir app itself with a result "event dropped due to filter". In my project settings I have "Filter out known web crawlers", so I am guessing that's the filter in question.

The issue here is why would it be logged as an error? It is causing the papertrail logger to report false positives. Wouldn't it make sense to silently accept that the log was rejected, or at most log it as either a debug or info message?

Here are the logs in question. I tried my best to format it better.

```
[error] Failed to send sentry event. 
{"user":{},"timestamp":"2016-11-15T22:02:46.763155Z","tags":{},"stacktrace":{"frames":
[
  {"module":"cowboy_protocol","lineno":442,"function":":cowboy_protocol.execute/4","filename":"src/cowboy_protocol.erl"},
  {"module":"Elixir.Plug.Adapters.Cowboy.Handler","lineno":15,"function":"Plug.Adapters.Cowboy.Handler.upgrade/4","filename":"lib/plug/adapters/cowboy/handler.ex"},
  {"module":"Elixir.Socks.Endpoint","lineno":1,"function":"Socks.Endpoint.call/2","filename":"lib/socks/endpoint.ex"},
  {"module":"Elixir.Socks.Endpoint","lineno":1,"function":"Socks.Endpoint.phoenix_pipeline/1","filename":"lib/socks/endpoint.ex"},
  {"module":"Elixir.Socks.Router","lineno":64,"function":"Socks.Router.call/2","filename":"lib/plug/error_handler.ex"},
  {"module":"Elixir.Socks.Router","lineno":1,"function":"Socks.Router.do_call/2","filename":"web/router.ex"},
  {"module":"Elixir.Socks.Router","lineno":1,"function":"Socks.Router.match_route/4","filename":"web/router.ex"}
]},
"server_name":"dama-server","request":{"url":"http://topgadgeturi.com:80/","query_string":"","method":"GET",
"headers":{"user-agent":"Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)","pragma":"no-cache",
"host":"topgadgeturi.com","from":"bingbot(at)microsoft.com","connection":"Keep-Alive","cache-control":"no-cache",
"accept-encoding":"gzip, deflate","accept":"*/*"},
"env":{"SERVER_PORT":80,"SERVER_NAME":"topgadgeturi.com","REQUEST_ID":"8d3pv3i852pmec0503meco5q34cvsu7c","REMOTE_PORT":2524,
"REMOTE_ADDR":"207.46.13.181"},"data":{},"cookies":{}},"release":"dfda8213a158c980581935e1307b4e50ba8df1ba",
"platform":"elixir","message":"(Phoenix.Router.NoRouteError) no route found for GET / (Socks.Router)",
"level":"error","extra":{},"exception":
[
  {"value":"no route found for GET / (Socks.Router)","type":"Elixir.Phoenix.Router.NoRouteError"}
],
"event_id":"74dfe32b38ee48078ee4a5149b592bdf","environment":"prod","culprit":"Socks.Router.match_route/4","breadcrumbs":[]} 
Received 403 from Sentry server: Event dropped due to filter
```

**Comment by jeregrine** [comment]
@Mazyod this looks like you are getting hit by the "bingbot" which is a Microsoft Bing search engine scraping server. It looks like Sentry has a filter to drop this kind of error. I'll ping them to see if there is something we should be doing to handle this specifically.

**Comment by Mazyod** [comment]
Thanks for the response, @jeregrine. I would just like to emphasize that sentry service is doing a great job at filtering this event, I just think the elixir client needs to realize that this is intentional and "by design", hence shouldn't log any errors to the console/Logger.

**Comment by mitchellhenke** [comment]
It's tough because Sentry will also return HTTP 403 for things like bad credentials, etc., so we couldn't exclude based on 403 status.

I'm not sure if it would be good for us to drop messages in the end anyway, as some users may want to see these logs.

**Comment by Mazyod** [comment]
@mitchellhenke Users wanting to see this log is a reasonable assumption, but my argument is that no one expects it to be logged as an error. Wouldn't you agree?

I sympathize with the inability to easily differentiate between intentional and faulty situations. I would certainly hope people from Sentry would mitigate this with a header field or similar.

**Comment by jeregrine** [comment]
@Mazyod Thanks for reporting this, the solution suggested by the sentry team is to just log as a warning for now. We'll need to cut a new release soonish
