### ISSUE TITLE
Can you publish an updated version?

### ISSUE THREAD

**Issue by myronmarston** [getsentry/sentry-elixir#9]
The version on Hex is at 0.0.5 but there have been many changes since that version.  Any reason you haven't published updated versions?

**Comment by jeregrine** [comment]
This package has been transferred to Sentry proper. We'll be making a great deal of changes in the near term to bring it up to speed with existing Sentry libraries. 

This will likely come with some major version changes and a new package name on hex.

**Comment by jwarlander** [comment]
Nice to hear! So if I'd be starting to look at using Sentry for Elixir right now, would I be likely to see some new cool things being published within the near future?

**Comment by jeregrine** [comment]
Yes.

**Comment by mitchellhenke** [comment]
@myronmarston @jwarlander we've released a new version to hex (1.0.0), but it will require you to change the dependency name and configuration if you are on an older version :)
