### ISSUE TITLE
ErrorLogger will not report all exceptions

### ISSUE THREAD

**Issue by DavidAntaramian** [getsentry/sentry-elixir#90]
Discussed this with @mitchellhenke last night. I'll detail the issue here and let you decide what, if anything, needs to be done.

Currently, the Sentry's [`:error_logger` handler](https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/logger.ex), which captures exceptions reported by `:error_logger`, is only set to capture errors reported with the `:error_report` tag, which reports a process crash. It will _not_ capture exceptions reported with the `:error` tag which is sent as an exception report.

Consider the following two problems (note, the error here is that we are trying to enumerate over a binary):

```elixir
Task.async(fn -> Enum.each("hello", &IO.puts/1) end)
```

This causes the process running the task to crash and sends an `:error_report` via `:error_logger`. Therefore, this error will be seen by Sentry and reported.

```elixir
Process.spawn(fn -> Enum.each("hello", &IO.puts/1) end, [])
```

This causes the process running the task to report an exception and then exit. It reports an error as `:error` via `:error_logger`, therefore this error will not be seen by Sentry.

An important thing to note is that `:error` reports do not contain process information (_i.e._, the process dictionary is not included in the report, therefore the report will not contain any Sentry contextual data).

**Comment by DavidAntaramian** [comment]
Just to follow up, `:error_report` seems to be sent whenever an OTP-compliant / supervised process exits abnormally.

I'm still trying to figure out under what circumstances `:error` is sent.

To give more context, I was running an app that included Phoenix and for various reasons was not using `Plug.ErrorLogger`. I was expecting that errors that occurred would be reported to Sentry regardless via the `:error_logger` system. They weren't, even though everything seems to suggest they should (Plug terminates the request using `exit/1` which is reported via `:error_report` as far as I can tell). There are a bunch of rabbit holes that this could probably be followed down, but I'd be interested to know if anyone else is having issues with exceptions not being reported.

**Comment by DavidAntaramian** [comment]
After some digging, I figured out that the `:error` from Phoenix is actually being triggered by Ranch: https://github.com/ninenines/ranch/blob/master/src/ranch_conns_sup.erl#L316. 

Essentially, if you don't have the `Plug.ErrorLogger` being used (which I don't because it screws up CORS when there's an error), any error will cause a termination that is reported by Ranch using `:error_logger.error_msg/2`. This in turn causes an `:error` notice to be sent to the `:error_logger` app.

**Comment by edevil** [comment]
@DavidAntaramian Could you elaborate on how Plug.ErrorLogger screws up CORS requests when an error occurs? Thanks.

**Comment by mitchellhenke** [comment]
This is a bit roundabout, and I _think_ I understand it now, but the root issue is that Plug pipelines with`Plug.ErrorHandler` will have the `conn` state "unwound" to what it was at the beginning of that pipeline.

The Plugs that do things in front of `Plug.ErrorHandler` will do thing normally (set headers, etc.), but if it catches an error, the `conn` that is ultimately returned by the request will have the state that it had at the beginning (and lose headers or whatever else that were set afterwards).

The issue is described here: https://github.com/elixir-lang/plug/issues/486

I'll be updating the docs to clarify this, and exploring solutions to see if it can be resolved well enough within the library itself.
