### ISSUE TITLE
Support Sentry.Context.set_http_context/1

### ISSUE THREAD

**Issue by DavidAntaramian** [getsentry/sentry-elixir#92]
It seems that the `:request` key is supported for `Sentry.capture_exception/2`, but it can't be set ahead of time. The SDK documentation seems to indicate that this should be supported: https://docs.sentry.io/clientdev/context/#common-context-methods

Essentially, I'm trying to do the same thing as `Sentry.Plug` but setting it at the time the plug is called so that `Sentry.capture_exception/2` reports will have it.

**Comment by Mazyod** [comment]
It looks supported to me:

Here is where the context is set ahead of time, it works per process like Logger.metadata
https://github.com/getsentry/sentry-elixir/blob/141e7a58b7b10e2907d121f11711b58ce3777daf/lib/sentry/context.ex#L30

Here is where it is accessing the process context and sending it with the `Event`, which is what an exception gets transformed to:
https://github.com/getsentry/sentry-elixir/blob/141e7a58b7b10e2907d121f11711b58ce3777daf/lib/sentry/event.ex#L43

e.g.

```elixir
Sentry.Context.set_extra_context(%{request: request_id})
Sentry.capture_exception(...) # correctly pulls context from Process dictionary
```
