### ISSUE TITLE
Not reporting test event and Phoenix Channel errors?

### ISSUE THREAD

**Issue by deepflame** [getsentry/sentry-elixir#93]
Hi guys,

I have a Phoenix app and followed the instruction to add Sentry logging to it.
When I run

    MIX_ENV=prod mix sentry.send_test_event

it also says that it is sending the test event. Great!
However nothing shows up in the web console on `sentry.io`. Is that normal?

If so, I wanted to catch an error that I get in my Phoenix sockets with `check_origin`. I have seen that this triggers a `Logger.error` call.
So I put `use_error_logger: true` in my config. Now this error should be caught, right?

**Comment by thruflo** [comment]
Hey,

I'm experiencing the same thing.  Did you resolve / was it an delay on sentry's side?

Thanks,

James.

**Comment by mitchellhenke** [comment]
Yep, I have a proposed fix here: https://github.com/getsentry/sentry-elixir/pull/94

The issue was that since we do the request asynchronously, we'd start the request process and the mix task would end nearly immediately (potentially before the request could be sent).

**Comment by mitchellhenke** [comment]
Also thank you for the report 🙂
