### ISSUE TITLE
Timestamp parameter is invalid and ignored

### ISSUE THREAD

**Issue by doughsay** [getsentry/sentry-elixir#99]
Just updated to sentry-elixir 2.0.2, and my events are getting this error when displayed in the sentry UI.  Also, the "First Seen" and "Last Seen" are always "n/a".  See screenshot:

![screen shot 2016-12-08 at 5 56 13 pm](https://cloud.githubusercontent.com/assets/221693/21034888/0f82231c-bd70-11e6-96e4-214b573c202f.png)

I assume the two are related...

Also, I don't know if this has anything to do with version 2.0.2, I think it's just been not working the whole time.  But, I only recently started getting that red bar at the top of the sentry ui.

**Comment by mitchellhenke** [comment]
I believe this was fixed as much as the library can fix the issue in #100.  If you continue to have problems, please just open another issue, and I'll see what can be done on client or server side. 🙂

**Comment by doughsay** [comment]
Thanks!  Sorry for my lack of responses; I'm confident this is all we can do from the library side as well.  I'll keep my eye out on the misbehaving events to see if I can figure anything else out.  So far, things seem to have magically fixed themselves.  Thanks again!

**Comment by mitchellhenke** [comment]
@doughsay no worries, thanks for reporting this!
